### ISSUE TITLE
error: unable to retrieve session token

### ISSUE THREAD

**Issue by TorulfDanielsson** [icanos/hassio-plejd#10]
Installed the addon yesterday and  it was up and running. Decided to rename the lights in Plejd but the new names seems to show up i hassio without problems. This evening i get the error below. It was working well before. Have a plejd gateway installed and run Home Assistant 0.103.0 Hassos HassOS 3.7, on a RPi 3+. Any clues on where to start.

[18:44:28] INFO: Starting the Plejd service...
[18:44:28] INFO: Verified permissions on startup script
[18:44:28] INFO: Executing startup script
[18:44:30] INFO: Wrote plejd.json
[18:44:30] INFO: Running add-on
error: unable to retrieve session token response: Error: Request failed with status code 403
[18:44:32] INFO: Starting the Plejd service...
[18:44:32] INFO: Verified permissions on startup script
[18:44:32] INFO: Executing startup script
[18:44:34] INFO: Wrote plejd.json
[18:44:34] INFO: Running add-on
error: unable to retrieve session token response: Error: Request failed with status code 403

**Comment by axlthorell** [comment]
Could you verify your plejd login credentials? 
Does your plejd config look something like this?
```
{
  "site": "Yoursitename",
  "username": "your@email.com",
  "password": "!secret plejd_password",
  "mqttBroker": "mqtt://localhost",
  "mqttUsername": "mqttusername",
  "mqttPassword": "mqttpassword",
  "includeRoomsAsLights": false
}
```

**Comment by TorulfDanielsson** [comment]
Seems to be exactly like that and it was working last night and this morning. The only thing (deliberately) that was changed was the naming in plejd app and as a result entity names in hass.

`{
  "site": "xxxx",
  "username": "xxxx",
  "password": "xxxx",
  "mqttBroker": "mqtt://localhost",
  "mqttUsername": "xxxx",
  "mqttPassword": "xxxx",
  "includeRoomsAsLights": false
}`

**Comment by icanos** [comment]
Hmm, strange. 403 means Forbidden, have you verified your credentials?

**Comment by TorulfDanielsson** [comment]
Updated add-on to 0.1.0 and verified that the password is correct. Changed to a new password, still the same problem. Tried change to "user" instead of "installer".  Tried with gateway disconnect. Still the same problem. 

Noticed that my RTR-01 was marked "unknown device" in the plejd app. Power-cycled (some plejd) after a while everything look normal.

Should i create a user only for hass? Now i use the same user as in the plejd app.

**Comment by icanos** [comment]
If you feel comfortable using Postman, please send me an email to further investigate what happens.

**Comment by TorulfDanielsson** [comment]
Sending an email. When starting the addon i noticed that my connected RTR-01 seems to go crazy - if i look in plejd app.

![Screenshot_20191220-130233](https://user-images.githubusercontent.com/26775807/71265257-1d087d80-2346-11ea-83bb-379e6238c5f4.png)

**Comment by icanos** [comment]
Interesting, can you check to see if the Plejd add-on is connecting to one of the RTR-01 devices? Check the Device ID in the app and then in Hass.io restart the add-on and check the log to see which device it connects to.

**Comment by icanos** [comment]
Check if your site name contains any Swedish characters, and if that's the case, are you willing to try and remove those to see if that changes anyhting?

**Comment by TorulfDanielsson** [comment]
Uninstalled add-on and reinstalled. Still fails. Will try to change password etc again.

[21:32:19] INFO: Starting the Plejd service...
[21:32:19] INFO: Verified permissions on startup script
[21:32:19] INFO: Executing startup script
[21:32:20] INFO: Wrote plejd.json
[21:32:20] INFO: Running add-on
starting Plejd add-on v. 0.2.5
plejd-api: login()
logging into NE666
error: unable to retrieve session token response: Error: Request failed with status code 403

**Comment by thowik-git** [comment]
Any success in solving this? I got the same issue and have tried all suggested actions without good results.

**Comment by icanos** [comment]
Only thing I can think of is any Swedish characters in the username/password. Otherwise I’m not sure, can you try using Postman to make an API request manually?

**Comment by TorulfDanielsson** [comment]
Have not been able to resolve this. Removed all Swedish characters (everywhere) changed password and site name etcetera. Nothing has helped - tried every release. Will do a complete re installation this weekend as i am moving over to SSD.

**Comment by jzee** [comment]
I had the same problem when I started with the plugin. I had used the wrong login credentials. 

Checking that I used the same email and password that I used for the plejd app, after resetting the password and removing special characters from my password in the plejd app fixed it for me.

HTH

**Comment by icanos** [comment]
If this still is an issue, please reopen. Thank you!
