### ISSUE TITLE
failed to start discovery. Make sure no other add-on is currently scanning

### ISSUE THREAD

**Issue by pezmannen** [icanos/hassio-plejd#103]
Hi

Running Hassio on ubuntu and getting the error below. Any tips?

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Plejd
 Adds support for the Swedish home automation devices from Plejd.
-----------------------------------------------------------
 Add-on version: 0.4.7
 There is an update available for this add-on!
 Latest add-on version: null
 Please consider upgrading as soon as possible.
 System: Ubuntu 18.04.5 LTS  (amd64 / qemux86-64)
 Home Assistant version: 0.114.4
 Supervisor version: 235
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[12:21:54] INFO: Starting the Plejd service...
[12:21:54] INFO: Verified permissions on startup script
[12:21:54] INFO: Executing startup script
[12:21:54] INFO: Wrote plejd.json
[12:21:54] INFO: Running add-on
starting Plejd add-on v. 0.4.7
plejd-api: login()
plejd-api: logging into Johansson
plejd-api: got session token response
plejd-api: getSites()
plejd-api: got site list response
plejd-api: getSite(...)
plejd-api: got site details response
wireEvents()
init()
plejd-ble: error: failed to start discovery. Make sure no other add-on is currently scanning.
plejd-mqtt: connected to mqtt.
plejd-mqtt: discovered light (DIM-01) named Taklampa with PID 19.
plejd-mqtt: discovered light (DIM-01) named Toalett EP with PID 15.
plejd-mqtt: discovered light (DIM-01) named Kök with PID 11.
plejd-mqtt: discovered light (DIM-01) named Korridor EP with PID 13.
plejd-mqtt: discovered light (DIM-01) named Groventré with PID 21.
plejd-mqtt: discovered light (DIM-01) named Trappa with PID 17.
plejd-mqtt: discovered switch (Scene) named Allt av with PID 2.
plejd-mqtt: discovered switch (Scene) named Allt på with PID 1.
plejd-mqtt: discovered switch (Scene) named Natt with PID 3.
plejd-mqtt: discovered switch (Scene) named Bortrest with PID 4.
plejd-mqtt: discovered switch (Scene) named Hemkomst with PID 6.
plejd-mqtt: discovered switch (Scene) named Semester with PID 7.

**Comment by icanos** [comment]
Make sure to run it in privilege mode of you haven’t allowed your user account permissions to dbus.

Try run it with sudo.

**Comment by pezmannen** [comment]
> Make sure to run it in privilege mode of you haven’t allowed your user account permissions to dbus.
> 
> Try run it with sudo.

Could you elaborate? Not an ubuntu pro

**Comment by pezmannen** [comment]
How do I run the add-on in privileged mode?

**Comment by pezmannen** [comment]
Figured out my issue. I am running on an old Mac mini. Doesn't have bluetooth LE. Bought a usb adapter and now it workds great
