### ISSUE TITLE
No state change on scene

### ISSUE THREAD

**Issue by ruzzbug1** [icanos/hassio-plejd#109]
The state doesn't change when triggering a scene. The state is always "off" and as far as I know (HA newbie), mqtt doesn't recieve a message from plejd when triggering a scene. Therefore I can't trigger an event or entity in HA from my plejd scene buttons.

**Comment by f00dagi** [comment]
Identical to #85?
https://github.com/icanos/hassio-plejd/issues/85

**Comment by icanos** [comment]
I will be removing scenes from the integration as it doesn't work, since Plejd scenes aren't something that triggers a BLE event. Because of that, there is no way for me to get informed whether or not a state changes.
