### ISSUE TITLE
Cannot add repo

### ISSUE THREAD

**Issue by MrTengvall** [icanos/hassio-plejd#11]
Hi,

For some reason I cannot add the repo; https://github.com/icanos/hassio-plejd/ to Hassio. Any idea why. Help is really appreciated.

**Comment by MrTengvall** [comment]
From log:
19-12-19 19:16:33 ERROR (MainThread) [hassio.store.git] Can't clone https://github.com/icanos/hassio-plejd/ repository: Cmd('git') failed due to: exit code(128)
  cmdline: git clone --depth=1 --recursive --shallow-submodules -v https://github.com/icanos/hassio-plejd/ /data/addons/git/7bc5c08c
  stderr: 'Cloning into '/data/addons/git/7bc5c08c'...
fatal: unable to access 'https://github.com/icanos/hassio-plejd/': Could not resolve host: github.com

**Comment by icanos** [comment]
It looks like you're having some DNS issues from your device, are you able to access other external resources?

**Comment by icanos** [comment]
Oh, sorry. I see that I have an error in my README. The URL should be: https://github.com/icanos/hassio-plejd.git

**Comment by MrTengvall** [comment]
Hi,

Fault was on my side, had pi-hole installed and that blocked github. Removed it from the blocklist and then i could add the repo.
