### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by AlexxHansson** [icanos/hassio-plejd#111]
Hej!

I am not able to install the addon anymore. Had it installed earlier but it lost connection so i thought i would reinstall it. After the uninstall i was not able to install anymore and got this error message:

`The command '/bin/bash -o pipefail -c apk add --no-cache --virtual .build-dependencies g++=8.3.0-r0 gcc=8.3.0-r0 libc-dev=0.7.1-r0 linux-headers=4.19.36-r0 make=4.2.1-r2 python bluez eudev-dev=3.2.8-r0 && apk add --no-cache git nodejs npm dbus-dev glib-dev && npm config set unsafe-perm true' returned a non-zero code: 68`

I have tried with both easy and manual install.

HassOS 4.17 / 0.118.3

**Comment by magnus-kall** [comment]
I have the same exact issue after trying to reinstall:
HassOS 4.17 / version 0118.3

`The command '/bin/bash -o pipefail -c apk add --no-cache --virtual .build-dependencies g++=8.3.0-r0 gcc=8.3.0-r0 libc-dev=0.7.1-r0 linux-headers=4.19.36-r0 make=4.2.1-r2 python bluez eudev-dev=3.2.8-r0 && apk add --no-cache git nodejs npm dbus-dev glib-dev && npm config set unsafe-perm true' returned a non-zero code: 68`

**Comment by icanos** [comment]
Working on a fix, a new version should be released soon.

**Comment by icanos** [comment]
A new fix is released

**Comment by AlexxHansson** [comment]
I can confirm that it works again on manual install! Thanks!

**Comment by icanos** [comment]
Closing as resolved.
