### ISSUE TITLE
Bluetooth disconnect efter 1-3 days

### ISSUE THREAD

**Issue by FlyHigh-Swe** [icanos/hassio-plejd#117]
Hi

I have a setup that works but it keeps loosing connection to the bluetooth hardware (think) after 1-3 days.
If I just restart hassOS the issue reamins but if I turn of the power and restart the RPI4 it works for a while again.
I am running the latest version of plejd (0.4.8), hassio (4.17), HA (0.118.5) on a Raspberri PI 4. 
I had the issue for a while but thought it was related to a usb-connected device at first.

I dont know this is an issue with the plejd add-on or something else in my setup.

I have attached the log (all that is available via the add-on page)

Could this be something related to the plejd add-on or should I start searching elsewhere?
I might add that I had some heat issues with the raspberry and the network kept shutting down but I now have a new case that handles the heat much better.

`
plejd-ble: sending 8 byte(s) of data to Plejd
error: writing to plejd: DBusError: In Progress
plejd-ble: ping failed, reconnecting.
init()
plejd-ble: disconnecting /org/bluez/hci0/dev_C4_1D_FE_A2_7C_A5
error: writing to plejd: TypeError: Cannot read property 'ReadValue' of null
plejd-ble: ping failed, reconnecting.
init()
plejd-ble: error: failed to start discovery. Make sure no other add-on is currently scanning.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
init()
plejd-ble: connecting to /org/bluez/hci0/dev_C4_1D_FE_A2_7C_A5
onDeviceConnected()
trying 10 characteristics
authenticate()
plejd-ble: error: failed to authenticate: DBusError: Not connected
startPing()
startWriteQueue()
plejd-ble: sending 8 byte(s) of data to Plejd
plejd-ble: write failed DBusError: Not connected
init()
plejd-ble: connecting to /org/bluez/hci0/dev_C4_1D_FE_A2_7C_A5
plejd-ble: warning: unable to connect, will retry. DBusError: Software caused connection abort
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
init()
plejd-ble: connecting to /org/bluez/hci0/dev_C4_1D_FE_A2_7C_A5
plejd-ble: warning: unable to connect, will retry. DBusError: Software caused connection abort
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
init()
plejd-ble: connecting to /org/bluez/hci0/dev_C4_1D_FE_A2_7C_A5
onDeviceConnected()
trying 10 characteristics
authenticate()
startPing()
startWriteQueue()
error: writing to plejd: DBusError: In Progress
plejd-ble: ping failed, reconnecting.
init()
error: writing to plejd: TypeError: Cannot read property 'ReadValue' of null
plejd-ble: ping failed, reconnecting.
init()
plejd-ble: disconnecting /org/bluez/hci0/dev_C4_1D_FE_A2_7C_A5
plejd-ble: disconnecting /org/bluez/hci0/dev_C4_1D_FE_A2_7C_A5
(node:302) UnhandledPromiseRejectionWarning: DBusError: Does Not Exist
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:315:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:315:20)
    at emitReadable_ (_stream_readable.js:555:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
(node:302) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 35)
plejd-ble: connecting to /org/bluez/hci0/dev_C4_1D_FE_A2_7C_A5
plejd-ble: warning: unable to connect, will retry. DBusError: Software caused connection abort
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
init()
plejd-ble: connecting to /org/bluez/hci0/dev_C4_1D_FE_A2_7C_A5
onDeviceConnected()
trying 10 characteristics
authenticate()
startPing()
startWriteQueue()
error: plejd ping failed
plejd-ble: ping failed, reconnecting.
init()
error: writing to plejd: DBusError: Not connected
plejd-ble: ping failed, reconnecting.
init()
(node:302) UnhandledPromiseRejectionWarning: DBusError: Does Not Exist
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:315:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:315:20)
    at emitReadable_ (_stream_readable.js:555:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
(node:302) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 36)
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
init()
plejd-ble: connecting to /org/bluez/hci0/dev_C4_1D_FE_A2_7C_A5
plejd-ble: warning: unable to connect, will retry. DBusError: Software caused connection abort
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
init()
plejd-ble: disconnecting /org/bluez/hci0/dev_C4_1D_FE_A2_7C_A5`

**Comment by FlyHigh-Swe** [comment]
I also noticed these errors after a reboot of the host system.
After a whiile it start working (see the last row) but there is something about a potential memory leak.

init()
plejd-ble: connecting to /org/bluez/hci0/dev_C4_1D_FE_A2_7C_A5
plejd-ble: warning: unable to connect, will retry. DBusError: Software caused connection abort
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
init()
plejd-ble: connecting to /org/bluez/hci0/dev_C4_1D_FE_A2_7C_A5
onDeviceConnected()
trying 10 characteristics
authenticate()
startPing()
startWriteQueue()
(node:301) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 {"path":"/org/bluez/hci0/dev_C4_1D_FE_A2_7C_A5/service0009/char0015","interface":"org.freedesktop.DBus.Properties","member":"PropertiesChanged"} listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
plejd-ble: sending 6 byte(s) of data to Plejd

**Comment by icanos** [comment]
Yeah, seems like the event handlers are readded too many times without proper cleanup. Not sure why it disconnects so often. Do you only have one device and also use the Plejd app? BLE is single connection only, so if you were to connect to the device with the Plejd app, it disconnects Home Assistant and vice verse.

**Comment by FlyHigh-Swe** [comment]
I have 2 plejd units within 5 meters from where the RPI as located.. I have noticed the walls in my building is affecting the general network more than it should, maybe this also affect the BLE signals so the reach it reduced. I have one Plejd that is not installed yet, I will try setting it up in the same room as the RPI.

I did notice something about a memory leak but never copied that text.

**Comment by FlyHigh-Swe** [comment]
Problem has been reduced drastically when adding a new Plejd unit closer to the PI. I still see a bit to many errors in the log but they are different and if needed  I will raise a new issue for these.
