### ISSUE TITLE
Unable to connect - ping failed

### ISSUE THREAD

**Issue by QueensGamb** [icanos/hassio-plejd#118]
Hi!

I am new to HA and am trying to install the addon but cant seem to get it to work. Running a Raspberry Pi 4B and have a Plejd Gatway. Seems I get quite far but cant connect with any of the devices. Help please! Here is the log:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Plejd
 Adds support for the Swedish home automation devices from Plejd.
-----------------------------------------------------------
 Add-on version: 0.4.8
 You are running the latest version of this add-on.
parse error: Expected string key before ':' at line 1, column 4
[18:44:57] ERROR: Unknown HTTP error occured
 System:   (armv7 / raspberrypi4)
 Home Assistant Core: 0.118.5
 Home Assistant Supervisor: 2020.12.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[18:44:58] INFO: Starting the Plejd service...
[18:44:58] INFO: Verified permissions on startup script
[18:44:58] INFO: Executing startup script
[18:44:59] INFO: Wrote plejd.json
[18:44:59] INFO: Running add-on
starting Plejd add-on v. 0.4.8
plejd-api: login()
plejd-api: logging into Hemma9
plejd-api: got session token response
plejd-api: getSites()
plejd-api: got site list response
plejd-api: getSite(...)
plejd-api: got site details response
wireEvents()
init()
plejd-ble: disconnecting /org/bluez/hci0/dev_D9_B1_1E_BC_23_72
plejd-ble: connecting to /org/bluez/hci0/dev_D9_B1_1E_BC_23_72
onDeviceConnected()
trying 10 characteristics
authenticate()
startPing()
startWriteQueue()
error: plejd ping failed
plejd-ble: ping failed, reconnecting.
init()
error: writing to plejd: DBusError: Not connected
plejd-ble: ping failed, reconnecting.
init()
(node:302) UnhandledPromiseRejectionWarning: DBusError: Does Not Exist
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:315:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:315:20)
    at emitReadable_ (_stream_readable.js:555:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
(node:302) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:302) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
init()
plejd-ble: connecting to /org/bluez/hci0/dev_D9_B1_1E_BC_23_72
onDeviceConnected()
trying 10 characteristics
authenticate()
startPing()
startWriteQueue()

HasOS 4.17

**Comment by icanos** [comment]
After it gave you that error, it seems to successfully connect. Does it work?

**Comment by SweVictor** [comment]
@QueensGamb: Still an issue with newer versions? Unless we get an update I suggest we close this.

**Comment by icanos** [comment]
Closing, reopen if the issue still exists.
