### ISSUE TITLE
Request failed with status code 403

### ISSUE THREAD

**Issue by pekivan** [icanos/hassio-plejd#119]
Im trying to configure my plejd in home assistant. And I get this error message in the log. Could someone please help me to figure out what is wrong. Firmvare in the Plejd hardware is 2.4.3

[20:14:24] INFO: Starting the Plejd service...
[20:14:24] INFO: Verified permissions on startup script
[20:14:24] INFO: Executing startup script
[20:14:25] INFO: Wrote plejd.json
[20:14:25] INFO: Running add-on
starting Plejd add-on v. 0.4.8
plejd-api: login()
plejd-api: logging into plejd
error: unable to retrieve session token response: Error: Request failed with status code 403
(node:17813) UnhandledPromiseRejectionWarning: unable to retrieve session token response: Error: Request failed with status code 403
(node:17813) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:17813) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

My Plejd config tab looks like this
site: plejd
username: xxxxx.xxxxx@xxxxxx.xx
password: 'xxxx'
mqttBroker: 'mqtt://xxx.xxx.xx.xxx'
mqttUsername: mqtt
mqttPassword: xxxxxxx
includeRoomsAsLights: false
connectionTimeout: 2
writeQueueWaitTime: 400

My configuration.yaml look like this

device_tracker:
  - platform: bluetooth_le_tracker

mqtt:
  broker: 'mqtt://xxx.xxx.xx.xxx'
  username: mqtt
  password: xxxx
  discovery: true
  discovery_prefix: homeassistant
  birth_message: 
    topic: 'hass/status'
    payload: 'online'
  will_message: 
    topic: 'hass/status'
    payload: 'offline'

**Comment by pekivan** [comment]
Im using Raspberry 4 b with Raspberry OS

**Comment by mudape** [comment]
Looks like something is wrong with your authorization

> The HTTP 403 is a HTTP status code meaning access to the requested resource is forbidden. The server understood the request, but will not fulfill it due to client-related issues.

Are you using the same username/password as in the app?

**Comment by pekivan** [comment]
The app has two option. Name or E-mail. There is no username. 

Im using the e-mail and password from the app. I have reset the password but no luck.

**Comment by masfak97** [comment]
Had the same problem and had to reset the password multiple times. 
I use my email address, no username. In the end logged out from the Plejd app, reset the password and logged in through HA keeping the app logged out. 
Once HA has logged in, you can log in to the app again.

**Comment by pekivan** [comment]
Thanks for your help. Did you use mqtt://localhost or mqtt://192.xxx.x.xxx

**Comment by masfak97** [comment]
Not localhost, I use the full IP address

**Comment by pekivan** [comment]
I restarted my Wi-Fi router and now I get this result. Am I typing the site name wrong?

[20:54:04] INFO: Starting the Plejd service...
[20:54:04] INFO: Verified permissions on startup script
[20:54:04] INFO: Executing startup script
[20:54:05] INFO: Wrote plejd.json
[20:54:05] INFO: Running add-on
starting Plejd add-on v. 0.4.8
plejd-api: login()
plejd-api: logging into plejd
plejd-api: got session token response
plejd-api: getSites()
plejd-api: got site list response
plejd-api: error: failed to find a site named plejd

**Comment by masfak97** [comment]
Are you using the exact name from the toplist in the app?

**Comment by pekivan** [comment]
I updated the firmware in all my Plejd hardware. I rechecked the spelling of the site name in the Plejd app and noticed that the name included a blank space in the end :/

Works fine now

**Comment by icanos** [comment]
Glad to hear, I'm closing the issue as solved :-)
