### ISSUE TITLE
startWriteQueue() - Nothing happens

### ISSUE THREAD

**Issue by sockerbagarn** [icanos/hassio-plejd#120]
First of all, I am sorry if I am creating an issue of of nothing. 
But, here is the logs from my fresh install of the plejd addon. 

It seems fine to me? But why doesn't it work? Or am I missing something obvious? 

[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[14:05:47] INFO: Starting the Plejd service...
[14:05:47] INFO: Verified permissions on startup script
[14:05:47] INFO: Executing startup script
[14:05:49] INFO: Wrote plejd.json
[14:05:49] INFO: Running add-on
starting Plejd add-on v. 0.4.8
plejd-api: login()
plejd-api: logging into Blåsutgatan
plejd-api: got session token response
plejd-api: getSites()
plejd-api: got site list response
plejd-api: getSite(...)
plejd-api: got site details response
wireEvents()
init()
plejd-mqtt: connected to mqtt.
plejd-mqtt: discovered light (DIM-01) named Vardagsrum with PID 11.
plejd-ble: connecting to /org/bluez/hci0/dev_DB_CC_B7_39_19_FD
onDeviceConnected()
trying 10 characteristics
authenticate()
startPing()
startWriteQueue()

**Comment by masfak97** [comment]
Same thing for me. NUC 54250 with bluetooth dongle BT400, Debian with supervised Home assistant. Bluetooth seems to work fine in Debian desktop.

**Comment by icanos** [comment]
Sorry, but I can't help you since I'm using RPi 4 without issues. What happens, nothing? Do you see anything in the log when you try to trigger the DIM-01?

**Comment by icanos** [comment]
Are you trying to use HA at the same time as the Plejd app? BLE is single connection only and will disconnect HA if you open the Plejd app, if you only have one Plejd device.

**Comment by sockerbagarn** [comment]
I'm using a raspberry 4 as well.
A few more things has appeared in my log.

Nothing happens when I trigger my dimmer. 

authenticate()
startPing()
startWriteQueue()
error: writing to plejd: DBusError: In Progress
plejd-ble: ping failed, reconnecting.
init()
plejd-ble: disconnecting /org/bluez/hci0/dev_DB_CC_B7_39_19_FD
error: writing to plejd: DBusError: Operation failed with ATT error: 0x0e
plejd-ble: ping failed, reconnecting.
init()
plejd-ble: error: failed to start discovery. Make sure no other add-on is currently scanning.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
init()
plejd-ble: connecting to /org/bluez/hci0/dev_DB_CC_B7_39_19_FD
onDeviceConnected()
trying 10 characteristics
authenticate()
startPing()
startWriteQueue()

**Comment by SweVictor** [comment]
Having the same (or at least similar) issue here. Not optimal environment on my side (Windows x64 => VirtualBox with USB redirection of Deltaco BT-118). Initial HA image attempt failed (no Bluetooth found). Got Bluetooth working with a bare Debian install under VirtualBox. Not sure how to copy log but basically

* plejd-api (working)
* wireEvents()
* init()
* plejd-ble: (disconnect => connect => retry => repeat with differect MAC addresses => ...)
* onDeviceConnected()    <== Does this mean Plejd connection is up?
* Trying 10 characteristics
* authenticate()
* startPing()
* startWriteQueue()
* [nothing more happens, several hours at least]

I'm reasonably knowledgable in programming in general, not so much in Linux unfortunately, but happy to help any way I can if there is anything I can do.

I have 20+ Plejd devices, so it's probably not the "single device is blocked" issue.

**Comment by SweVictor** [comment]
Have had a bit of time during Christmas so tried using on Windows on a separate laptop. Program starts after some trickery (replace BT drivers using Zadig, compile bluez, ..., revert dbus-next to noble BT lib)

Result (using old ble.js, not ble-bluez.js) below

After a bit of cross-referencing ble.js and ble.bluez.js I actually got things working. Also realized that to get some kind of debug output you need to set `let debug = "console";` in the js file(s). So - started backtracking and see if I could get things working in Debian as well (which I could). After that tried to move back to the main Windows server and eventually got things working!


Things that did it for me
* Make sure MQTT is correctly configured! For me, using the HomeAssistant Supervisor (HassIO) Addon mosquitto changing from `broker: "mqtt://localhost"` to `broker: "core-mosquitto"` did the trick (username and password as before)
* Make sure that the MQTT integration works! Config => Integrations => MQTT => Configure => Listen to "#" (everything), then publish to topic `home-assistant/switch/1/power` and make sure you see the message below when listening
* If on Windows + VirtualBox or similar setup
  * Install VirtualBox extensions to get USB 2/3
  * Redirect correct usb
  * Potentially replace BT drivers with WinUSB using Zadig   <==== did part of the trick for me
  * Start VirtualBox HA machine
* Make sure BT is working
  * Go to HA console (login as "root", write `login` to access normal terminal (or SSH or similar)
  * start `bluetoothctl` interactive command
  * write `list` and make sure it finds the Bluetooth device, if not you'r no-go ;-(
  * Look in Plejd addon log and make sure there is no `plejd-ble: error: unable to find a bluetooth adapter that is compatible.` line
* Don't mind that you don't get any log output
* Listen to `#` in the MQTT integration and watch Plejd things come in. 
  * Initial device discovery messages originate from the Plejd API, so if you set up that correctly you should get new devices in HA
  * Plejd log will show sth like `plejd-mqtt: discovered light (DIM-01) named ....`
  * State change messages originate from the Plejd Bluetooth connection, so if you get those you should be able to listen to Plejd state changes as well as being able to set states!
  * Log does NOT show state change messages currently, to me that would be very helpful @icanos (or a config switch to allow showing no logs / state change / debug logs)
  * Initial sync might (will?) take many minutes until all devices have the correct on/off/brightness states. I seem to get ~4-12 state messages per minute until all are though. Pretty instant updates on changes though!
  * It seems you can kick yourself out (by connecting using the app) even when you have multiple devices. Possbly a solution would be to add a "dummy" Plejd device close to the BT dongle?!
 

Hope this helps someone, not super-easy to set up first time but well worth it! :)

/Victor

**Comment by SweVictor** [comment]
To clarify the above with regards to the issue: When everything is working as it should, the log is still stuck at `startWriteQueue()`, but you _can_ follow changes by listening to `#` in the MQTT addon.

/Victor

**Comment by svennis94** [comment]
I ran into this issue as well, thinking it did not work. Turned out I needed to configure the just installed mqtt integration. By following the steps of @SweVictor.

> Make sure that the MQTT integration works! Config => Integrations => MQTT => Configure => Listen to "#" (everything)

I noticed that I could not select the option listen to # as I needed to configure the MQTT plugin after installing. So make sure you have configured the MQTT plugin as well in the integration section and have auto discovery on in the configuration of the MQTT integration. For me it is now working, but I am using a rpi4b.

**Comment by sockerbagarn** [comment]
Hi guys,

Thanks for your help.

For me it started working as soon as I changed it to: core-mosquitto in the Plejd addon instead of 192.168.0.XX. 

I also removed to manual configuration in configuration.yaml and only use the integration. 

This worked like a charm on my raspberry pi 4.

Happy new year to all of you.

**Comment by icanos** [comment]
Glad it started working for you and thank you @SweVictor for your work!
