### ISSUE TITLE
Add to "Tested on" section

### ISSUE THREAD

**Issue by kodarn** [icanos/hassio-plejd#122]
I can confirm that I have successfully deployed hassio-plejd on the following system:

### Hardware: 
- Home Assistant Blue
- Board | odroid-n2+

### Software: 
- Home Assistant 2020.12.1
- Installation Type | Home Assistant OS
- Operating System Version | 5.9.15
- Host Operating System | Home Assistant OS 5.9
- Plejd add-on v. 0.4.8

### Bluetooth adapter:
- ASUS USB-BT400
- Chipset: Broadcom BCM20702A1-0b05-17cb

## Hardware:
<img width="532" alt="Home Assistant Blue" src="https://user-images.githubusercontent.com/24460172/103002192-c4f2f100-452e-11eb-83b7-df0837daae1c.png">

## Software:
<img width="754" alt="Home Assistant OS version" src="https://user-images.githubusercontent.com/24460172/103002228-ce7c5900-452e-11eb-8abc-bc1e8bd152c0.png">

## Bluetooth dongle
<img width="974" alt="Bluetooth Dongle" src="https://user-images.githubusercontent.com/24460172/103002241-d50ad080-452e-11eb-92c0-f02a9fdcdda1.png">

## Bluetooth dongle firmware file
(Downloaded from the [WinterHeart](https://github.com/winterheart/broadcom-bt-firmware/tree/master/brcm) firmware collection)
<img width="482" alt="dmesg_showing_success" src="https://user-images.githubusercontent.com/24460172/103010825-35067480-4539-11eb-8f07-f34320c4c1f3.png"><img width="504" alt="Bluetooth Dongle Firmware File" src="https://user-images.githubusercontent.com/24460172/103002253-dc31de80-452e-11eb-9c7f-726d7ab7d8f4.png">

## hassio-plejd log on success
<img width="754" alt="hassio-plejd log on success" src="https://user-images.githubusercontent.com/24460172/103003130-7f372800-4530-11eb-9a0f-b150a25a1dfb.png">

**Comment by tempmaseg** [comment]
> ## Bluetooth dongle firmware file
> (Downloaded from the [WinterHeart](https://github.com/winterheart/broadcom-bt-firmware/tree/master/brcm) firmware collection)
> <img alt="dmesg_showing_success" width="482" src="https://user-images.githubusercontent.com/24460172/103010825-35067480-4539-11eb-8f07-f34320c4c1f3.png"><img alt="Bluetooth Dongle Firmware File" width="504" src="https://user-images.githubusercontent.com/24460172/103002253-dc31de80-452e-11eb-9c7f-726d7ab7d8f4.png">

Hi,

I have just ordered the same bluetooth dongle, and I am wondering if you could write the commands on how to install the firmware on HA blue.

Thanks in advance!

**Comment by kodarn** [comment]
Having worked with the setup for a few days now, I've come to realize that the firmware file isn't really needed. I have removed the file, and it continues to operate after complete reboots of the machine. As long as you have updated the regular software updated (Home Assistant OS via the Supervisor Dashboard etc) you should be all set.

**Comment by tempmaseg** [comment]
It was just plug & play, no installation was requiered. All I needed to do was to reboot and wait a few minutes for HA to find the bluetooth device.

**Comment by SweVictor** [comment]
Also working: Deltaco BT-118 with Cambridge Silicon Radio chipset. Windows + Zadig to change driver to WinUSB (not 100% sure that is needed) => VirtualBox => Home Assistant VBox image

![image](https://user-images.githubusercontent.com/449347/103403598-0009ab80-4b51-11eb-9951-fdf9ef7bb096.png)

**Comment by icanos** [comment]
Please create a PR with the updated hardware and I'll approve it :-) thanks!!

**Comment by faanskit** [comment]
**ASUS BT400**
Windows 10 Host, Oracle Virtualbox 6.1
Home Assistant VBox image
![virtualbox](https://user-images.githubusercontent.com/10439868/117542577-7d6e8c80-b019-11eb-86db-7834533f0631.JPG)

Had issues with the built-in Bluetooth on my motherboard. Qualcomm, Atheros AR9462.
Could not get it to work with Virtualbox/Hassio, or a Debian 7.
Inacivated and added Asus BT400. Works out of the box.

**Comment by SweVictor** [comment]
Adding the above known working configurations to v0.8.0 readme and closing this. Please open PR:s with updated readme for more known version after v0.8 release.
