### ISSUE TITLE
plejd-ble reconnect attempts

### ISSUE THREAD

**Issue by kodarn** [icanos/hassio-plejd#123]
## Issue description:
When booting "Home Assistant OS" on my brand new "Home Assistant Blue" using a USB-Bluetooth dongle, there seems to be some sort of delayed initialization of the USB-Bluetooth dongle...

#1 Power on the "Home Assistant Blue"
#2 Check the hassio-plejd log

```plejd-api: got session token response
plejd-api: getSites()
plejd-api: got site list response
plejd-api: getSite(...)
plejd-api: got site details response
wireEvents()
init()
plejd-ble: error: unable to find a bluetooth adapter that is compatible.
plejd-mqtt: connected to mqtt.
plejd-mqtt: discovered light (CTR-01) named Carport with PID 11.
plejd-mqtt: discovered light (CTR-01) named InnerTak with PID 12.
plejd-mqtt: discovered light (CTR-01) named MotGata with PID 14.
plejd-mqtt: discovered switch (Scene) named GarageOn with PID 2.
plejd-mqtt: discovered switch (Scene) named GarageOff with PID 3.
```

#3 Now hassio-plejd just sits here and waits... (Note the line "plejd-ble: error: unable to find a bluetooth adapter that is compatible.")

#4 Going to the Info-tab in the hassio-plejd addon gui, and simply clicking the restart button, restarts hassio-plejd with complete success this time. Looking at the log we see:
```plejd-api: got session token response
plejd-api: getSites()
plejd-api: got site list response
plejd-api: getSite(...)
plejd-api: got site details response
wireEvents()
init()
plejd-mqtt: connected to mqtt.
plejd-mqtt: discovered light (CTR-01) named Carport with PID 11.
plejd-mqtt: discovered light (CTR-01) named InnerTak with PID 12.
plejd-mqtt: discovered light (CTR-01) named MotGata with PID 14.
plejd-mqtt: discovered switch (Scene) named GarageOn with PID 2.
plejd-mqtt: discovered switch (Scene) named GarageOff with PID 3.
plejd-ble: connecting to /org/bluez/hci0/dev_EE_0B_45_05_B9_62
onDeviceConnected()
trying 10 characteristics
authenticate()
startPing()
startWriteQueue()
```

(Note the line "plejd-ble: connecting to /org/bluez/hci0/dev_EE_0B_45_05_B9_62")

## Solution suggestions:
A solution would enable the Plejd network to automatically come back up online after a powerloss or manual reboot of the machine. Suggestions:

- Put the "plejd-ble: connecting to"-code in some sort of loop (preferable)
or
- Simply halt the whole addon making the Supervisor-WatchDog restart the add-on as if it had crashed

**Comment by kodarn** [comment]
Perhaps a duplicate issue of #98

**Comment by icanos** [comment]
Perhaps add somekind of setting where you could delay the start of the addon for X seconds. Would that be suitable?

**Comment by kodarn** [comment]
Yes, an optional configuration parameter would be great!

startDelay: <NumberOfSeconds>

If not set: default to zero
If set: Simply sleep the specified number of seconds

**Comment by grubbe123** [comment]
Would be nice. I always have to restart the addon when Home Assistant has started. Great addon, thanks alot! :)

**Comment by SweVictor** [comment]
#158 will address this

**Comment by SweVictor** [comment]
Merged to [develop branch](https://github.com/icanos/hassio-plejd/tree/develop), planned for 0.6.0 release. Closing
