### ISSUE TITLE
light.turn_off turns the lights on

### ISSUE THREAD

**Issue by jzee** [icanos/hassio-plejd#124]
## To reproduce
- turn on a light with max brightness -> light turns on [OK]
- turn off the same light -> light turns off [OK]
- attempt to turn off the same light with a transition parameter of 10s (transition: 10) -> light turns **on** and subsequently fades out over a period of 10s [NOK]

The expected behavior would be that the light (which was already off) is unaffected by a light.turn_off command. 

## Use case
This negatively affects automations where a trigger snapshots a current light setting and then collectively turns off several lights. In essence, this cannot be performed. Instead, one needs to separately check each light and issue and fade them out individually. 

## System configuration

version | 2020.12.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.6
os_name | Linux
os_version | 5.4.79-v7l
arch | armv7l
timezone | Europe/Stockholm

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Home Assistant OS 5.9
-- | --
update_channel | stable
supervisor_version | 2020.12.7
docker_version | 19.03.13
disk_total | 28.0 GB
disk_used | 7.2 GB
healthy | true
supported | true
board | rpi4
supervisor_api | ok
version_api | ok
installed_addons | TellStick (2.0), File editor (5.2.0), Node-RED (7.2.11), Terminal & SSH (8.10.0), deCONZ (6.6.1), Plejd (0.4.8), Mosquitto broker (5.1), SONOS AudioClip TTS (2.0.4)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
mode | storage
views | 7
resources | 0

</details>

**Comment by f00dagi** [comment]
Last time I checked I found even more severe problems with transitions: https://github.com/icanos/hassio-plejd/issues/68

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
