### ISSUE TITLE
Request: Clarify versions/readme

### ISSUE THREAD

**Issue by SweVictor** [icanos/hassio-plejd#126]
Versions and README are currently (at least to me) a bit confusing. A changelog or at least a clear version indication would be highly appreciated.

I, using "Easy installation", have the latest (as of 2020-12-31) version installed. Tried `includeRoomsAsLights: true` config setting, but nothing seems to happen (no MQTT messages with "room" type posted). Started reporting that as an issue, but realized I'm not sure what is running and what is the latest version.
* HA says `Plejd - Current version: 0.4.8` (is this maybe taken from plejd/config.json?)
* Readme changelog section shows 0.4.5 as latest
* (Releases show v0.1.4 as latest, presumably releases aren't used anymore)
* plejd/Readme seems to be an old version of Readme, maybe remove? Unfortunately plejd/readme is the one picked up by HA
* `includeRoomAsLights` is said to require v.5. Is that possibly newer than 0.4.8?

After the above investigation, maybe the version in plejd/config.json is enough, but if that is the "real" version it would be great if that would be mentioned in the main readme, and also if there is only one readme in the project to avoid confusion.

Edit: A good way to format a changelog could be this. I could potentially try to help structure this if that would be of interest @icanos  https://keepachangelog.com/en/1.0.0/

Thanks for your great work regarding the addon btw, really really welcome!

**Comment by icanos** [comment]
I think that the changelog has outgrown being part of the README :-) my suggestion is to either remove it from the README and move it to a separate file or something like that or just keep a few of the latest versions in the README and the rest in a CHANGELOG file.

**Comment by SweVictor** [comment]
So, @icanos, I'm looking into this. After some looking around it seems many addons have all files in the root (not as it is done here in a /plejd subfolder). There also seems to be a suggestion to have a README for the repo, a DOCS file for the hassio addon and a CHANGELOG for specifically that.

What I can't figure out based on the code structure is - how does hassio find the /plejd directory?! I can't see it linked in any of the root folders. Does it just parse the entire tree looking for a config.json?

I'm thinking maybe a slight restructure could be in order (once figuring out the above), something like
* Root folder contains a few more files from the /plejd directory (package.json, config.json, DOCKERFILE, build.json, readme, etc)
* rootfs is moved to the root
* test is moved to the root
* /plejd is renamed to something a bit clearer (nodejs, js, node_server, ...)

As an alternative we could keep it a bit more simple
* Rename plejd/README to /plejd/DOCS for clarity and remove dev-related things
* Remove most info from /README and link to /plejd/DOCS
* Create CHANGELOG (which I suppose currently needs to be in the /plejd directory)

What do you think?

(as a side note https://developers.home-assistant.io/docs/en/hassio_addon_config.html in the readme does not exist anymore - remove? or has it been moved?)

**Comment by icanos** [comment]
Regarding how it finds the /plejd directory is that the current GitHub repository is actually an addon repository in HassIO so each folder within the repo shows up as a separate addon in the Store within the Supervisor UI. That's why we have the folder structure as is.

The README in the root of the repo is the readme that is displayed in GitHub, the README in /plejd is the one that's being shown within the Supervisor UI. Not the best setup I know, and maybe time to look into publishing the addon through "official" HassIO channels?

**Comment by SweVictor** [comment]
Ah, that makes sense of course, thanks for that. It's probably mostly the `repostiory.json` that confuses a bit since it says the entire repo is the addon, but in reality only the plejd folder is the addon...

Given that, maybe we should just skip README/CHANGELOG in the root and just create a very thin README instead "This is a HA addon repository with currently only one addon inside, [link to inner readme]"

That actually opens the slightly interesting possibility to keep old stable versions in separate folders... Not sure if it's a good idea (would duplicate a lot of code, having HA work with tags would be MUCH easier of course), but it could work at least. So folders "plejd", "plejd-v0.3.4", ...  (which would then make it possible for the end user to choose an older stable-deemed version. I wonder though what happens when we remove old folders....)

**Comment by icanos** [comment]
Yes, that would be a better way of solving it maybe. Regarding versioning, maybe that's an idea to explore, but I think we should keep it to either 0.1.0, 0.2.0 and so on, or the last version in each "minor", so for example, 0.1.9, 0.2.9 and so on... Otherwise we'll have tons of addons displayed in the Supervisor UI. One other variant would be to just keep the latest as "plejd" and "previous" as the last known working version.

Or simply just provide information of how to download a tagged version and manually upload and install it locally.

**Comment by SweVictor** [comment]
Yeah, agreed. Keeping multiple directories is not super-appealing, and would create more maintenance. Info about tagged releases is probably good.

If you don't mind I can change the main readme to only point to the inner one and remove the root changelog?
