### ISSUE TITLE
Idea: Add device id and shouldRetry to writeQueue

### ISSUE THREAD

**Issue by SweVictor** [icanos/hassio-plejd#128]
After looking a bit at what happens when sending lots of commands to lots of devices (when transitioning for example) I have an idea to
* Add `deviceId` and `shouldRetry` to writeQueue
* Potientially add `isImportant` attribute (or use `shouldRetry` for that)
* Add `TTL` to messages (default to 5-10 seconds or maybe up to a minute)

This would let the writeQueue loop
* Skip sending all but the most recent update to each device (happens when transitioning and probably also when dragging the dim slider in the UI)
* Flag transition updates as "non-important" to let queue skip those when lots of writeQueue is long
* Skip updating when when message is old (TTL has expired) to avoid strange updates after a longer downtime

What do you think?

**Comment by icanos** [comment]
I've been thinking about something similar, so I think that would be a good addition to the plugin.
