### ISSUE TITLE
Can't turn on/off lights anymore

### ISSUE THREAD

**Issue by dennisgranasen** [icanos/hassio-plejd#129]
Hi,
Since about a year ago I can't interact with my plejd devices through Home assistant. 
This is what the log says when firing up the plejd integation:

init()
plejd-mqtt: connected to mqtt.
plejd-mqtt: discovered light (DIM-02) named Taklampa with PID 11.
plejd-mqtt: discovered light (DIM-02) named Spotlights with PID 12.
plejd-mqtt: discovered light (DIM-01) named Badrumsspottar with PID 14.
plejd-ble: error: failed to start discovery. Make sure no other add-on is currently scanning.

Then nothing more. When I click the switches for the lights in Home assistant, they do seemingly change state for a second or two, then switch back off. The lights do not react.

I should add that I'm runing on a RPi4 with raspbian. Everything was working, but it is not more than a year ago...  I do not know what is different in my system today compared to when it was working. But perhaps you have a clue as to what could be wrong?

**Comment by icanos** [comment]
Did you install any other addon to your Hass.io that uses BLE? For example NodeRED? Only one addon can use the dbus at a time.

**Comment by SweVictor** [comment]
Please install the latest version and increase logLevel to verbose to get A LOT more info on what is going on!

**Comment by SweVictor** [comment]
Should be fixed in [develop branch](https://github.com/icanos/hassio-plejd/tree/develop), planned for 0.6.0 release. Closing
