### ISSUE TITLE
Back end improvement build for 64bit system

### ISSUE THREAD

**Issue by buffedelic** [icanos/hassio-plejd#131]
Hi,

First off thank you for a great plugin!! Recently installed the aarch64 version of homeassistant and realized that hassio-plejd will not run on it... out of the box/restore-box anyways :)

I ran the rebuild option and it worked fine so no worries...
An improvement would be to automatically run the rebuild option if error below is thrown. Seems to me that other plugins eighter rebuild after migration to 64 bit system, or has a built version ready during initial install. 

```
Failed to start addon
404 Client Error for http+docker://localhost/v1.40/containers/create?name=addon_4cb18a39_plejd: Not Found ("No such image: 4cb18a39/aarch64-addon-plejd:0.4.8")
```

**Comment by icanos** [comment]
Not sure that is possible from our side, to trigger a rebuild would be a Hass.io thing (outside of the scope for the addon).

**Comment by buffedelic** [comment]
Maybe the other add-ons I had running when I migrated where shipped with precompiled versions for aarch64, not very space efficient. 
ie. Grafana, Mosquitto broker, node-RED.

Anyway if it is possible it shure is a plesant experience for the user! :) Rebuild button is ok.

**Comment by SweVictor** [comment]
Since the addon is compiled locally, I'm thinking the restore restores your old x86-compiled version. I'm guessing that installing clean on aarch64 works fine? 

If so I suggest we close this.
