### ISSUE TITLE
Runn as Stand Alone

### ISSUE THREAD

**Issue by JohnPhoto** [icanos/hassio-plejd#132]
Is it possible to run this as a stand alone on an RPi and just communicate through MQTT to actually HA?

my setup involves running HA on a (freebsd) server (no USB etc) and in my system I have a few RPI which is responsible for interacting with BLE/Zigbee so this is where I Will need to run this preferably.

It looks like I only have to run main.js with node? But is there any docs or recomendations what I need to set up?

**Comment by icanos** [comment]
You would need to create a plejd.json file, the format of which you can find in the build scripts of the Docker container, the file would need to be placed along side the main.js file. Then just run 'node main.js' and it _should_ work :-).

**Comment by JohnPhoto** [comment]
I actually saw your response after I actually got it working in the exact same way as your described. Got som scary warnings on `npm install` for missing native files but it worked any way.

I am actually running on an RPi Zero W so stuff (i.e nodejs) has a bit of an alternative install procedure, still running like a train!

Awesome work!
