### ISSUE TITLE
Cannot read property 'length' of undefined - when turning of the light

### ISSUE THREAD

**Issue by tempmaseg** [icanos/hassio-plejd#134]
Hi,

After turning off the light i am getting an error message _plejd-ble: write failed TypeError: Cannot read property 'length' of undefined_ and then i get disconnect from the plejd device and it tries to reconnect. 

I can turn on the light and change dim on it but as soon as i turn it off it loses the connection to the add-on. Further, I can turn of the device from the switch and it works fine.

onDeviceConnected()
trying 10 characteristics
authenticate()
startPing()
startWriteQueue()
Plejd got turn on command for  11 , brightness  undefined , transition  undefined
Plejd got turn off command for  11 , transition  undefined
plejd-ble: write failed TypeError: Cannot read property 'length' of undefined
init()
plejd-ble: disconnecting /org/bluez/hci0/dev_C5_70_95_DB_43_77
plejd-ble: connecting to /org/bluez/hci0/dev_C5_70_95_DB_43_77
plejd-ble: warning: unable to connect, will retry. DBusError: Disconnected early

Thanks in advance!

**Comment by JohnPhoto** [comment]
See https://github.com/icanos/hassio-plejd/pull/137 for suggested fixes to this bug.

**Comment by JohnPhoto** [comment]
Further investigations seems to indicate that this for me is actually happening in my scenes where I have set `min` to a light. If I update the scene in Plejdapp, and restart both this addon and HA to properly sync all settings I no longer get the error.

So except the errorhandling-stuff I have done above (which does not fix the fact that some lamps is not updated), I also change my scenes to be put to explicitly `1%` instead of `min`.

**Comment by tempmaseg** [comment]
> Further investigations seems to indicate that this for me is actually happening in my scenes where I have set `min` to a light. If I update the scene in Plejdapp, and restart both this addon and HA to properly sync all settings I no longer get the error.
> 
> So except the errorhandling-stuff I have done above (which does not fix the fact that some lamps is not updated), I also change my scenes to be put to explicitly `1%` instead of `min`.
> 
> Edit: I also believe that the error happens on `off`, but in my case that actually gets through to system somehow and actually turns my lamps off, even though I see the error.

I have grouped my Plejd plug with a zigbee plug into a group in HA, so when toggling to on it works fine even though the undefined objects. However, as you are saying it is possible to toggle off but then it gets disconected.

**Comment by LBcuPqpJo7** [comment]
I am also experiencing this since i rebuilt yesterday (13/1) and added two DIM-02 and WPH-01 yesterday. The lights are mainly controlled by motion sensors through HA. I don't use transitions in my automations or scenes in Plejd. 

Logs:
```
Plejd got turn off command for  11 , transition  undefined
Plejd got turn off command for  21 , transition  undefined
plejd-ble: failed inspecting /org/bluez/hci0/dev_##_##_##_##_##_## error: Error: interface not found in proxy object: org.bluez.Device1
plejd-ble: connecting to /org/bluez/hci0/dev_##_##_##_##_##_##
Plejd got turn off command for  34 , transition  undefined
Plejd got turn off command for  33 , transition  undefined
Plejd got turn off command for  54 , transition  undefined
onDeviceConnected()
trying 10 characteristics
authenticate()
startPing()
startWriteQueue()
plejd-ble: write failed TypeError: Cannot read property 'length' of undefined
plejd-ble: write failed TypeError: Cannot read property 'length' of undefined
plejd-ble: write failed TypeError: Cannot read property 'length' of undefined
plejd-ble: write failed TypeError: Cannot read property 'length' of undefined
plejd-ble: write failed TypeError: Cannot read property 'length' of undefined
Plejd got turn off command for  54 , transition  undefined
plejd-ble: write failed TypeError: Cannot read property 'length' of undefined
init()
plejd-ble: disconnecting /org/bluez/hci0/dev_##_##_##_##_##_##
init()
plejd-ble: disconnecting /org/bluez/hci0/dev_##_##_##_##_##_##
init()
plejd-ble: disconnecting /org/bluez/hci0/dev_##_##_##_##_##_##
init()
plejd-ble: disconnecting /org/bluez/hci0/dev_##_##_##_##_##_##
init()
plejd-ble: disconnecting /org/bluez/hci0/dev_##_##_##_##_##_##
init()
plejd-ble: disconnecting /org/bluez/hci0/dev_##_##_##_##_##_##
(node:301) UnhandledPromiseRejectionWarning: DBusError: Does Not Exist
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
(node:301) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 54)
(node:301) UnhandledPromiseRejectionWarning: DBusError: Does Not Exist
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
(node:301) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 55)
(node:301) UnhandledPromiseRejectionWarning: DBusError: Does Not Exist
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
(node:301) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 56)
(node:301) UnhandledPromiseRejectionWarning: DBusError: Does Not Exist
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
(node:301) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 57)
(node:301) UnhandledPromiseRejectionWarning: DBusError: Does Not Exist
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
(node:301) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 58)
plejd-ble: failed inspecting /org/bluez/hci0/dev_##_##_##_##_##_## error: Error: interface not found in proxy object: org.bluez.Device1
plejd-ble: connecting to /org/bluez/hci0/dev_##_##_##_##_##_##
onDeviceConnected()
trying 10 characteristics
authenticate()
startPing()
startWriteQueue()
Plejd got turn on command for  20 , brightness  177 , transition  undefined
Plejd got turn on command for  20 , brightness  177 , transition  undefined
Plejd got turn on command for  11 , brightness  104 , transition  undefined
Plejd got turn on command for  20 , brightness  177 , transition  0
Plejd got turn on command for  11 , brightness  105 , transition  0
Plejd got turn on command for  21 , brightness  195 , transition  undefined
Plejd got turn on command for  21 , brightness  196 , transition  0
Plejd got turn off command for  20 , transition  undefined
plejd-ble: write failed TypeError: Cannot read property 'length' of undefined
init()
plejd-ble: disconnecting /org/bluez/hci0/dev_##_##_##_##_##_##
plejd-ble: failed inspecting /org/bluez/hci0/dev_##_##_##_##_##_## error: Error: interface not found in proxy object: org.bluez.Device1
plejd-ble: connecting to /org/bluez/hci0/dev_##_##_##_##_##_##
onDeviceConnected()
trying 10 characteristics
authenticate()
startPing()
startWriteQueue()
```

**Comment by icanos** [comment]
This should be resolved in the merge done last night, could you rebuild and try again?

**Comment by LBcuPqpJo7** [comment]
Rebuilt and so far so good. Will continue to monitor during the day.

Thanks!

**Comment by tempmaseg** [comment]
Hi,

Thanks for the fix! it works for me to toggle the light on and off now. :)

However, i am facing the same issue as ankisch

onDeviceConnected()
trying 10 characteristics
authenticate()
startPing()
startWriteQueue()
error: writing to plejd: DBusError: In Progress
plejd-ble: ping failed, reconnecting.
init()
plejd-ble: disconnecting /org/bluez/hci0/dev_C5_70_95_DB_43_77
error: writing to plejd: TypeError: Cannot read property 'ReadValue' of null
plejd-ble: ping failed, reconnecting.
init()
plejd-ble: disconnecting /org/bluez/hci0/dev_C5_70_95_DB_43_77
(node:303) UnhandledPromiseRejectionWarning: DBusError: Does Not Exist
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
(node:303) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
onDeviceConnected()
trying 10 characteristics
authenticate()
startPing()
startWriteQueue()

**Comment by ankisch** [comment]
> However, i am facing the same issue as ankisch

I have not experienced any more issues of this kind after the rebuild I did this morning.

**Comment by JohnPhoto** [comment]
> Hi,
> 
> Thanks for the fix! it works for me to toggle the light on and off now. :)
> 
> However, i am facing the same issue as ankisch
> 
> onDeviceConnected()
> trying 10 characteristics
> authenticate()
> startPing()
> startWriteQueue()
> error: writing to plejd: DBusError: In Progress
> plejd-ble: ping failed, reconnecting.
> init()
> plejd-ble: disconnecting /org/bluez/hci0/dev_C5_70_95_DB_43_77
> error: writing to plejd: TypeError: Cannot read property 'ReadValue' of null
> plejd-ble: ping failed, reconnecting.
> init()
> plejd-ble: disconnecting /org/bluez/hci0/dev_C5_70_95_DB_43_77
> (node:303) UnhandledPromiseRejectionWarning: DBusError: Does Not Exist
> at _methodReturnHandlers. (/plejd/node_modules/dbus-next/lib/bus.js:339:27) at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11) at EventEmitter. (/plejd/node_modules/dbus-next/lib/bus.js:147:9) at EventEmitter.emit (events.js:314:20) at /plejd/node_modules/dbus-next/lib/connection.js:112:14 at Socket. (/plejd/node_modules/dbus-next/lib/message.js:63:9) at Socket.emit (events.js:314:20) at emitReadable_ (_stream_readable.js:557:12)
> at processTicksAndRejections (internal/process/task_queues.js:83:21)
> (node:303) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
> onDeviceConnected()
> trying 10 characteristics
> authenticate()
> startPing()
> startWriteQueue()

This is actually not the same as @ankisch, but my real concern is that this should be caught by a special-case in the error-catcher.

**Comment by tempmaseg** [comment]
I am also facing below error message, randomly. Is it something wrong on my end? 

onDeviceConnected()
trying 10 characteristics
authenticate()
startPing()
startWriteQueue()
Plejd got turn off command for  11 , transition  undefined
Plejd got turn on command for  11 , brightness  undefined , transition  undefined
error: writing to plejd: DBusError: In Progress
plejd-ble: ping failed, reconnecting.
init()
error: writing to plejd: TypeError: Cannot read property 'ReadValue' of null
plejd-ble: ping failed, reconnecting.
init()
plejd-ble: disconnecting /org/bluez/hci0/dev_C5_70_95_DB_43_77
plejd-ble: disconnecting /org/bluez/hci0/dev_C5_70_95_DB_43_77
(node:300) UnhandledPromiseRejectionWarning: DBusError: Does Not Exist
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
(node:300) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
plejd-ble: connecting to /org/bluez/hci0/dev_C5_70_95_DB_43_77
onDeviceConnected()
trying 10 characteristics
authenticate()
startPing()
startWriteQueue()
