### ISSUE TITLE
Errors in BLE cause addon to reinitialize

### ISSUE THREAD

**Issue by SweVictor** [icanos/hassio-plejd#143]
Have tested a bit after #137 got merged. Errors addressed in the PR are gone, unfortunately they seem to be swallowed rather than actually dealt with.

An example is exceptions in the BLE code (turnOn command for example) which will actually cause `Starting the Plejd service...` from   `run.sh` to be shown, which means the entire plugin is restarting. This is despite me not checking the watchdog button meaning that the service itself has some autorecovery built in (probably intentional).

There are a few things which is a bit problematic with this, a few examples are
* Plejd devices will become unresponsive for quite some time until restart and re-init is complete
* Plejd public API will be hit many more times than necessary
* Device states in `blue.bluez.js` will be lost meaning that for example transitions won't work as expected.

Another (slightly worse) example is that exceptions thrown during first init will _not_ recover (Plejd device non-responsive typically) and addon will hang and never start up.

I'm looking into a good way of solving this, but would appreciate some input of what you think the expected behavior is code-wise. I see two main options
1. `ble.bluez.js` is very resilient in itself
2. `main.js` is rebuilt towards some kind of worker loop concept that catches all unhandled exceptions and re-inits BLE gracefully without losing all state.

I'm leaning towards the second approach, but am also thinking that a `ble.js` should be (re)added that handles the "business logic" side of BLE communication, while `ble.bluez.js` continues to have the blues-specific actual operations. 

Any thoughts? I know that @thomasloven has probably given the overall structure some thought recently since breaking out into a standalone repo, so maybe you have some thoughts? Anyone else?

/Victor

**Comment by icanos** [comment]
I agree with you, the current setup isn't as stable as it should be.

I too think that we should break out the business logic from the actual communication layer, resulting in a `ble.js` or `plejd.js` containing the logic, unaware of what communication protocol is behind. Then we have the communication layer of `ble.bluez.js` which just handles the connect, read and write. That should simplify error handling in the comm layer too.

Then the `plejd.js` would handle all the magic done to turning lights on/off, transitions and/or scenes and just call the communication channel once a message should be written.

**Comment by SweVictor** [comment]
Sounds good. I have added some logging on timeouts in the `setTimeout`-initialized promises. So far it is actually quite stable in general, I'm just not a fan of errors propagating so "far up" the component tree _when_ something happens. But either way, in practice, it works quite well!

**Comment by SweVictor** [comment]
I have thought about two more things around a potential refactor of the code. How do you (all) feel about 

### TypeScript
I am personally very much in favor of TS codebases (but have limited experience with NodeJS). I think TS could help with code quality with regards to for example readability and clearly specified and typed interfaces and function calls, avoiding bugs by for example setting some arguments as required and others as optional. Main downside as I see it is that a compile step is needed before the code can be run. There might also be a bit of a learning curve for some. TS is though quite popular nowadays and untyped JS code can be written if the code style permits it.

### Linting
Related to the code quality/style argument above, I prefer having a set code style so that code "looks the same" independent of who wrote it. A good toolset would be `eslint` for JS/TS with `editorconfig` as a complement. Such tooling would ensure consistent quotes, line lengths, braces positions, unused variables and much more. As a dev you would typically integrate eslint/editorconfig as addons in your preferred editor, quickly getting feedback and autofixes as you write.

Any thoughts?

**Comment by SweVictor** [comment]
Most of these issues addressed. Linting has been added, no love for TypeScript as of yet, so closing this for now 😄
