### ISSUE TITLE
Remove or fix mqtt settings code

### ISSUE THREAD

**Issue by SweVictor** [icanos/hassio-plejd#147]
As discussed in other issue, the code to reload parts of the addon on settings update does not work.

The entry-point seems to be code in `mqtt.js` that listens to the `plejd/settings` topic`. Unfortunately, no mqtt messages are emitted on settings changes currently. 

I suggest we remove the code related to settings updates, or fix it. I have looked but cannot find examples of addons that react to settings changes without reloading. I'm guessing it could be done by some kind of file/folder watcher reacting to updates in the `/data/options.json` file, but I personally lean towards it not being worth the effort to make this work.

What do you think? Is it a problem to have to reload the plugin to have settings changes stick? If so, why?

**Comment by icanos** [comment]
I don't see any problem with manually reloading the addon when settings changes. Don't think that they will change that often :-)

**Comment by SweVictor** [comment]
Code removed. Fixed in #150
