### ISSUE TITLE
Question: Offline mode

### ISSUE THREAD

**Issue by kodarn** [icanos/hassio-plejd#148]
Hi!

I have a question regarding this excellent Home Assistant Addon. :grinning:

I have been planing to firewall-block my Home Assistant from reaching Internet as a measure to increase security. I don't use any cloud services :cloud: in my home automation, so there is no apparent need for the server to have internet access besides downloading updates which I can manually allow when I feel the need to update. 

However, how will `hassio-plejd` deal with this scenario? When I take a look at the `hassio-plejd` log, it looks like the addon communicates with the Plejd-Cloud on **every** start/boot:

```
[08:13:12] INFO: Starting the Plejd service...
[08:13:12] INFO: Verified permissions on startup script
[08:13:12] INFO: Executing startup script
[08:13:13] INFO: Wrote plejd.json
[08:13:13] INFO: Running add-on
starting Plejd add-on v. 0.4.8
plejd-api: login(                                                  <----------------- Cloud Access?
plejd-api: logging into MyHome
plejd-api: got session token response
plejd-api: getSites()
plejd-api: got site list response                        <----------------- Cloud Data Download?
plejd-api: getSite(...)
plejd-api: got site details response
wireEvents()
init()
plejd-mqtt: connected to mqtt.
plejd-mqtt: discovered light (CTR-01) named Carport with PID 11.
plejd-mqtt: discovered light (CTR-01) named InnerTak with PID 12.
plejd-mqtt: discovered light (CTR-01) named MotGata with PID 14.
plejd-mqtt: discovered light (CTR-01) named Relay with PID 15.
plejd-mqtt: discovered switch (Scene) named GarageOn with PID 2.
plejd-mqtt: discovered switch (Scene) named GarageOff with PID 3.
plejd-ble: connecting to /org/bluez/hci0/dev_CC_77_86_28_06_07
...
```
in order to download `Sitelist` and perhaps other things.

### Question: 
Would it be possible to store the information in the hassio-plejd configuration file which is needed for the addon to start correctly? Now, I understand that the configuration file have to be updated if I modify my Plejd-network in anyway, but still it would be very desirable to eliminate accesses to 3rd party cloud services if possible. :pray:

**Comment by SweVictor** [comment]
You're absolutely right. The addon downloads lots of info (site info, all devices, BLE crypto key and much more) on every startup.

Caching the response and falling back to a cached copy is probably reasonably doable with some work. There is however the problem of updates in the Plejd app/system not propagating unless you fetch the data from the server, so it's not trivial what the best retention policy is.

I have seen occasions when the Plejd public API is non-responsive, so some cache would be nice. I also don't know how Plejd themselves feel about us using the API - could it be disabled all of a sudden?

Sideloading the config (download from other computer or hand-code) would be a lot more work as I see it.

**Comment by icanos** [comment]
Currently we're using the same API as the app does. However, a cache would be nice and I think that we could implement that in the manner of caching the API response for X minutes (to prevent multiple API calls each reconnect time). We'd need to query the API at least on startup (after a HA reboot) to make sure to get any new devices and/or mesh changes.

Things like crypto key (which is essentially the crucial part) would certainly be possible to cache since that doesn't seem to change over time.

We could maybe utilize the cache as a fallback on boot up if the API is unavailable, but the risk doing this is that we misses out on any device changes done between last caching and now.

Another risk will of course be many issues opened due to mismatching devices and/or failures to turn on/off lights. Although a clear warning message in the log about the API being unavailable would perhaps help here.

**Comment by SweVictor** [comment]
Implemented a first idea for caching. Sneak preview of the log below. Code is same branch as in #158 

```
2021-02-08 22:20:08 INF [plejd-api] Getting cached api response from disk
2021-02-08 22:20:08 DBG [plejd-api] Prefer cache? true
2021-02-08 22:20:08 DBG [plejd-api] Cache exists? Yes, created 2021-02-08T21:02:02.799Z
2021-02-08 22:20:08 INF [plejd-api] Cache preferred. Skipping api requests and setting api data to response from 2021-02-08T21:02:02.799Z
```

**Comment by SweVictor** [comment]
Merged to [develop branch](https://github.com/icanos/hassio-plejd/tree/develop), planned for 0.6.0 release. Closing
