### ISSUE TITLE
light transition: not supported?

### ISSUE THREAD

**Issue by f00dagi** [icanos/hassio-plejd#15]
Hi Marcus

Great job, thanks for the hassio-Plejd integration, very useful.

I have tested it now for couple of hours but I cannot get the transition: parameter to work properly on Plejd light sources. I have tested transition on IKEA tradfri light sources and that works perfectly.

Hope you have the time to look into this issue, transition is a very nice feature to have.

For troubleshooting I have used Developer Tools > Services with...
Service: light.turn_on
Entity: light.allrum_tak_2
Service Data
1 entity_id: light.allrum_tak_2
2 brightness: 250
3 transition: 30

...but the light instantly goes to brightness 250. If I replace the Plejd light source with Tradfri it works with this code.

-Daniel

**Comment by icanos** [comment]
Transitions are not yet implemented, but I’ll look into it. Doesn’t seem to be too hard to add. Thanks!

**Comment by f00dagi** [comment]
Then I understand why I don’t get it to work. Thanks for a quick reply, I really look forward to your update with transition support.

**Comment by axlthorell** [comment]
Really a great add-on! I'm also hoping for transition to work with plejd.
Does plejd trigger any events to use as automation triggers? 
Switches not linked to any lights, can they be used to trigger something in HA?

**Comment by icanos** [comment]
Yes, I think you could. All Plejd devices triggers events when the state changes.

But, I don’t have a switch so I’m not sure what events to listen for. What kind of events would you wanna have?

Currently, if you turn on/off a light in the Plejd app or physically, the state of the device is propagated to HA as well.

**Comment by axlthorell** [comment]
I'm thinking if I turn on/off a wall switch (button) and I have no output selected for this button in the plejd-app I still want to be able to trigger automations.
Just like plejd has double click to activate a scene, I want to be able to use single and double click to activate something in HA. The scenes in the plejd app is a bit to simple, for instance I cant use double click to turn on and off another light, only activate a scene.

**Comment by icanos** [comment]
I've been looking into the events that is triggered for eg. a double click of a switch. It sends a notification if the action is tied to a scene in Plejd, but if I set it to 'Inget' on a double click, the event is not sent. I could add a mqtt message for this kind of scenario so that you can use that as an automation trigger, would that help?

**Comment by axlthorell** [comment]
Sounds great! Would I then keep the plejd double click on 'Inget' in the app?

**Comment by icanos** [comment]
No, unfortunately, you would need to have a scene tied to the double click, otherwise we wouldn't get a notification from Plejd.

**Comment by icanos** [comment]
The dev branch contains code that supports transitions now, currently it's really broken for turning off lights but works for turning on :) if anyone can/want they can test the code in that branch.

**Comment by f00dagi** [comment]
How is that best tested; uninstall the version I have now and manually install the dev branch?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by spripe** [comment]
Is there any event created/seen by this addon if a scenario is triggered through the plejd app or via plejd switches? I.e if I single click a switch, day scenario is called. Will that create an event I could use for automation? And the same for doubleclick.
Is there any way to execute an plejd scenario through this addon which then will use the same dim_
-levels that specified in the app?

**Comment by icanos** [comment]
Yes, when installing the version found in the dev branch, you will get a notification on MQTT topic plejd/event/scene with the scene number that has been triggered. I will probably push that to master in a few days.

**Comment by f00dagi** [comment]
Hi, I tested the dev version. Transition in itself works, I executed the following automation where the brightness go from 10 to 255 over 30 seconds.

Unfortunately the transition ends by setting the brightness back to 10 so there is something for you to look into. Great work though! Looking forward to having an updated version on the master branch soon.

'''
- id: '1570820783744'
  alias: light at 19:30
  trigger:
  - at: '21:22'
    platform: time
  action:
  - data:
      entity_id:  light.allrum_tak
      brightness: 255
      transition: 30
    service: light.turn_on
'''

**Comment by icanos** [comment]
Could you try the same, but instead of 255, use brightness: 254. Does it still toggle back to 10?

**Comment by f00dagi** [comment]
I would love to but unfortunately I will not have access to my system the coming week. I will let you know when I have tested it unless you chose to push it to Master regardless.

On 23 Dec 2019, at 12:41, Marcus Westin <notifications@github.com> wrote:

﻿

Could you try the same, but instead of 255, use brightness: 254. Does it still toggle back to 10?

**Comment by spripe** [comment]
> Yes, when installing the version found in the dev branch, you will get a notification on MQTT topic plejd/event/scene with the scene number that has been triggered. I will probably push that to master in a few days.

And what about if there's any way to execute an plejd scenario through this addon which then will use the same dim_-levels that specified in the app?

**Comment by icanos** [comment]
Yes, that would be possible, I need to add the "trigger scene" command to the add-on as well in that case. Should scenarios be discovered as devices or just give the ability to trigger a scenario through MQTT (using automations etc)?

**Comment by spripe** [comment]
I think it will be a really good start if we can trigger a scene through MQTT for use in automations

**Comment by Mikro007** [comment]
When will the RTR-01 be supported?

**Comment by icanos** [comment]
Closing this issue as resolved and refers to the other two issues created regarding the transition bug #26  and scene triggering through MQTT #43.
