### ISSUE TITLE
Raspberry problem whit mesh.

### ISSUE THREAD

**Issue by magztar** [icanos/hassio-plejd#16]
Hallo, great work whit this integration.
I have discovered problems whit raspberry bluetooth not connecting to units that has som distance from outer units. I have no problems when i use the app on the phone.
The unit that I have the problems whit is in the garage. It works great whit the phone in the house butt not whit the raspberry. Is the mesh different? Or are the messages sent from phone app different to messages from HA?
/Magnus

**Comment by icanos** [comment]
Thanks your reporting your issuse. What device do you have in the garage? The commands should be the same, but I would need some more information. Is it a device with multiple outputs?

**Comment by magztar** [comment]
I’ve tried both whit controller and single dimmer. It’s strange, maybe the mesh doesn't work from the messages that are sent from Ha.

**Comment by magztar** [comment]
I’ve  have to mention that if i use the plejd app and change de dimmer in garage it is instant reporting to Ha every time.  But when I change the value or turn on/off the light in Ha it sometimes not responding or extremely laggy.

**Comment by icanos** [comment]
Sorry but I can't say that I've seen that. What device are you using?

**Comment by magztar** [comment]
Right now i’m using a DIM-01 in the garage. In the house I have 5 other devices that work god whit your integration. But like I mentioned before the plejd app has no problem adjusting the dimmer in garage inside main house. Its strange. My friend that i helped set this up also has this problem whit devices that is far from the pi.
It’s like that the messages sent from the raspberry doesn’t send between the devices, instead it send directly to the device.

**Comment by icanos** [comment]
I need to look into it a bit more, I have two Plejd devices in our garage which is about 15 m from where the Raspberry Pi 4 is located and that works without problem.

**Comment by magztar** [comment]
👍👍

**Comment by mattiasjonsson** [comment]
@icanos I have been running version 2.8 successfully for about 3 days now without any problems. Just wanted to let you know. Great work🥇 

rpi3b+
HassOS 3.8
Hass.io supervisor 195
HA 0.103.6
30+ Plejd devices (DIM-01, DIM-02, LED-10, CTR-01, REL-02, GWY-01, WPH-01)

Tips:
I have my pi right next the Plejd gateway, so I always get a reliable connection to the Plejd mesh.
Might help some of you.

**Comment by icanos** [comment]
Closing this issue, please reopen if the issues persist.
