### ISSUE TITLE
Scene id and device id can overlap meaning mqtt commands overlap

### ISSUE THREAD

**Issue by SweVictor** [icanos/hassio-plejd#161]
After debugging for a while why some Plejd scenes aren't working as they should, it turns out that their `sceneIndex` property can overlap with `deviceAddress`. I haven't deeply checked the code, but I'm quite sure these two are used as values in the mqtt commands which means the mqtt command `homeassistant/switch/plejd/8/set` could refer to both the device with address 8 and the scene with index 8.

It somewhat refers to #91 and #102, but I think this is a separate thing.

Anyone else experiencing this? What's the mqtt best practice regarding this? Should we change the id or the topic?

**Comment by icanos** [comment]
Maybe we should prefix the topic with 'device' or 'scene' depending on what it is?

**Comment by SweVictor** [comment]
Seems like a good idea. Or use serial numbers or similar as the id?

**Comment by icanos** [comment]
Do scenes have serial numbers?

**Comment by SweVictor** [comment]
The main id we get from a Plejd API is a UUID. In the main scene object (from the API) there is also a shorter "objectId".

The SceneId is what is referenced from for example SceneSteps, "doubleClick" command from buttons etc. 

In the response there is also a SceneIndex list (which I presume we use) where SceneId is mapped to a small number which can overlap device number. Other similar lookup lists (UUID => int) are "deviceIdrass","roomAddress", "outputAddress", "inputAddress" and "outputGroups" (what is controlled from a dimmer, a few of my "unknown device id" come from these). 

One scene from my API call:
```
    {
      "title": "Scene name",
      "sceneId": "8914a5e6-8791-4ea3-9130-797195754422",
      "siteId": "d3ccb42f-bab8-4d6f-a9c1-205f42a1b522",
      "hiddenFromSceneList": false,
      "settings": "{\"SceneType\":\"CreatedByUser\"}",
      "createdAt": "2018-08-06T17:13:21.788Z",
      "updatedAt": "2020-12-24T19:06:53.962Z",
      "ACL": {},
      "objectId": "GppuIXEuGC",
      "__type": "Object",
      "className": "Scene"
    },
    },
```

**Comment by icanos** [comment]
I think that the sceneId GUID and a device GUID would be preferred in that case, and then keep a mapping table between the GUID and the int or we keep both when enumerating the API?

**Comment by SweVictor** [comment]
Yeah, I think using the GUID as the Id is (maybe for both mqtt Id and for uniqueId towards HA?) would be the best way.

Also I think your idea to use a new prefix for scenes is a good one to reduce confusion regarding what is what. Maybe `light` and `switch` can stay and we can add `scene` and `room`?

**Comment by icanos** [comment]
Yeah, that seems like a nice approach! Then it'll be crystal clear what each GUID is representing :-)

**Comment by SweVictor** [comment]
Many options... Maybe the best way is to just land #102 first? Last comment is interesting https://github.com/icanos/hassio-plejd/pull/102#discussion_r567217949. DIM-02 of course needs to be supported, as well as the new wireless button, so just using device id / serial won't be enough here either.

**Comment by SweVictor** [comment]
#179 will address this issue (scenes are no longer switches, id uniqueness has been addressed), so closing this.
