### ISSUE TITLE
parse error: Expected string key before ':' at line 1, column 4/code 404

### ISSUE THREAD

**Issue by MrTengvall** [icanos/hassio-plejd#18]
Hi,

I manage to install mqtt broker and hassio plejd but when starting hassio plejd I get this error; 
....................................
Hass.io Add-on: Plejd
 Adds support for the Swedish home automation devices from Plejd.
-----------------------------------------------------------
 Add-on version: 0.1.1
 You are running the latest version of this add-on.
parse error: Expected string key before ':' at line 1, column 4
[08:56:24] ERROR: Unknown HTTP error occured
 System:   (armv7 / raspberrypi4)
 Home Assistant version: 0.103.4
 Supervisor version: 193
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[08:56:25] INFO: Starting the Plejd service...
[08:56:25] INFO: Verified permissions on startup script
[08:56:25] INFO: Executing startup script
[08:56:26] INFO: Wrote plejd.json
[08:56:26] INFO: Running add-on
error: unable to retrieve session token response: Error: Request failed with status code 404

Any idea of what the issue might be?
Thanks!

**Comment by axlthorell** [comment]
Error 404 means not found. Do you get this error if you restart the add-on multiple times?
The add-on tries to connect to [https://cloud.plejd.com/parse/](https://cloud.plejd.com/parse/)
Can you access that link? I get `{"error":"unauthorized"}` if I try to open it in a browser.

**Comment by MrTengvall** [comment]
I get the error several times. Neither I can access https://cloud.plejd.com/parse/ thru web browser, I also get {"error":"unauthorized"}. But should I be able to access that thru the web browser?

**Comment by axlthorell** [comment]
Could it be your site name not being found?
Verify your settings in the config.

**Comment by icanos** [comment]
You won't be able to access the page by browsing it using a browser. You need to correct client id header to get any data from there.

Based on the log however, it seems that your request is failing when authenticating against the API. Have you verified your credentials in the add-on configuration? Though 404 means Not Found, which suggests that the API is requested using the wrong URL. Do you have a gateway?

**Comment by MrTengvall** [comment]
Hi,

Managed to install it and get it up and Running. I think the issue was that I was using my username in the credentials instead of my e-mail.

Seems like the fault was om my side, sorry. Merry christmas and Thanks for this integration!
