### ISSUE TITLE
MQTTS connection problems with mqtt@~3.0.0

### ISSUE THREAD

**Issue by JohnPhoto** [icanos/hassio-plejd#181]
So I am still running on a rpi0 as a (monitored) "raw" nodejs process.
When I did an update of this repo and a fresh `npm install` I got a broken version of `mqtt@3.0.0`.

The broken version was not able at all to connect over MQTT over TLS, with the following error(s, got like 4/second):

```
0|main   | 2021-04-06 22:49:40 WRN [plejd-mqtt] Error emitted from mqtt client write EPROTO 3069359312:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 80
0|main   | Error: write EPROTO 3069359312:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 80
0|main   |     at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
```

I debugged this for a couple of hours before I started to isolate the problem to the actual `mqtt` library.
If I upgrade to `mqtt@^4.2.6` (latest) I can connect again without any problems. But if I revert changes (in incomming PR) back to `mqtt@~3.0.0` (which gives `3.0.0`) I can reproduce the problem.

**Comment by SweVictor** [comment]
Hmm, strange. Presumably something that changed in HA requiring a newer mqtt lib version?

I updated the packages in the newest PR (#179) on my end it seems to work for me as well. I don't think we should `^x.x.x` but rather `~x.x.x` to avoid suddenly updating major versions when users install the addon locally though.

If you have the opportunity it would be appreciated if someone else can test #179 before moving on to creating a "sensor update" channel as discussed in other issue.

**Comment by JohnPhoto** [comment]
I do not mind about `~` vs `^`, so stick with `~`. 

I might be able to test out #179, but this comment https://github.com/icanos/hassio-plejd/pull/179#issuecomment-811483014 scares me cause I am heavily dependent on Plejd Scenes in my automations. I will comment there to let you describe what I will have to look out for/fix.

**Comment by JohnPhoto** [comment]
> Hmm, strange. Presumably something that changed in HA requiring a newer mqtt lib version?

I mean the only thing I did was to `git pull master && npm install` in this repo and then I got the problematic `3.0.0`, It is not even involving HA in any way since HA is running on a different physical device for me.

**Comment by SweVictor** [comment]
Alright - so - I reached out to the HA community at https://community.home-assistant.io/t/mqtt-scene-config-discovery-from-addon-not-working/297211

Possibly the wrong sub-forum, but either way - no replies for over a week. 

Since I can't get scenes over mqtt to work at all I'll try reverting to using switches, hopefully in the next few days, unless I get some help from someone how to move forward.

**Comment by SweVictor** [comment]
Resolved in develop branch, will be included in next release.
