### ISSUE TITLE
Configuration instruction outdated

### ISSUE THREAD

**Issue by faanskit** [icanos/hassio-plejd#189]
The configuration instruction is dated and needs to up updated, in particular the MQTT parts.

The installation is much simpler than what is described. **No configuration** is needed at all in `configuration.yaml`.
The current instruction is confusing people with fresh installs.

Installation instruction with Mosquitto broker:
- Install Mosquitto as per instruction (Supervisor ==> Add-on Store ==> Mosquitto broker ==> Install)
- Find your MQTT username and password:
-- Configuration ==> Integrations ==> Configure (Mosquitto broker) ==> RE-CONFIGURE MQTT ==> Click the "eye" to get your password

Configure ha-plejd:
mqttBroker = http://localhost
mqttUsername = homeassistant (or whatever Mosquitto broker was configured to)
mqttPassword = [whatever Mosquitto broker was configured to]

**Comment by SweVictor** [comment]
Sounds like a good thing to fix. "RE-CONFIGURE" might not be the best option for ppl using Mosquitto for something else, but otherwise it sounds like a good strategy.

**Comment by faanskit** [comment]
> Sounds like a good thing to fix. "RE-CONFIGURE" might not be the best option for ppl using Mosquitto for something else, but otherwise it sounds like a good strategy.


No need to change anything, this is only to obtain the password in use (generated during installation).

**Comment by SweVictor** [comment]
Resolved in #192, merged to develop branch
