### ISSUE TITLE
(node:291) MaxListenersExceededWarning: Possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by claeshellgren** [icanos/hassio-plejd#19]
Hi,
The add-on randomly stops working with this error message in the add-on log:

> (node:291) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 write listeners added. Use emitter.setMaxListeners() to increase limit

When I restart the add-on it works again until it gives the error message again...

I'm running Hass.io in Docker on Ubuntu 19.04.

**Comment by icanos** [comment]
How often do you see this? It looks like the add-on doesn't clean up properly when a connection is lost. Need to look into it a bit more.

**Comment by mudape** [comment]
Same for me, Hassio 0.103.4 on RPi3B+ running HassOS 3.7. 

> (node:292) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 write listeners added. Use emitter.setMaxListeners() to increase limit

I have five DIM-02 and one CTR-01 in the mesh.
No other components or integrations are using bluetooth, just this one.

Don't know how often this happens. I'd say at least once per day.
Can I activate more logs?

**Comment by claeshellgren** [comment]
It's hard to say how often it happens. At least once a day, often more.
I have 3 DIM-01, 5 DIM-02, 1 CTR-01 and 1 GWY-01. The gateway is placed 20 cm from the Bluetooth transceiver the next closest Plejd device is 2 m from the transceiver.
I have tested with 2 different transceivers with the same result. ...

**Comment by JacobWiqvist** [comment]
Same for me. Get this message: 

Receives this message: (node: 292) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 write listeners added. Use emitter.setMaxListeners () to increase limit

**Comment by icanos** [comment]
Looking into this now, not sure where the leak happens yet though

**Comment by joadske** [comment]
HI, I have the same Error. After this Plejd add-on stops working.

(node:342) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 write listeners added. Use emitter.setMaxListeners() to increase limit

**Comment by icanos** [comment]
Can you please try the latest version (0.2.8) to see if it still gives you that warning?

**Comment by JacobWiqvist** [comment]
Verkar ta tid innan Ha det Gött Jacob! Ser update!

Fortfarande inget!

tors 16 jan. 2020 kl. 19:53 skrev Marcus Westin <notifications@github.com>:

**Comment by jzee** [comment]
Same problem, happened three times within 12h for me, plug-in must be restarted to work again. Tested with v0.2.7, there doesn’t seem to be a 0.2.8 available for auto-update

**Comment by icanos** [comment]
Strange, have you clicked the Refresh button (upper right corner) of the Add-on Store in Hass.io configuration? Do you have a stacktrace (log) to share?

**Comment by jzee** [comment]
@icanos i checked the hassio logs (not only home-assistant) and it turned out that the DNS went bonkers and even though it managed to get the hass.io update, it failed to resolve github. rebooted the host and all is good now, I see the 0.2.8 update. Will report results.

**Comment by icanos** [comment]
Think I might need to rewrite the add-on to use Bluez instead of noble for the BLE com. Noble seems to be too unsable, especially when it comes to poor connectivity conditions.

Please tell me how it goes with the latest version.

**Comment by JacobWiqvist** [comment]
What ever it takes!

fre 17 jan. 2020 kl. 15:22 skrev Marcus Westin <notifications@github.com>:

**Comment by jzee** [comment]
it appeared to sustain longer with 0.2.8 for me but failed again for me now after about 24h, with the same error. 
> (node:594) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 write listeners added. Use emitter.setMaxListeners() to increase limit

Without knowing how the mesh works under the hood, Is it possible that this depends on which node you initially connect to? Could it be a strategy to try and connect to the node with the strongest signal first? From what I can see in the logs the connection attempts appear to be random.

**Comment by icanos** [comment]
Valid question, let me see what I can do, I know that's been there in an early version but not anymore. Will add that back and we'll have another go and see if it helps.

**Comment by icanos** [comment]
I have released a new version 0.2.9 which sorts the device list before trying to connect, please test to see if it works any better.

**Comment by claeshellgren** [comment]
After installing 0.2.9 it can't connect at all. It givs a new error message:

scan completed, found 10 device(s).
onDeviceScanComplete()
trying to connect to the mesh network.
/plejd/ble.js:201
      sortedDevices = Object.values(this.devices).sort((a, b) => b.rssi - a.rssi);
                    ^

ReferenceError: sortedDevices is not defined
    at PlejdService.connect (/plejd/ble.js:201:21)
    at PlejdService.onDeviceScanComplete (/plejd/ble.js:538:10)
    at PlejdService.emit (events.js:198:13)
    at Timeout.setTimeout [as _onTimeout] (/plejd/ble.js:188:14)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

Have tried to Reinstall and Rebuild with no success...

**Comment by icanos** [comment]
Yes, I noticed. Sorry about that. Should be fixed now

**Comment by icanos** [comment]
It seems that Hass.io doesn't download new code if no new version is added, so I've updated to 0.2.10.

**Comment by JacobWiqvist** [comment]
Worsen then ever...

Did not work for more than a few hours :

s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing...
----------------------------------------------------------- Hass.io
Add-on: Plejd Adds support for the Swedish home automation devices
from Plejd.-----------------------------------------------------------
Add-on version: 0.2.10 You are running the latest version of this
add-on.
parse error: Expected string key before ':' at line 1, column 4
[20:45:12] ERROR: Unknown HTTP error occured System:   (armv7 /
raspberrypi3) Home Assistant version: 0.103.6 Supervisor version:
195----------------------------------------------------------- Please,
share the above information when looking for help or support in, e.g.,
GitHub, forums or the Discord
chat.-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing...
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[20:45:14] INFO: Starting the Plejd service...
[20:45:14] INFO: Verified permissions on startup script
[20:45:14] INFO: Executing startup script
[20:45:16] INFO: Wrote plejd.json
[20:45:16] INFO: Running add-on
starting Plejd add-on v. 0.2.10
plejd-api: login()
plejd-api: logging into Jacob
plejd-api: got session token response
plejd-api: getCryptoKey()
plejd-api: got sites response
wireEvents()
onInterfaceStateChanged(poweredOn)
scan()
plejd-mqtt: connected to mqtt.
plejd-mqtt: discovered light named Hall Övervåning with PID 39.
plejd-mqtt: discovered light named Trappa  with PID 35.
plejd-mqtt: discovered light named Badrum Nedre with PID 21.
plejd-mqtt: discovered light named Vardagsrum Tak with PID 16.
plejd-mqtt: discovered light named Victor Tak with PID 57.
plejd-mqtt: discovered light named Övervåning Soffa with PID 69.
plejd-mqtt: discovered light named Hanna Säng with PID 73.
plejd-mqtt: discovered light named Trappa Huvudentré with PID 43.
plejd-mqtt: discovered light named Hall mitten with PID 52.
plejd-mqtt: discovered light named Hanna Tak with PID 11.
plejd-mqtt: discovered light named Övervåning Allrum tvillingar with PID 65.
plejd-mqtt: discovered light named Fläkt simulator with PID 80.
plejd-mqtt: discovered light named Kontor Säng with PID 30.
plejd-mqtt: discovered light named Ytterbelysning with PID 78.
plejd-mqtt: discovered light named Hall Groventre’ with PID 48.
plejd-mqtt: discovered light named Victor Säng with PID 61.
plejd-mqtt: discovered light named Kontor tak with PID 26.
plejd-mqtt: discovered switch named Hall WC with PID 79.
scan completed, found 15 device(s).
onDeviceScanComplete()
trying to connect to the mesh network.
connecting to d2f823ebde9c with addr d2:f8:23:eb:de:9c and rssi -54
onDeviceConnected()
authenticate()
startPing()
plejd: connected via bluetooth.
(node:290) MaxListenersExceededWarning: Possible EventEmitter memory
leak detected. 11 write listeners added. Use emitter.setMaxListeners()
to increase limit


lör 18 jan. 2020 kl. 19:24 skrev Marcus Westin <notifications@github.com>:

**Comment by joadske** [comment]
Hi, same problem for me. Is there something i can do to help?

> (node:291) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 write listeners added. Use emitter.setMaxListeners() to increase limit
>

**Comment by icanos** [comment]
It looks like the issue presents itself from the noble library, not the plejd add-on. I'm working on replacing noble with dbus/bluez instead, can't give you an exact timeline yet, but I'm working on it in the bluez branch.

**Comment by JacobWiqvist** [comment]
Pleas give a timeline😜🙈🙈🙈🙈😭

sön 19 jan. 2020 kl. 15:42 skrev Marcus Westin <notifications@github.com>:

**Comment by jzee** [comment]
It’s been stable for me for today at least but I’ll update if it occurs again. 

For you guys who are still suffering the effect, make sure to close and kill the plejd app when restarting HA so that it doesn’t “occupy” the connection with the closest node, this will worsen the mesh connection I found.

Thanks for putting in the work @icanos!

**Comment by JacobWiqvist** [comment]
Can you guide me threw the processes you got it working!

When you say "close and kill"

Do you mean the "STOP" button in the addon.

Should I rebuild?

Start addon when hassio start?

Pleas go threw how I should do?

sön 19 jan. 2020 kl. 18:05 skrev Jörg Ziegler <notifications@github.com>:

**Comment by jzee** [comment]
@JacobWiqvist I meant close and kill the plejd app _on your mobile phone/tablet._ I found that this interferes with the connection process.

**Comment by JacobWiqvist** [comment]
Seam to stop working any way?

The only thing in the log

(node:291) MaxListenersExceededWarning: Possible EventEmitter memory
leak detected. 11 write listeners added. Use emitter.setMaxListeners()
to increase limit


sön 19 jan. 2020 kl. 15:42 skrev Marcus Westin <notifications@github.com>:

**Comment by JacobWiqvist** [comment]
Maybe I have not gone threw all the Plejd apps on my wifes, and
daughters mobile phones and closed them to.

It stoped working today any way.

Den sön 19 jan. 2020 kl 19:06 skrev Jörg Ziegler <notifications@github.com>:

**Comment by icanos** [comment]
I'll start testing the new DBus/BlueZ implementation today at home, hopefully I can release it sometime this week.

**Comment by JacobWiqvist** [comment]
Nice. Keep up the good work

mån 20 jan. 2020 kl. 09:15 skrev Marcus Westin <notifications@github.com>:

**Comment by JacobWiqvist** [comment]
Hi!

What possibly to ad WPH-01 As an input device when you reprogram the addon
is it for you?

I realy want bothe WPH-01 and the rotary part RTR-01 of the dimmer, as an
input device?

Best regards Jacob Wiqvist

mån 20 jan. 2020 kl. 09:15 skrev Marcus Westin <notifications@github.com>:

**Comment by JacobWiqvist** [comment]
?

mån 20 jan. 2020 kl. 09:15 skrev Marcus Westin <notifications@github.com>:

**Comment by JacobWiqvist** [comment]
Is it possible for you to as support for WPH-01 to?



mån 20 jan. 2020 kl. 09:15 skrev Marcus Westin <notifications@github.com>:

**Comment by icanos** [comment]
I don’t own a WPH-01 so that’s not something I can do now, unfortunately.

**Comment by JacobWiqvist** [comment]
If I send you one?


Best regards Jacob

ons 22 jan. 2020 kl. 17:43 skrev Marcus Westin <notifications@github.com>:

**Comment by icanos** [comment]
I could try, but can't promise anything. Please create a new issue in that case :)

**Comment by icanos** [comment]
I have finally committed version 0.3.0 which contains the new BLE manager, please try that to see if it works any better for you.

**Comment by JacobWiqvist** [comment]
What adress should I send it to?

How is it going with the rewrite of the addon?

Best regards Jacob Wiqvist

fre 24 jan. 2020 kl. 10:16 skrev Marcus Westin <notifications@github.com>:

**Comment by JacobWiqvist** [comment]
Is this correct:

plejd-api: getCryptoKey()
plejd-api: got sites response
wireEvents()
events.js:174
      throw er; // Unhandled 'error' event
      ^
Error: connect ENOENT /var/run/dbus/system_bus_socket
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
Emitted 'error' event at:
    at EventEmitter.MessageBus.conn.on
(/plejd/node_modules/dbus-next/lib/bus.js:155:12)
    at EventEmitter.emit (events.js:198:13)
    at Socket.<anonymous>
(/plejd/node_modules/dbus-next/lib/connection.js:82:10)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[10:56:23] INFO: Starting the Plejd service...
[10:56:23] INFO: Verified permissions on startup script
[10:56:23] INFO: Executing startup script
[10:56:25] INFO: Wrote plejd.json
[10:56:25] INFO: Running add-on
starting Plejd add-on v. 0.3.0
plejd-api: login()
plejd-api: logging into Jacob
plejd-api: got session token response
plejd-api: getCryptoKey()
plejd-api: got sites response
wireEvents()
events.js:174
      throw er; // Unhandled 'error' event
      ^
Error: connect ENOENT /var/run/dbus/system_bus_socket
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
Emitted 'error' event at:
    at EventEmitter.MessageBus.conn.on
(/plejd/node_modules/dbus-next/lib/bus.js:155:12)
    at EventEmitter.emit (events.js:198:13)
    at Socket.<anonymous>
(/plejd/node_modules/dbus-next/lib/connection.js:82:10)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[10:56:28] INFO: Starting the Plejd service...
[10:56:28] INFO: Verified permissions on startup script
[10:56:28] INFO: Executing startup script
[10:56:30] INFO: Wrote plejd.json
[10:56:30] INFO: Running add-on
starting Plejd add-on v. 0.3.0
plejd-api: login()
plejd-api: logging into Jacob
plejd-api: got session token response
plejd-api: getCryptoKey()
plejd-api: got sites response
wireEvents()
events.js:174
      throw er; // Unhandled 'error' event
      ^
Error: connect ENOENT /var/run/dbus/system_bus_socket
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
Emitted 'error' event at:
    at EventEmitter.MessageBus.conn.on
(/plejd/node_modules/dbus-next/lib/bus.js:155:12)
    at EventEmitter.emit (events.js:198:13)
    at Socket.<anonymous>
(/plejd/node_modules/dbus-next/lib/connection.js:82:10)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[10:56:33] INFO: Starting the Plejd service...
[10:56:33] INFO: Verified permissions on startup script
[10:56:33] INFO: Executing startup script
[10:56:35] INFO: Wrote plejd.json
[10:56:35] INFO: Running add-on
starting Plejd add-on v. 0.3.0
plejd-api: login()
plejd-api: logging into Jacob
plejd-api: got session token response
plejd-api: getCryptoKey()
plejd-api: got sites response
wireEvents()
events.js:174
      throw er; // Unhandled 'error' event
      ^
Error: connect ENOENT /var/run/dbus/system_bus_socket
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
Emitted 'error' event at:
    at EventEmitter.MessageBus.conn.on
(/plejd/node_modules/dbus-next/lib/bus.js:155:12)
    at EventEmitter.emit (events.js:198:13)
    at Socket.<anonymous>
(/plejd/node_modules/dbus-next/lib/connection.js:82:10)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[10:56:38] INFO: Starting the Plejd service...
[10:56:38] INFO: Verified permissions on startup script
[10:56:38] INFO: Executing startup script
[10:56:39] INFO: Wrote plejd.json
[10:56:39] INFO: Running add-on


fre 24 jan. 2020 kl. 10:26 skrev Marcus Westin <notifications@github.com>:

**Comment by icanos** [comment]
No, somehow the dbus access from the Docker container slipped from config.json, I've updated that and released 0.3.1.

**Comment by JacobWiqvist** [comment]
No update available jet!

fre 24 jan. 2020 kl. 11:01 skrev Marcus Westin <notifications@github.com>:

**Comment by JacobWiqvist** [comment]
Also what does this do: "

   - FIX: Adding entities as devices now as well"


fre 24 jan. 2020 kl. 11:01 skrev Marcus Westin <notifications@github.com>:

**Comment by JacobWiqvist** [comment]
Why does it takes do much time before I  can see the update?

Can you do anything to make it go faster?

fre 24 jan. 2020 kl. 11:01 skrev Marcus Westin <notifications@github.com>:

**Comment by icanos** [comment]
No, if I browse Hass.io in the left menu, clicks on "Add-on Store" and then the arrow in the top right corner (Refresh), the version updates, instantly. So if that doesn't work for you, there's some caching or other error in your end unfortunately.

Devices/entities means that all Plejds show up as Devices in Home Assistant (Configuration > Devices)

**Comment by JacobWiqvist** [comment]
I know how browsers and browser cash works, I think!

Latest version don't seem to work :

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing...
----------------------------------------------------------- Hass.io
Add-on: Plejd Adds support for the Swedish home automation devices
from Plejd.-----------------------------------------------------------
Add-on version: 0.3.1 You are running the latest version of this
add-on.
parse error: Expected string key before ':' at line 1, column 4
[16:19:13] ERROR: Unknown HTTP error occured System:   (armv7 /
raspberrypi3) Home Assistant version: 0.103.6 Supervisor version:
195----------------------------------------------------------- Please,
share the above information when looking for help or support in, e.g.,
GitHub, forums or the Discord
chat.-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing...
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:19:15] INFO: Starting the Plejd service...
[16:19:15] INFO: Verified permissions on startup script
[16:19:15] INFO: Executing startup script
[16:19:17] INFO: Wrote plejd.json
[16:19:17] INFO: Running add-on
starting Plejd add-on v. 0.3.1
plejd-api: login()
plejd-api: logging into Jacob
plejd-api: got session token response
plejd-api: getCryptoKey()
plejd-api: got sites response
wireEvents()
plejd-ble: disconnecting /org/bluez/hci0/dev_D2_F8_23_EB_DE_9C
plejd-mqtt: connected to mqtt.
plejd-mqtt: discovered light named Hall Övervåning with PID 39.
plejd-mqtt: discovered light named Trappa  with PID 35.
plejd-mqtt: discovered light named Badrum Nedre with PID 21.
plejd-mqtt: discovered light named Vardagsrum Tak with PID 16.
plejd-mqtt: discovered light named Victor Tak with PID 57.
plejd-mqtt: discovered light named Övervåning Soffa with PID 69.
plejd-mqtt: discovered light named Hanna Säng with PID 73.
plejd-mqtt: discovered light named Trappa Huvudentré with PID 43.
plejd-mqtt: discovered light named Hall mitten with PID 52.
plejd-mqtt: discovered light named Hanna Tak with PID 11.
plejd-mqtt: discovered light named Övervåning Allrum tvillingar with PID 65.
plejd-mqtt: discovered light named Fläkt simulator with PID 80.
plejd-mqtt: discovered light named Kontor Säng with PID 30.
plejd-mqtt: discovered light named Ytterbelysning with PID 78.
plejd-mqtt: discovered light named Hall Groventre’ with PID 48.
plejd-mqtt: discovered light named Victor Säng with PID 61.
plejd-mqtt: discovered light named Kontor tak with PID 26.
plejd-mqtt: discovered switch named Hall WC with PID 79.
plejd-ble: connecting to /org/bluez/hci0/dev_D2_F8_23_EB_DE_9C
onDeviceConnected()
trying 10 characteristics
authenticate()
startPing()


fre 24 jan. 2020 kl. 14:28 skrev Marcus Westin <notifications@github.com>:

**Comment by icanos** [comment]
You're connected and should be able to rule your lights, at least according to the log :)

**Comment by JacobWiqvist** [comment]
Seem to work dispite the hassio io

fre 24 jan. 2020 kl. 18:38 skrev Marcus Westin <notifications@github.com>:

**Comment by JacobWiqvist** [comment]
Hi!

For some reason it does not work!

I have rebuild and started the addon!

Restarted hassio.


[s6-init] making user provided files available at /var/run/s6/etc...exited
0. [s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes... [fix-attrs.d] done.
[cont-init.d] executing container initialization scripts... [cont-init.d]
00-banner.sh: executing...
----------------------------------------------------------- Hass.io Add-on:
Plejd Adds support for the Swedish home automation devices from Plejd.
-----------------------------------------------------------
Add-on version: 0.3.3
You are running the latest version of this add-on.
parse error: Expected string key before ':' at line 1, column 4 [10:43:26]
ERROR: Unknown HTTP error occured System: (armv7 / raspberrypi3) Home
Assistant version: 0.104.3
Supervisor version: 195
----------------------------------------------------------- Please, share
the above information when looking for help or support in, e.g., GitHub,
forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0. [cont-init.d] 01-log-level.sh:
executing... [cont-init.d] 01-log-level.sh: exited 0. [cont-init.d] done.
[services.d] starting services [services.d] done. [10:43:28] INFO: Starting
the Plejd service... [10:43:28] INFO: Verified permissions on startup script
[10:43:28] INFO: Executing startup script [10:43:30] INFO: Wrote plejd.json
[10:43:30] INFO: Running add-on starting Plejd add-on v. 0.3.3 plejd-api:
login() plejd-api: logging into Jacob plejd-api: got session token response
plejd-api: getCryptoKey() plejd-api: got sites response wireEvents()
plejd-ble: disconnecting /org/bluez/hci0/dev_D2_F8_23_EB_DE_9C plejd-mqtt:
connected to mqtt. plejd-mqtt: discovered light named Hall Övervåning with
PID 39. plejd-mqtt: discovered light named Trappa with PID 35. plejd-mqtt:
discovered light named Badrum Nedre with PID 21. plejd-mqtt: discovered
light named Vardagsrum Tak with PID 16. plejd-mqtt: discovered light named
Victor Tak with PID 57. plejd-mqtt: discovered light named Övervåning Soffa
with PID 69. plejd-mqtt: discovered light named Hanna Säng with PID 73.
plejd-mqtt: discovered light named Trappa Huvudentré with PID 43.
plejd-mqtt: discovered light named Hall mitten with PID 52. plejd-mqtt:
discovered light named Hanna Tak with PID 11. plejd-mqtt: discovered light
named Övervåning Allrum tvillingar with PID 65. plejd-mqtt: discovered
light named Fläkt simulator with PID 80. plejd-mqtt: discovered light named
Kontor Säng with PID 30. plejd-mqtt: discovered light named Ytterbelysning
with PID 78. plejd-mqtt: discovered light named Hall Groventre’ with PID
48. plejd-mqtt: discovered light named Victor Säng with PID 61. plejd-mqtt:
discovered light named Kontor tak with PID 26. plejd-mqtt: discovered
switch named Hall WC with PID 79.




Den fre 24 jan. 2020 kl 18:38 skrev Marcus Westin <notifications@github.com

**Comment by icanos** [comment]
According to the log, the add-on hasn't even tried to connect to Plejd yet, startup can take upto 1 min sometimes, depending on which Raspberry Pi you're using and how many other add-ons that is running.

**Comment by icanos** [comment]
Also, I'm closing this issue since the original error originates from pre 0.3.x. Please open a new issue if the problems continue :)

**Comment by JacobWiqvist** [comment]
Hmmmm...,

at _methodReturnHandlers.(anonymous function)
(/plejd/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.MessageBus.conn.on
(/plejd/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:198:13)
    at /plejd/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:55:9)
    at Socket.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:554:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:291) UnhandledPromiseRejectionWarning: Unhandled promise
rejection. This error originated either by throwing inside of an async
function without a catch block, or by rejecting a promise which was
not handled with .catch(). (rejection id: 2506)
init()
onDeviceConnected()
plejd-ble: warning: wasn't able to connect to Plejd, will retry.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
(node:291) UnhandledPromiseRejectionWarning: DBusError: Operation
already in progress
    at _methodReturnHandlers.(anonymous function)
(/plejd/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.MessageBus.conn.on
(/plejd/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:198:13)
    at /plejd/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:55:9)
    at Socket.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:554:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:291) UnhandledPromiseRejectionWarning: Unhandled promise
rejection. This error originated either by throwing inside of an async
function without a catch block, or by rejecting a promise which was
not handled with .catch(). (rejection id: 2507)
init()
onDeviceConnected()
plejd-ble: warning: wasn't able to connect to Plejd, will retry.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
(node:291) UnhandledPromiseRejectionWarning: DBusError: Operation
already in progress
    at _methodReturnHandlers.(anonymous function)
(/plejd/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.MessageBus.conn.on
(/plejd/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:198:13)
    at /plejd/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:55:9)
    at Socket.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:554:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:291) UnhandledPromiseRejectionWarning: Unhandled promise
rejection. This error originated either by throwing inside of an async
function without a catch block, or by rejecting a promise which was
not handled with .catch(). (rejection id: 2508)
init()
onDeviceConnected()
plejd-ble: warning: wasn't able to connect to Plejd, will retry.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
(node:291) UnhandledPromiseRejectionWarning: DBusError: Operation
already in progress
    at _methodReturnHandlers.(anonymous function)
(/plejd/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.MessageBus.conn.on
(/plejd/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:198:13)
    at /plejd/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:55:9)
    at Socket.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:554:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:291) UnhandledPromiseRejectionWarning: Unhandled promise
rejection. This error originated either by throwing inside of an async
function without a catch block, or by rejecting a promise which was
not handled with .catch(). (rejection id: 2509)
init()
onDeviceConnected()
plejd-ble: warning: wasn't able to connect to Plejd, will retry.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
(node:291) UnhandledPromiseRejectionWarning: DBusError: Operation
already in progress
    at _methodReturnHandlers.(anonymous function)
(/plejd/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.MessageBus.conn.on
(/plejd/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:198:13)
    at /plejd/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:55:9)
    at Socket.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:554:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:291) UnhandledPromiseRejectionWarning: Unhandled promise
rejection. This error originated either by throwing inside of an async
function without a catch block, or by rejecting a promise which was
not handled with .catch(). (rejection id: 2510)
init()
onDeviceConnected()
plejd-ble: warning: wasn't able to connect to Plejd, will retry.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
(node:291) UnhandledPromiseRejectionWarning: DBusError: Operation
already in progress
    at _methodReturnHandlers.(anonymous function)
(/plejd/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.MessageBus.conn.on
(/plejd/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:198:13)
    at /plejd/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:55:9)
    at Socket.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:554:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:291) UnhandledPromiseRejectionWarning: Unhandled promise
rejection. This error originated either by throwing inside of an async
function without a catch block, or by rejecting a promise which was
not handled with .catch(). (rejection id: 2511)
init()
onDeviceConnected()
plejd-ble: warning: wasn't able to connect to Plejd, will retry.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
(node:291) UnhandledPromiseRejectionWarning: DBusError: Operation
already in progress
    at _methodReturnHandlers.(anonymous function)
(/plejd/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.MessageBus.conn.on
(/plejd/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:198:13)
    at /plejd/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:55:9)
    at Socket.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:554:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:291) UnhandledPromiseRejectionWarning: Unhandled promise
rejection. This error originated either by throwing inside of an async
function without a catch block, or by rejecting a promise which was
not handled with .catch(). (rejection id: 2512)


mån 27 jan. 2020 kl. 11:12 skrev Marcus Westin <notifications@github.com>:
