### ISSUE TITLE
Repostitory structure for 0.7.1 is not compliant

### ISSUE THREAD

**Issue by andreasropel** [icanos/hassio-plejd#202]
Just updated HASS to 
Version
supervisor-2021.05.4

Found error "Platform error light.plejd - Integration 'plejd' not found." when tried to check config and restart HASS.
Tried to re-enter git repo to HACS and got error "Repostitory structure for 0.7.1 is not compliant". 

Please advice.
Thanks.

**Comment by SweVictor** [comment]
Hmm... I am running `supervisor-2021.05.4` without problems it seems. I am running a side-loaded (manual install) version though. Anyone knows of any changes made to repo structure? Would be a good change to include in the v0.8.0 release!

**Comment by andreasropel** [comment]
Same here.. Side loaded it is. Did a git clone to make sure I have the most recent version installed on HASS.

**Comment by SweVictor** [comment]
Oh wait... I think I did this in the beginning too!

Don't add to HASS, add as repo in Configuration => Integration (Home Assistant integration, not Hass addon)

**Comment by andreasropel** [comment]
It's added under 'Supervisor' - > 'Add-on store'. Not HACS. Sorry for confusion. 
As said, all logs look ok, I can use HASS to switch on lights as designed. 

In light.yaml I have correct syntax and indentation as follow:

```
- platform: plejd
  crypto_key: <**key**>
  devices:
    11:
      name: bedroom_ceiling
    13:
      name: outdoor_entrance
    15:
      name: kitchen_ceiling
```

And still, when I check configuration if valid I got error:
"Platform error light.plejd - Integration 'plejd' not found.". 

Elsewhere to check in my config? 
Just updated to supervisor-2021.06.0, issue still persist. 
Please advice.

**Comment by SweVictor** [comment]
I'm not sure exactly what you have added, there are more than one Plejd plugin. This one does not require anything in any of the config files (except to set up mqtt). Everything is configured in the config of the plugin itself (second tab), crypto key is fetched automatically from the Plejd API, etc.

Maybe you have installed both this plugin and https://github.com/klali/ha-plejd (which does require manually adding devices and crypto key)?

**Comment by andreasropel** [comment]
I remove everything - All related to Plejd and installed  https://github.com/klali/ha-plejd. 
Now all is ok! Guess we can close issue and many thanks for support from your side. 
--A

**Comment by SweVictor** [comment]
@andreasropel : In case you want to switch back to THIS addon (that does not require manual fiddling with devices or crypto keys) 0.8.0-beta was just released. If you try and still can't install that I'd be happy to take a look.

**Comment by SweVictor** [comment]
I can also report back that installing the public version worked well for me after the v0.8 release. I did have to reload repository information and possibly restart, so there might be some strange caching going on.

**Comment by andreasropel** [comment]
Sorry for late reply. 
I will see if I can manage to get it working during the week. Will report back to you when I have made an attempt.
