### ISSUE TITLE
2021-06-25 02:00:10 ERR [plejd-ble] Failed to start discovery. Operation already in progress DBusError: Operation already in progress

### ISSUE THREAD

**Issue by Ludde157** [icanos/hassio-plejd#210]
Hey, 

I've got this message in my log:
2021-06-25 02:00:10 ERR [plejd-ble] Failed to start discovery. Operation already in progress
DBusError: Operation already in progress

And when I go into terminal, bluetoothctl I see that my Raspberry pi bluetooth and my bluetooth adapter is on and I cannot turn off the internal bluetooth.

<img width="425" alt="Skärmavbild 2021-06-25 kl  01 56 56" src="https://user-images.githubusercontent.com/57288064/123348274-88de2e80-d559-11eb-8751-a506361854b4.png">

Have you any solution?

**Comment by Megamannen** [comment]
https://github.com/icanos/hassio-plejd/issues/208

**Comment by SweVictor** [comment]
Closing this since discussion seems to have moved to 208.
