### ISSUE TITLE
Plejd got turn on command for ExternalHouse (plejd ID), brightness undefined

### ISSUE THREAD

**Issue by NachoMas** [icanos/hassio-plejd#212]
Hi all,

I'm testing the addon running standalone towards my MQTT mosquitto server that feeds home assistant core in a docker container. The discovery of the Plejd pucks happens all right but when I'm sending an ON command to them the addon responds with 'Plejd got turn on command for ExternalHouse (plejd ID), brightness undefined' for the four pucks below. I assume it must be something in the way HASS maps the plejd discovery to lights? But I'm not sure where to look any more. Any hints?

My pucks are discovered as follows:
Sending discovery for 7 Plejd output devices
2021-08-09 09:47:40 INF [plejd-mqtt] Discovered DIM-01 (light) named Spotlight kök (11 : Id_edited).
2021-08-09 09:47:40 INF [plejd-mqtt] Discovered CTR-01 (light) named ExternalHouse (13 : Id _edited).
2021-08-09 09:47:40 INF [plejd-mqtt] Discovered LED-10 (light) named Badrum Spotlights (15 : Id_edited).
2021-08-09 09:47:40 INF [plejd-mqtt] Discovered DIM-01 (light) named Koklampor (16 : Id_edited).
2021-08-09 09:47:40 INF [plejd-mqtt] Discovered Room (light) named Kitchen (10 : Id_edited).
2021-08-09 09:47:40 INF [plejd-mqtt] Discovered Room (light) named HouseFasade (12 : Id_edited).
2021-08-09 09:47:40 INF [plejd-mqtt] Discovered Room (light) named Toalett (14 : Id_edited).

thanks for the help!
/Nacho

**Comment by SweVictor** [comment]
My guess is it works as expectected? If I remember correctly "brightness undefined" just means that "currently the brightness of the light is undefined". As time progresses known brightnesses will be saved.

**Comment by NachoMas** [comment]
Yes, you are right. In fact the problem that the Plejd pucks where not responding related to the fact that I had not run the container in provileged mode, so it could not reach the BT dongle. Now everything is working as expected and I even have two different instances of the addon running on two different computers and controlling two plejd installations both of them from home assistant.
Thanks!

**Comment by SweVictor** [comment]
> Yes, you are right. In fact the problem that the Plejd pucks where not responding related to the fact that I had not run the container in provileged mode, so it could not reach the BT dongle. Now everything is working as expected and I even have two different instances of the addon running on two different computers and controlling two plejd installations both of them from home assistant.
> Thanks!

Very nice to hear, thanks for reporting back!

Regarding the issues you solved (privileged mode etc), and also potentially the multi-controller setup, I'm thinking those things could be of interest to others. If you have the time I would be very happy to accept a PR improving on the existing readme or troubleshooting guides to benefit others.
