### ISSUE TITLE
Invalid token for access /host/info

### ISSUE THREAD

**Issue by BriHay** [icanos/hassio-plejd#214]
Hello,
When I start the add-on, I get this message in the system log.
This is happening at the same time as I have the problem described in # 208 and have tested the suggested actions without success.
Can these problems be related?

_21-09-15 11:38:55 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1596' coro=<HomeAssistantWebSocket.async_send_command() done, defined at /usr/src/supervisor/supervisor/homeassistant/websocket.py:106> exception=TypeError('Received message 257:None is not str')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 134, in async_send_command
    return await self._client.async_send_command(message)
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 46, in async_send_command
    response = await self.client.receive_json()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_ws.py", line 291, in receive_json
    data = await self.receive_str(timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_ws.py", line 276, in receive_str
    raise TypeError(f"Received message {msg.type}:{msg.data!r} is not str")
TypeError: Received message 257:None is not str
21-09-15 11:38:57 WARNING (MainThread) [supervisor.api.middleware.security] 4cb18a39_plejd missing API permission for /host/info
21-09-15 11:38:57 ERROR (MainThread) [supervisor.api.middleware.security] Invalid token for access /host/info_

My environment is:
Raspberry Pi 4 Model B (2 GB RAM + SSD)
ASUS USB-BT500 (also tested with the internal bluetooth)
Home Assistant OS Version core-2021.9.6
Home Assistant OS 6.4
Plejd 0.8.0-beta

**Comment by SweVictor** [comment]
Strange. The only line talking at all about this addon is the "_plejd missing API permissions". This seems HA-related rather than specific to this app. Could it be some security setting?

If no one here knows, maybe ask in the larger HA community or search around?
