### ISSUE TITLE
Cannot read property 'plejdMesh'

### ISSUE THREAD

**Issue by clindland** [icanos/hassio-plejd#22]
Hi!
Love the idea of having a hassio add-on. I have an issue when starting up. I keep getting the following error:
'error: unable to retrieve the crypto key. error: TypeError: Cannot read property 'plejdMesh' of undefined' 

Under is a copy of the log:

`
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------

 Hass.io Add-on: Plejd
 Adds support for the Swedish home automation devices from Plejd.

-----------------------------------------------------------

 Add-on version: 0.1.1
 You are running the latest version of this add-on.
parse error: Expected string key before ':' at line 1, column 4
[21:37:30] ERROR: Unknown HTTP error occured
 System:   (armv7 / raspberrypi3)
 Home Assistant version: 0.103.4
 Supervisor version: 193

-----------------------------------------------------------

 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.

-----------------------------------------------------------

[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[21:37:35] INFO: Starting the Plejd service...
[21:37:35] INFO: Verified permissions on startup script
[21:37:35] INFO: Executing startup script
[21:37:39] INFO: Wrote plejd.json
[21:37:39] INFO: Running add-on
error: unable to retrieve the crypto key. error: TypeError: Cannot read property 'plejdMesh' of undefined
(node:291) UnhandledPromiseRejectionWarning: unable to retrieve the crypto key. error: TypeError: Cannot read property 'plejdMesh' of undefined
(node:291) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:291) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[21:37:44] INFO: Starting the Plejd service...
[21:37:44] INFO: Verified permissions on startup script
[21:37:44] INFO: Executing startup script
`

**Comment by icanos** [comment]
It looks like the API didn't return any result from the getSites request, could you maybe restart the add-on. Does the same thing happen?

**Comment by clindland** [comment]
> It looks like the API didn't return any result from the getSites request, could you maybe restart the add-on. Does the same thing happen?

I have restarted, rebuilded, reinstalled both the ad-on and my entire hass.io system, but unfortunately I still get the same error..

**Comment by icanos** [comment]
That is weird, I would love to get my hands on your response from the API :)

You can look in the api.js file and use Postman to simply make a request manually to the API and then send me the response (after you've masked any personal details).

Thanks!

**Comment by icanos** [comment]
If you still want/need help, please reopen this issue. Closing it now due to inactivity.
