### ISSUE TITLE
New devices

### ISSUE THREAD

**Issue by tallgatan2** [icanos/hassio-plejd#220]
I have 2 new Plejd devices, but i can't fugure out how to get them in.

I had to uninstall Plejd reboot HA and install pled again to get them in.

Is there a easier way?

**Comment by SweVictor** [comment]
@tallgatan2 Have you solved this? All devices are fetched during startup from the Plejd API, so as long as they are added in the app you should see them.

**Comment by oleander** [comment]
Make sure your devices are placed in the same home in the Plejd app, as the add-on only has support for one 'Home' or 'Site' as its called in the configuration.

**Comment by SweVictor** [comment]
Closed due to inactivity
