### ISSUE TITLE
Brightness control missing for one of my devices (DIM-01)

### ISSUE THREAD

**Issue by davidholm** [icanos/hassio-plejd#230]
I am new to HA and have recently managed to implement this nice add-on.
All devices have been loaded and everything works perfectly except that I can not control the brightness of one of my devices. It is a DIM-01 that works well and like all other of my DIM-01s in the official Plejd app.

In the log after restart of add-on it says "brightness undefined":
`2022-01-21 10:30:13 INF [device-comm] Plejd got turn on command for Fönsterlampa (FF4644C1A847_0), brightness undefined
`

Is it a quick fix?
Where can I start my troubleshooting?
Anyone had the same issue?

Thanks in advanced!

**Comment by icanos** [comment]
Could be that your DIM-01 has another hardware ID than those detected by us currently. We would need a copy of the JSON response from Plejd (stripped of any personal details) in order to debug this further.

**Comment by hjernberg** [comment]
Hi
Have implemeted this great add-on and testing the setup with a DIM-01. I can turn on/off but cant control brightness. In the log I have the same as davidholm "brightness undefined". Someone that knows how to fix the problem or is it not possible at this time to control the brightness?

/Henrik

**Comment by SweVictor** [comment]
Can you post verbose logs on what happens during startup? Refer to the readme for details on how to extract those.

**Comment by hjernberg** [comment]
Sorry for delay, brightness seems to work for me now. Not sure if it happend during the latest update...
