### ISSUE TITLE
Scences become "unavailable" at random instances

### ISSUE THREAD

**Issue by artkula** [icanos/hassio-plejd#233]
After the core update from 2022.2.0 to 2022.2.2, scenes became unavailable in HASS and therefore cannot be triggered by the home kit. Once activated through HASS directly they turn on for some time (just the activated scene) and then become "unavailable" again after a certain period. Other scenes from HUE and manually configured work fine.

**Comment by SweVictor** [comment]
Scenes and devices are set to unavailable when shutting down or restarting, but otherwise I don't know. What do the (verbose) logs say when this happens?

**Comment by SweVictor** [comment]
Closed due to inactivity
