### ISSUE TITLE
Installation of 0.8.0-beta failed

### ISSUE THREAD

**Issue by olajakobson** [icanos/hassio-plejd#235]
When trying to install this plejd add-on on my HA running in a VirtualBox image, I get below error message:

"Failed to install add-on
The command '/bin/bash -o pipefail -c apk add --no-cache --virtual .build-dependencies g++ gcc libc-dev linux-headers make python3 bluez eudev-dev && apk add --no-cache git nodejs npm dbus-dev glib-dev && npm config set unsafe-perm true' returned a non-zero code: 2"

I've tried using the "easy installation" as well as the "manual installation" steps - both resulting the same issue (see above). 

Any ideas of what goes wrong here?

Thanks!

**Comment by Wronek** [comment]
I have also problem with instalation of this version.

**Comment by MarqsN** [comment]
I Have the same issue

**Comment by olajakobson** [comment]
Okay, glad I'm not alone.. 
Just hoping a developer looks into this problem then :)

**Comment by nik-linds** [comment]
Same issue here... :(

**Comment by SweVictor** [comment]
Anyone digged into this more? 

When did it last work? What was updated to make it not work? What specific underlying component failed?

**Comment by nik-linds** [comment]
Trying to install the add-on for the first time, on Home Assistant 2022.3.8, OS 7.6. I've also tried to auto install through the add-on store, was going to try manual install but then noticed this thread...

**Comment by richardsorensson** [comment]
I can confirm, my previous installation stopped working for me, i uninstalled and tried to reinstall with this error.

> Failed to install add-on
> The command '/bin/bash -o pipefail -c apk add --no-cache --virtual .build-dependencies g++ gcc libc-dev linux-headers make python3 bluez eudev-dev && apk add --no-cache git nodejs npm dbus-dev glib-dev && npm config set unsafe-perm true' returned a non-zero code: 2

I've got the latest version of home assistant running.

**Comment by richardsorensson** [comment]
Just committed a PR (https://github.com/icanos/hassio-plejd/pull/236) that seems to fix these build issues with the latest hassio version.

**Comment by SweVictor** [comment]
Those of you who had the issue - please chime in here or in the PR thread if the fix indeed solves the issue. If so, I'll accept the PR into the master branch.

**Comment by mrab95** [comment]
I Have the same issue

**Comment by SweVictor** [comment]
@mrab95 Do try to install @richardsorensson PR branch using the manual install method and please report back if that solves the problem.

**Comment by nik-linds** [comment]
@SweVictor I have done the manual install and yes, it solved the issue for me and I'm up and running with the addon!

**Comment by SweVictor** [comment]
Thanks for reporting back. Closing this after mergin PR to master, will be released as 0.8.1

**Comment by SweVictor** [comment]
New version set to 0.9.0, normal install should work now

**Comment by olajakobson** [comment]
Hi again. Sorry for late reply. FYI - installation now successfully works for me as well (ver 0.9.1). 
Great work and thank you all!! :)
