### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by HAPSagan** [icanos/hassio-plejd#251]
Hi. Apologies if I've searched too badly, but unfortunately I can't get this to work and can't find a clue. I would be grateful if someone could help me find a solution. I am attaching the log file.

Om någon vill kontakta mig via mail eller telefon går det också bra: familjenlindhha@gmail.com +46 70 616 49 61

[Logfil Plejd.txt](https://github.com/icanos/hassio-plejd/files/9705067/Logfil.Plejd.txt)

**Comment by SweVictor** [comment]
Looks like the Plejd API is down (or changed). 404 means not found, let's hope the endpoint is not removed...

Earlier times the Plejd API had been down a day or three, otherwise i don't know

It also says the name of the addon is "plaid", strange. Does it do that for others too? Maybe me too 🙂

**Comment by HAPSagan** [comment]
Ok, so you don’t think I have done something wrong?/Peter

**Comment by HAPSagan** [comment]
Hi. Still no progress for me. Same error in the log. Any suggestions? I will buy you coffee if you solve this. ;-)

**Comment by SweVictor** [comment]
Well... I expect your HA instance and add-ons can reach the internet?

You double checked your credentials?

**Comment by HAPSagan** [comment]
Hi
It was all my mistake! I had misunderstood ""Username". I was stupid enough to enter my username I chose in the Plejd app and not my email address. Sorry! I'll buy you a coffee via the link. :-)
/Peter

**Comment by SweVictor** [comment]
No worries, I've done the same mistake myself. I'll leave this ticket open for now and see if I can improve at least the documentation a bit and hint we actually mean email, not username. Thanks for reporting back.

**Comment by SweVictor** [comment]
Documentation slightly clarified in https://github.com/icanos/hassio-plejd/commit/9561a0586d129b2b646aeda9755c05f5355cee9b, currently in the https://github.com/icanos/hassio-plejd/tree/feature/new-devices-2022-10 branch.
