### ISSUE TITLE
[installation] Repository not showing up in Add-on Store

### ISSUE THREAD

**Issue by magicus** [icanos/hassio-plejd#256]
I'm trying to install the Plejd add-on, and are following the instructions for the add-on store method. I have added `https://github.com/icanos/hassio-plejd`, and it shows up as "Unofficial Plejd Add-on" in the `Manage add-on repositories` dialog. So far, so good. But then I don't see this repository in the list in the main screen. :-( I've tried restarting HA, rebooting the machine, removing and re-adding the repository a few times for good measures, but no effect.

I'm not even sure this is a problem with hassio-plejd; on the surface it sounds like more a HA core issue. But I have another repo added which works fine. My thinking is that perhaps some metadata has changed recently, which makes HA fail to find the Plejd add-on as provided by the Plejd repository. 

I *could* do a manual install, but I'd rather not. And if this is a general problem, I believe you'd want it fixed as much as I do. :-)

I'm using Home Assistant 2022.10.5 (the latest release).

**Comment by magicus** [comment]
I think this might be due to a missing `config.yaml`. See https://developers.home-assistant.io/docs/add-ons/tutorial#i-dont-see-my-add-on. 

For an example, see https://github.com/home-assistant/addons-example/blob/main/example/config.yaml

**Comment by SweVictor** [comment]
I'm closing this since it seems to work without the fix. 

If anyone continues to have issues, feel free to reopen this, comment, or open a new issue referencing this.
