### ISSUE TITLE
HA Configuration failed 

### ISSUE THREAD

**Issue by arnonfarn** [icanos/hassio-plejd#276]
Hello!
I tried re install the plugin, but I must do something wrong in the configuration. I'm running HAOS. 

Can you help me find what I'm doing wrong? It worked in my former hardware but has changed to a better spec server. However bluetooth is working and in the beginning, it looks promising but then it fail. Here's the log:

### redacted ###

Thank you in advance!

**Comment by mathiasbk** [comment]
Are you sure you have configured the correct sitename in the configuration?

Your errorlog says:
 2023-07-16 08:05:54 INF [plejd-api] Got site list response with 1: Elin Sefyrin
2023-07-16 08:05:54 ERR [plejd-api] Failed to find a site named Default Site

**Comment by arnonfarn** [comment]
I don't know how I find the site name?

**Comment by mathiasbk** [comment]
It's the name of your site in the Plejd app.
In your case its probably "Elin Sefyrin"

**Comment by arnonfarn** [comment]
Thanks for taking your time for support. It wasn't a bug, it was a user error from my part.

**Comment by SweVictor** [comment]
Thanks everyone.

Though, for first time users having only one Plejd site, maybe it would make sense to default to that one?

"First" if you have multiple I'm not as sure would be a good idea though.

Thoughts?

**Comment by mathiasbk** [comment]
Making it default to the first site when there is only one site is a good ide.
Probably not necessary where there are more than 1 site, but i am not sure :)

**Comment by arnonfarn** [comment]
> Making it default to the first site when there is only one site is a good ide. Probably not necessary where there are more than 1 site, but i am not sure :)

Is it much work involved, to have a checkbox "Do you have more than 1 sites? Yes/no"

**Comment by SweVictor** [comment]
> > Making it default to the first site when there is only one site is a good ide. Probably not necessary where there are more than 1 site, but i am not sure :)
> 
> Is it much work involved, to have a checkbox "Do you have more than 1 site? Yes/no"

I think we know from the API reply the number of sites and names of them.

**Comment by arnonfarn** [comment]
Could you remove this bug report because it has Personal information in the log? My mistake.

**Comment by SweVictor** [comment]
@arnonfarn redacted the first message - looks good?

**Comment by arnonfarn** [comment]
Almost and a few messages 🙂 I don't know if you can edit others posts?

**Comment by mathiasbk** [comment]
> Almost and a few posts 🙂 I don't know if you can edit other users posts?

I changed my comments. Ok?

**Comment by arnonfarn** [comment]
Well good 

> > Almost and a few posts 🙂 I don't know if you can edit other users posts?
> 
> I changed my comments. Ok?

Good enough 🙂
