### ISSUE TITLE
0.10.0 breaks DAL-01

### ISSUE THREAD

**Issue by telf3** [icanos/hassio-plejd#284]
First of all i'm aware that DAL-01 is _"Not tested, not supported"_. 
However mine was working prior to the 0.10.0 release.

Rolling back to 0.9.1 solves the issue for me.

```
2023-08-24 00:16:58 ERR [plejd-api] Error trying to create output device: Error: Unknown device type with id 12
2023-08-24 00:16:58 WRN [plejd-api] device (from API response) when error happened: {
  "deviceId": "E5701FBB2DD7",
  "siteId": "--redacted--",
  "title": "Ledskenor",
  "traits": 11,
  "hiddenFromRoomList": false,
  "roomId": "--redacted--",
  "createdAt": "2023-08-23T21:08:42.442Z",
  "updatedAt": "2023-08-23T21:09:04.418Z",
  "hiddenFromIntegrations": false,
  "outputType": "LIGHT",
  "ACL": {},
  "objectId": "W0UfFWsqjA",
  "__type": "Object",
  "className": "Device"
}
2023-08-24 00:16:58 WRN [plejd-api] plejdDevice (from API response) when error happened: {
  "deviceId": "E5701FBB2DD7",
  "installer": {
    "__type": "Pointer",
    "className": "_User",
    "objectId": "X270HmEl83"
  },
  "hardwareId": "12",
  "faceplateId": "0",
  "firmware": {
    "notes": "DAL-01",
    "createdAt": "2021-05-18T12:04:03.357Z",
    "updatedAt": "2021-05-19T08:35:11.853Z",
    "data": {
      "__type": "File",
      "name": "4d862e90fa5dc0e683dd0386ac4ef531_application.bin",
      "url": "https://cloud.plejd.com/parse/files/zHtVqXt8k4yFyk2QGmgp48D9xZr2G94xWYnF4dak/4d862e90fa5dc0e683dd0386ac4ef531_application.bin"
    },
    "metaData": {
      "__type": "File",
      "name": "4f0fa6376fac65a82e430c3272898975_application.dat",
      "url": "https://cloud.plejd.com/parse/files/zHtVqXt8k4yFyk2QGmgp48D9xZr2G94xWYnF4dak/4f0fa6376fac65a82e430c3272898975_application.dat"
    },
    "version": "1.1.0",
    "buildTime": 20210510145612,
    "firmwareApi": "5",
    "ACL": {},
    "objectId": "dREAAtC1s4",
    "__type": "Object",
    "className": "Firmware"
  },
  "createdAt": "2022-04-01T13:47:27.701Z",
  "updatedAt": "2023-08-23T21:09:03.262Z",
  "diagnostics": "0F000B002A002A00000000000000",
  "faceplateUpdatedAt": "2023-08-23T21:08:42.398Z",
  "dirtyClock": false,
  "dirtyInstall": false,
  "dirtySettings": false,
  "dirtyUpdate": false,
  "siteId": "--redacted--",
  "coordinates": {
    "__type": "GeoPoint",
    "latitude": --redacted--,
    "longitude": --redacted--
  },E5701FBB2DD7_0
  "predefinedLoad": {
    "loadType": "DALI",
    "createdAt": "2021-03-08T12:08:35.934Z",
    "updatedAt": "2023-06-22T13:59:41.228Z",
    "defaultDimCurve": {
      "__type": "Pointer",
      "className": "DimCurve",
      "objectId": "xGBw2qRHoE"
    },
    "descriptionKey": "DALIDescription",
    "titleKey": "DALITitle",
    "predefinedLoadData": "{\n   \"Order\":1,\n   \"Min\":0,\n   \"Max\":100,\n   \"Start\":0,\n   \"OutputSpeed\":0.1,\n   \"OutputType\":\"LIGHT\",\n   \"BootState\":\"UseLast\",\n   \"UserDefined\":[\n      \"DALIScan\",\n      \"SimpleStart\"\n   ],\n   \"Settings\":[\n      \"SimpleStart\",\n      \"Max\",\n      \"DAPCControl\"\n   ]\n}",
    "allowedDimCurves": {
      "__type": "Relation",
      "className": "DimCurve"
    },
    "ACL": {
      "*": {
        "read": true
      }
    },
    "objectId": "CvNVNVOukZ",
    "__type": "Object",
    "className": "PredefinedLoad"
  },
  "ACL": {},
  "objectId": "sC3XZ7MjJS",
  "__type": "Object",
  "className": "PlejdDevice"
}
```

I'm thinking that this commit is probably the reason for this: 0ed2ad8

**Comment by SweVictor** [comment]
@telf3: Interesting!

Agree with your analysis of what caused the issue. 

We (I) have basically no info on how the DAL-01 works. Could you share some additional info? Anything would be helpful, but specifically:
* How is the Plejd => Dali integration done? (app-wise mostly, but any info would be interesting)
* How many individually controlled devices can be added to the DAL-01?
* How do these show up in the Plejd app? (devices => settings)
* Are Dali devices always lights or could there be other types?

Thanks

**Comment by telf3** [comment]
@SweVictor 
I don't know for sure since my electrician performed the install. But I will do my best to answer.

- I think that the DAL-01 device handles DALI communication to all output devices and inputs are handled like any other Plejd device.  You add the device like any other in the app and get guided through the settings in the screenshots below.
- Mine has 7 devices, but the [documentation](https://brand.plejd.com/downloads/manual/DAL-01/plejd_manual_DAL-01_EN.pdf) specifies up to 64 DALI loads.
- For me, they show up as a single light entity. 
![23-08-24 17-55-39 0751](https://github.com/icanos/hassio-plejd/assets/44555627/062a343b-7b27-428e-8f21-8986c4b2eb73)
![23-08-24 17-55-43 0752](https://github.com/icanos/hassio-plejd/assets/44555627/7467013d-a62f-45cb-b0fe-193e7f7b5ca9)
![23-08-24 17-55-54 0753](https://github.com/icanos/hassio-plejd/assets/44555627/4d9f8a79-850e-4a28-87d7-7f0f8883577f)
- According to the [Plejd documentation](https://brand.plejd.com/downloads/product-sheet/DAL-01/plejd_product_sheet_DAL-01_EN.pdf) it "...is used for broadcast control of drivers and lights". So I interpret this as it only supports lights (and drivers of lights) as output DALI devices.
- Please note that it also supports white temperature adjustment. However my output devices doesn't so I cannot test that. To configure this you set Light source under output to Tunable white.

**Comment by telf3** [comment]
They are treated as one light.

**Comment by SweVictor** [comment]
Great, thanks for the info @telf3 !

I've updated the Develop branch at https://github.com/icanos/hassio-plejd/tree/develop.

Hopefully, this should add "official" support for DAL-01 based on your input. It can be installed using the manual install method in the README.

If you (or anyone else) tests it, please report back if it works/not!

Thanks

**Comment by telf3** [comment]
Thank you for the quick response! @SweVictor  

I just installed the development branch, initially it seems to be working great.
Will let you know if any issues appear.

**Comment by SweVictor** [comment]
Planned for 0.11
