### ISSUE TITLE
Lights detected but cannot control them via HA. Going to unknown / unavailable in MQTT logbook

### ISSUE THREAD

**Issue by slowtraintodawn** [icanos/hassio-plejd#285]
This is a very odd issue that I've been trying to fix for a few days now.

The lights are detected by the Plejd Addon, populated in HA but I cannot control them. If I tap the on/off toggle in HA it turn blue for a few seconds and then goes black again. The lights also go to unknown / unavailable in the MQTT log book. It used to work btw. HEre's what I've tried

BT works OK as I've tried the NUC onboard BT and an ASUS BT400 (I think) adaptor with the same results

MQTT Addon, Plejd addon installed and configured. 
Lights are enumerated (I see that in the plejd addon log

- (2023-09-01 09:48:17 INF [plejd-mqtt] Discovered DIM-02 (light) named Bathroom Switches (14 : D9299917C918_1).
- 2023-09-01 09:48:17 DBG [plejd-mqtt] Sending discovery for Shower Lights

If Ilisten to # on MQTT I see 

- Message 67 received on homeassistant/light/plejd/E45A06F0B745_1/set at 9:49:
{"state":"ON"}

I the Plejd startup log I see 

- Device registry does not contain device with serial D3CD73xxxxxx (which is the Plejd Gateway

I guess the question is "Which Registry"?

Deinstalled / reinstalled many times.

Any ideas???

**Comment by SweVictor** [comment]
The registry is the Plejd api response. Gateways aren't included amongst the devices.

I think we had a very similar issue to this recently, do look back a bit and link it off you find it.

As for how to solve, I would try turning the gateway off and verifying you get a connection to the BLE mesh. If not, move closer to a Plejd device.

**Comment by SweVictor** [comment]
I was probably thinking about this one https://github.com/icanos/hassio-plejd/issues/278

**Comment by slowtraintodawn** [comment]
All working again but..... F f f f <add lots of swearing> 😄 

I'm using the onboard BT adaptor on the NUC which is installed with some of the other hubs etc in a case about 4m from the first Plejy device. Just moved it 2m closer and now everything works again.

I can promise you the thing worked before... Oh well, but thanks.
