### ISSUE TITLE
Startup problem

### ISSUE THREAD

**Issue by Mats1717** [icanos/hassio-plejd#288]
Hi to who this conserns
This fork works for my garage door not opening on restart or power failure.
Please integrate this in this verision.
All other forks get the garage door open in random time due to restart or power failure. Have som lights also and no problem with this fork. Tried the 10 version today and garage door was opend directliccly.

https://github.com/tomjaimz/hassio-plejd
tomjaimz good jobb

**Comment by SweVictor** [comment]
Thanks @Mats1717. The code in the above repository is the same as the PR at https://github.com/icanos/hassio-plejd/pull/268 as far as I can see. Let's continue the discussion there.
