### ISSUE TITLE
Raspberry Pi4 Hassos - Installation exited

### ISSUE THREAD

**Issue by spripe** [icanos/hassio-plejd#32]
I Just bought a raspberry pi 4 to test this addon.

The Raspberry pi 4 image I used is for: Raspberry Pi 4 Model B 32bit (recommended)
https://github.com/home-assistant/hassos/releases/download/3.8/hassos_rpi4-3.8.img.gz

Have tried installation both manual (local addon) and via hassio.
In both cases I was first getting the errors below (hassio log)

20-01-14 09:19:07 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/icanos/hassio-plejd.git repository
20-01-14 09:19:09 INFO (MainThread) [hassio.store] Load add-ons from store: 64 all - 1 new - 0 remove
20-01-14 09:19:17 INFO (MainThread) [hassio.addons] Create Home Assistant add-on data folder /data/addons/data/local_plejd
20-01-14 09:19:17 INFO (SyncWorker_8) [hassio.docker.addon] Start build local/armv7-addon-plejd:0.2.2
20-01-14 09:19:23 ERROR (SyncWorker_8) [hassio.docker.addon] Can't build local/armv7-addon-plejd:0.2.2: The command '/bin/bash -o pipefail -c apk add --no-cache --virtual .build-dependencies g++=8.3.0-r0 gcc=8.3.0-r0 libc-dev=0.7.1-r0 linux-headers=4.19.36-r0 make=4.2.1-r2 python=2.7.16-r1 bluez=5.50-r3 eudev-dev=3.2.8-r0 && apk add --no-cache git nodejs=10.16.3-r0 npm=10.16.3-r0 && npm config set unsafe-perm true' returned a non-zero code: 2

which resulting in that the installation exits.

I tried rebooting the rpi4, and tried installing via repo again. Then I got a new error.

20-01-14 11:10:37 INFO (SyncWorker_19) [hassio.docker.addon] Start build 4cb18a39/armv7-addon-plejd:0.2.2
20-01-14 11:10:37 ERROR (SyncWorker_19) [hassio.docker.addon] Can't build 4cb18a39/armv7-addon-plejd:0.2.2: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:51215->[::1]:53: read: connection refused

Any clue?

**Comment by spripe** [comment]
If I manually run the command above it shows me;

hassio-plejd $ apk add --no-cache --virtual .build-dependencies   g++=8.3.0-r0   gcc=8.3.0-r0   libc-dev=0.7.1-r0   linux-headers=4.19.36-r0   make=4.2.1-r2   python=2.7.16-r1   bluez=5.50-r3   eudev-dev=3.2.8-r0     && apk add --no-cache   git   nodejs=10.16.3-r0   npm=10.16.3-r0     && npm config set unsafe-perm true
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/armv7/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/armv7/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  gcc-9.2.0-r3:
    breaks: .build-dependencies-20200114.112323[gcc=8.3.0-r0]
    satisfies: g++-9.2.0-r3[gcc=9.2.0-r3]
  libc-dev-0.7.2-r0:
    breaks: .build-dependencies-20200114.112323[libc-dev=0.7.1-r0]
    satisfies: g++-9.2.0-r3[libc-dev]
  g++-9.2.0-r3:
    breaks: .build-dependencies-20200114.112323[g++=8.3.0-r0]
  python2-2.7.16-r3:
    breaks: .build-dependencies-20200114.112323[python=2.7.16-r1]
  bluez-5.52-r0:
    breaks: .build-dependencies-20200114.112323[bluez=5.50-r3]
  eudev-dev-3.2.9-r1:
    breaks: .build-dependencies-20200114.112323[eudev-dev=3.2.8-r0]
hassio-plejd $

**Comment by spripe** [comment]
lscpu shows me;
architecture: armv7l

![bild](https://user-images.githubusercontent.com/23295482/72342047-0b5b9100-36cc-11ea-9d21-418441513631.png)

**Comment by spripe** [comment]
build.json file only specifies for these architectures;
    "aarch64": "hassioaddons/base-aarch64:5.0.2",
    "amd64": "hassioaddons/base-amd64:5.0.2",
    "armhf": "hassioaddons/base-armhf:5.0.2",
    "armv7": "hassioaddons/base-armv7:5.0.2",
    "i386": "hassioaddons/base-i386:5.0.2"

Could this be the problem?

**Comment by spripe** [comment]
I've now tried the Raspberry Pi 4 Model B 64bit image, just for testing
https://github.com/home-assistant/hassos/releases/download/3.8/hassos_rpi4-64-3.8.img.gz

Getting the same error with this image
20-01-14 16:33:35 INFO (MainThread) [hassio.homeassistant] Setup Home Assistant
20-01-14 16:33:35 INFO (SyncWorker_7) [hassio.docker.interface] Update image homeassistant/raspberrypi4-64-homeassistant:landingpage to homeassistant/raspberrypi4-64-homeassistant:0.103.6
20-01-14 16:33:35 INFO (SyncWorker_7) [hassio.docker.interface] Pull image homeassistant/raspberrypi4-64-homeassistant tag 0.103.6.
20-01-14 16:36:10 INFO (SyncWorker_7) [hassio.docker.interface] Stop homeassistant application
20-01-14 16:36:24 INFO (SyncWorker_7) [hassio.docker.interface] Clean homeassistant application
20-01-14 16:36:24 INFO (MainThread) [hassio.homeassistant] Home Assistant docker now installed
20-01-14 16:36:24 INFO (MainThread) [hassio.homeassistant] Start Home Assistant
20-01-14 16:36:24 INFO (SyncWorker_8) [hassio.docker.homeassistant] Start homeassistant homeassistant/raspberrypi4-64-homeassistant with version 0.103.6
20-01-14 16:36:44 INFO (MainThread) [hassio.homeassistant] Detect a running Home Assistant instance
20-01-14 16:36:44 INFO (SyncWorker_1) [hassio.docker.interface] Cleanup images: ['homeassistant/raspberrypi4-64-homeassistant:landingpage']
20-01-14 16:39:53 INFO (MainThread) [hassio.store.git] Clone add-on https://github.com/icanos/hassio-plejd.git repository
20-01-14 16:39:55 INFO (MainThread) [hassio.store] Load add-ons from store: 63 all - 1 new - 0 remove
20-01-14 16:40:11 INFO (MainThread) [hassio.addons] Create Home Assistant add-on data folder /data/addons/data/4cb18a39_plejd
20-01-14 16:40:11 INFO (SyncWorker_16) [hassio.docker.addon] Start build 4cb18a39/aarch64-addon-plejd:0.2.2
20-01-14 16:40:30 ERROR (SyncWorker_16) [hassio.docker.addon] Can't build 4cb18a39/aarch64-addon-plejd:0.2.2: The command '/bin/bash -o pipefail -c apk add --no-cache --virtual .build-dependencies   g++=8.3.0-r0   gcc=8.3.0-r0   libc-dev=0.7.1-r0   linux-headers=4.19.36-r0   make=4.2.1-r2   python=2.7.16-r1   bluez=5.50-r3   eudev-dev=3.2.8-r0     && apk add --no-cache   git   nodejs=10.16.3-r0   npm=10.16.3-r0     && npm config set unsafe-perm true' returned a non-zero code: 2

**Comment by icanos** [comment]
Thank you for investigating, please try the new version published 0.2.3. This should have the build error fixed.

**Comment by spripe** [comment]
Thanks, I'll try

**Comment by icanos** [comment]
Fixed in v 0.2.3, closed.
