### ISSUE TITLE
Scene ID always 0

### ISSUE THREAD

**Issue by spripe** [icanos/hassio-plejd#35]
Is it possible to get Scene ID instead of the always 0 value i Scene or Scene name?.
If I push scene Night below message shows.

Meddelande 21 mottaget på plejd/event/scene vid 19:18 
{
    "scene": 0
}
QoS: 0 - Retain: false 

If I then push scene Day it shows
Meddelande 27 mottaget på plejd/event/scene vid 19:22 :
{
    "scene": 0
}

QoS: 0 - Retain: false

**Comment by icanos** [comment]
Yes, that was a bug which is resolved in the new (0.2.5) version published :-)

**Comment by spripe** [comment]
Yep!
Works in 0.2.5.

Just a check.
Is i possible to trigger a SCENE via MQTT?

Day Scene shows:
Meddelande 30 mottaget på plejd/event/scene vid 19:54 :
{
    "scene": 1
}

So for example
Topic: plejd/event/scene
Payload: 
{
    "scene": 1
}

Will Trigger that scene

**Comment by icanos** [comment]
Great! :-)

Currently, unfortunately no. I have that in my backlog to implement support for triggering a scene from HA (MQTT) as well.

**Comment by spripe** [comment]
Perfect, Will have to wait for that then :)
Should I keep this issue open for that or register a new one?

**Comment by icanos** [comment]
We'll close this issue. Feel free to open a new one for the enhancement of scene triggering :-)
