### ISSUE TITLE
Devices not loading after restart of HA

### ISSUE THREAD

**Issue by axlthorell** [icanos/hassio-plejd#4]
After a restart of Home Assistant my devices is not available in the MQTT integration.
If I restart the hassio-plejd add-on the devices are made available in the MQTT integration. 
However, if I try to turn on a light i get  `error: not connected` in the add-on log and lights won't turn on.

After several restarts of the add-on i finally get 
```
[11:45:22] INFO: Starting the Plejd service...
plejd-mqtt: connected to mqtt.
connected to Plejd device with addr d7:a4:4a:9e:c4:0f
plejd: connected via bluetooth.
```
and the lights are able to switch on and off again.

If a light were on when the add-on restarted I have to first turn on and then off the light in HA to make the light controllable by hassio-plejd. Changing the light dim level also seems to work to activate a light that was on when the add-on restarted.

It looks like the status of the lights isn't updated in the MQTT on restart, all are assumed to be off.

**Comment by icanos** [comment]
Could you make sure that your MQTT config looks similar to this:

![image](https://user-images.githubusercontent.com/90194/70617241-7539d400-1c10-11ea-9edb-915cf8754688.png)

The birth_message part is the important one, since that is responsible of notifying the Plejd add-on that Home Assistant has started correctly.

**Comment by icanos** [comment]
Regarding wrong status of the lights, that corrects itself after running a few minutes. Currently, I haven't implemented querying Plejd for the current status on start. That is something I have on my list :-)

**Comment by axlthorell** [comment]
What config are you referring to? I have Mosquitto MQTT add-on with no configuration set up.
My configuration.yaml doesn't have `mqtt:` in it.

This is my hassio-plejd config:

```
{
  "site": "Site",
  "username": "my@email.com",
  "password": "top secret password",
  "mqttBroker": "mqtt://localhost",
  "mqttUsername": "mqtt",
  "mqttPassword": "not so secret password"
}
```

My MQTT config looks like this:

```
{
  "logins": [],
  "anonymous": false,
  "customize": {
    "active": false,
    "folder": "mosquitto"
  },
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "require_certificate": false
}
```

**Comment by icanos** [comment]
Sorry, I wasn't clear. In your configuration.yaml, add that configuration that I posted above. I'll add that to the documentation.

The reason this is needed is that HA needs to notify the Plejd add-on when it has started, so Plejd sends the discovery message.

**Comment by axlthorell** [comment]
Ok good.
I currently have mqtt added on autodiscovery by Hass.io, should I remove that integration?

Is client_id something that I already have or is it anything?
Would this be a correct setup?

```
mqtt:
  broker: localhost
  username: mqtt
  password: !secret mqtt_password
  client_id: mqtt
  discovery: true
  discovery_prefix: homeassistant
  birth_message: 
    topic: 'hass/status'
    payload: 'online'
  will_message: 
    topic: 'hass/status'
    payload: 'offline'
```

**Comment by axlthorell** [comment]
Added above section to my configuration.yaml (and the secret password to secrets.yaml), it works!
After a restart of the add-on it looks as if all lights are loaded automatically. 

Please add this information to the setup instructions.

Is client_id needed? Can I set it to anything?

**Comment by icanos** [comment]
client_id is not needed, if left out, the mqtt client will automatically generate a random ID. Client_id will, however, if specified, need to be unique.

The ID is used to identify each client connected to the MQTT broker.
