### ISSUE TITLE
Scene triggering via MQTT

### ISSUE THREAD

**Issue by spripe** [icanos/hassio-plejd#43]
Hi,

Would love to see enhancement to do scene triggering via MQTT.

**Comment by icanos** [comment]
This will be implemented as soon as the BlueZ implementation is done and published.

**Comment by spripe** [comment]
Any progress regarding implementing scene triggering?

**Comment by icanos** [comment]
Haven't had time to look into this yet. As soon as "all" bugs are ironed out of 0.3.x, I'll look into this :)

**Comment by spripe** [comment]
Any progress or estimate when this feature could be implemented?

**Comment by icanos** [comment]
I'm currently working on it in the feature/scenes branch, shouldn't be too long.

**Comment by icanos** [comment]
How should you be able to trigger a scene, should scenes show up as devices in HA?

**Comment by icanos** [comment]
Resolved in #64
