### ISSUE TITLE
v0.3.1, DBusError: Software caused connection abort

### ISSUE THREAD

**Issue by joadske** [icanos/hassio-plejd#50]
Hi, thanks for the update, 0.3.1

But I cant connect to Plejd mesh.

> plejd-api: got session token response
> plejd-api: getCryptoKey()
> plejd-api: got sites response
> wireEvents()
> plejd-mqtt: connected to mqtt.
> plejd-mqtt: discovered light named Brytare vid altandörr with PID 21.
> plejd-mqtt: discovered light named Taklampa Hobbyrum with PID 25.
> plejd-mqtt: discovered light named Taklampa Kontor with PID 24.
> plejd-mqtt: discovered light named Takbel inglasning with PID 18.
> plejd-mqtt: discovered light named Fasadbel baksidan with PID 19.
> plejd-mqtt: discovered light named Carport with PID 11.
> plejd-mqtt: discovered light named Utebel inglasning  with PID 28.
> plejd-mqtt: discovered switch named Dörr hobbyrum with PID 26.
> plejd-mqtt: discovered light named Hall with PID 15.
> plejd-mqtt: discovered light named Utebel entre with PID 16.
> plejd-mqtt: discovered light named Motorvärmaruttag höger with PID 13.
> plejd-ble: connecting to /org/bluez/hci0/dev_E6_61_EF_8E_68_4B
> onDeviceConnected()
> plejd-ble: error: unable to connect to the Plejd mesh.
> plejd-ble: were unable to connect, will retry connection in 10 seconds.
> plejd-ble: disconnecting /org/bluez/hci0/dev_E6_61_EF_8E_68_4B
> plejd-ble: connecting to /org/bluez/hci0/dev_E6_61_EF_8E_68_4B
> plejd-ble: failed connecting to plejd, error: DBusError: Software caused connection abort
> plejd-ble: connecting to /org/bluez/hci0/dev_C7_27_57_B9_9E_44
> plejd-ble: failed connecting to plejd, error: DBusError: Software caused connection abort
> plejd-ble: connecting to /org/bluez/hci0/dev_FB_CB_50_0C_B8_A5

End after a restart of hassio-plejd
> 
> plejd-api: got session token response
> plejd-api: getCryptoKey()
> plejd-api: got sites response
> wireEvents()
> plejd-mqtt: connected to mqtt.
> plejd-mqtt: discovered light named Brytare vid altandörr with PID 21.
> plejd-mqtt: discovered light named Taklampa Hobbyrum with PID 25.
> plejd-mqtt: discovered light named Taklampa Kontor with PID 24.
> plejd-mqtt: discovered light named Takbel inglasning with PID 18.
> plejd-mqtt: discovered light named Fasadbel baksidan with PID 19.
> plejd-mqtt: discovered light named Carport with PID 11.
> plejd-mqtt: discovered light named Utebel inglasning  with PID 28.
> plejd-mqtt: discovered switch named Dörr hobbyrum with PID 26.
> plejd-mqtt: discovered light named Hall with PID 15.
> plejd-mqtt: discovered light named Utebel entre with PID 16.
> plejd-mqtt: discovered light named Motorvärmaruttag höger with PID 13.
> onDeviceConnected()
> plejd-ble: error: unable to connect to the Plejd mesh.
> plejd-ble: were unable to connect, will retry connection in 10 seconds.
> (node:292) UnhandledPromiseRejectionWarning: DBusError: Operation already in progress
>     at _methodReturnHandlers.(anonymous function) (/plejd/node_modules/dbus-next/lib/bus.js:339:27)
>     at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
>     at EventEmitter.MessageBus.conn.on (/plejd/node_modules/dbus-next/lib/bus.js:147:9)
>     at EventEmitter.emit (events.js:198:13)
>     at /plejd/node_modules/dbus-next/lib/connection.js:112:14
>     at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:55:9)
>     at Socket.emit (events.js:198:13)
>     at emitReadable_ (_stream_readable.js:554:12)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
> (node:292) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:292) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> (node:292) UnhandledPromiseRejectionWarning: DBusError: Operation already in progress
>     at _methodReturnHandlers.(anonymous function) (/plejd/node_modules/dbus-next/lib/bus.js:339:27)
>     at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
>     at EventEmitter.MessageBus.conn.on (/plejd/node_modules/dbus-next/lib/bus.js:147:9)
>     at EventEmitter.emit (events.js:198:13)
>     at /plejd/node_modules/dbus-next/lib/connection.js:112:14
>     at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:55:9)
>     at Socket.emit (events.js:198:13)
>     at emitReadable_ (_stream_readable.js:554:12)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
> (node:292) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by icanos** [comment]
That's troublesome :) does it give you the same exception if you restart once more? Which platform, RPi?

**Comment by joadske** [comment]
Yes, i'm using a RPi3B+
Anything i can do to help?

>  does it give you the same exception

Yes.

This is after a restart:
> plejd-api: got session token response
> plejd-api: getCryptoKey()
> plejd-api: got sites response
> wireEvents()
> plejd-mqtt: connected to mqtt.
> plejd-mqtt: discovered light named Brytare vid altandörr with PID 21.
> plejd-mqtt: discovered light named Taklampa Hobbyrum with PID 25.
> plejd-mqtt: discovered light named Taklampa Kontor with PID 24.
> plejd-mqtt: discovered light named Takbel inglasning with PID 18.
> plejd-mqtt: discovered light named Fasadbel baksidan with PID 19.
> plejd-mqtt: discovered light named Carport with PID 11.
> plejd-mqtt: discovered light named Utebel inglasning  with PID 28.
> plejd-mqtt: discovered switch named Dörr hobbyrum with PID 26.
> plejd-mqtt: discovered light named Hall with PID 15.
> plejd-mqtt: discovered light named Utebel entre with PID 16.
> plejd-mqtt: discovered light named Motorvärmaruttag höger with PID 13.
> onDeviceConnected()
> plejd-ble: error: unable to connect to the Plejd mesh.
> plejd-ble: were unable to connect, will retry connection in 10 seconds.
> (node:291) UnhandledPromiseRejectionWarning: DBusError: Operation already in progress
>     at _methodReturnHandlers.(anonymous function) (/plejd/node_modules/dbus-next/lib/bus.js:339:27)
>     at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
>     at EventEmitter.MessageBus.conn.on (/plejd/node_modules/dbus-next/lib/bus.js:147:9)
>     at EventEmitter.emit (events.js:198:13)
>     at /plejd/node_modules/dbus-next/lib/connection.js:112:14
>     at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:55:9)
>     at Socket.emit (events.js:198:13)
>     at emitReadable_ (_stream_readable.js:554:12)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
> (node:291) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:291) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> (node:291) UnhandledPromiseRejectionWarning: DBusError: Operation already in progress
>     at _methodReturnHandlers.(anonymous function) (/plejd/node_modules/dbus-next/lib/bus.js:339:27)
>     at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
>     at EventEmitter.MessageBus.conn.on (/plejd/node_modules/dbus-next/lib/bus.js:147:9)
>     at EventEmitter.emit (events.js:198:13)
>     at /plejd/node_modules/dbus-next/lib/connection.js:112:14
>     at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:55:9)
>     at Socket.emit (events.js:198:13)
>     at emitReadable_ (_stream_readable.js:554:12)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
> (node:291) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by icanos** [comment]
I'm looking into it as we speak, please join me in Gitter (link in the README) if you'd like realtime help investigating :)

**Comment by icanos** [comment]
Resolved in latest version
