### ISSUE TITLE
No connection to mesh after updating to 0.3.3 (UnhandledPromiseRejectionWarning: DBusError: An AppArmor policy prevents...)

### ISSUE THREAD

**Issue by oskargronqvist** [icanos/hassio-plejd#53]
Hi,

After updating to 0.3.3 I don't think that the add-on successfully connects to the bluetooth mesh anymore.

I get the following error in the log.
`UnhandledPromiseRejectionWarning: DBusError: An AppArmor policy prevents this sender from sending this message to this recipient`

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: Plejd
 Adds support for the Swedish home automation devices from Plejd.
-----------------------------------------------------------
 Add-on version: 0.3.3
 You are running the latest version of this add-on.
parse error: Expected string key before ':' at line 1, column 4
[01:09:00] ERROR: Unknown HTTP error occured
 System:   (amd64 / intel-nuc)
 Home Assistant version: 0.104.3
 Supervisor version: 195
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[01:09:01] INFO: Starting the Plejd service...
[01:09:01] INFO: Verified permissions on startup script
[01:09:01] INFO: Executing startup script
[01:09:02] INFO: Wrote plejd.json
[01:09:02] INFO: Running add-on
starting Plejd add-on v. 0.3.3
plejd-api: login()
plejd-api: logging into Hemma
plejd-api: got session token response
plejd-api: getCryptoKey()
plejd-api: got sites response
wireEvents()
(node:291) UnhandledPromiseRejectionWarning: DBusError: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender="(null)" (inactive) interface="org.freedesktop.DBus" member="Hello" error name="(unset)" requested_reply="0" destination="org.freedesktop.DBus" (bus)
    at _methodReturnHandlers.(anonymous function) (/plejd/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.MessageBus.conn.on (/plejd/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:198:13)
    at /plejd/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:55:9)
    at Socket.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:554:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:291) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:291) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
plejd-mqtt: connected to mqtt.
plejd-mqtt: discovered light named Ute with PID 34.
plejd-mqtt: discovered light named Matplats with PID 19.
plejd-mqtt: discovered light named Kök taklampor with PID 20.
plejd-mqtt: discovered light named Allrum övervåning with PID 27.
plejd-mqtt: discovered light named Under skåp with PID 21.
plejd-mqtt: discovered light named Köksö with PID 22.
plejd-mqtt: discovered light named Badrum nere with PID 24.
plejd-mqtt: discovered light named Entré with PID 16.
plejd-mqtt: discovered light named Vardagsrum mitten with PID 11.
plejd-mqtt: discovered light named Badrum övervåning with PID 30.
plejd-mqtt: discovered light named Trappa with PID 25.
plejd-mqtt: discovered light named Sovrummet with PID 31.
plejd-mqtt: discovered light named Viggos rum with PID 29.
plejd-mqtt: discovered light named Hall övervåning with PID 28.
plejd-mqtt: discovered light named Vardagsrum Matbord with PID 12.
plejd-mqtt: discovered light named Vardagsrum Soffa with PID 13.
plejd-mqtt: discovered light named Ute takterrass with PID 32.
plejd-mqtt: discovered light named Hall with PID 15.
plejd-mqtt: discovered light named Gästrum with PID 33.
```

**Comment by icanos** [comment]
That’s interesting, which platform are you running on?

**Comment by oskargronqvist** [comment]
Intel NUC. On "a generic Linux". Not Hass OS.

**Comment by icanos** [comment]
Ah, then I understand. Should probably provide an app armor policy for those scenarios but if running it manually, you need to allow DBus access in an AppArmor policy

**Comment by icanos** [comment]
Do you still run it in a Docker container?

**Comment by oskargronqvist** [comment]
Yes. (I think) I've git the same docker setup as when running Hass OS. One docker container running the hassio_supervisor, one hassio_dns, one running homeassistant and one for each addon.

**Comment by icanos** [comment]
Just to clearify, the container is still created using the Add-on Store in the Hass.io menu in Home Assistant or do you manually create it?

**Comment by oskargronqvist** [comment]
Yes. It is created using the add-on store in the hass.io menu in home assistant.

**Comment by icanos** [comment]
Then it seems like you're missing some custom AppArmor configurations done by Hass OS, not sure what kind of configurations are done by the Home Assistant team in order for it to work. But the error you're experiencing are due to some AppArmor policies not being applied to your Hass.io installation unfortunately.

**Comment by oskargronqvist** [comment]
Ok. Then I'll check my installation and see what I can find out.

I've installed it following this instruction:
https://www.home-assistant.io/hassio/installation/#alternative-install-on-a-generic-linux-host

It will run a script to import this apparmor configuration:
https://version.home-assistant.io/apparmor.txt

**Comment by icanos** [comment]
You could try to edit the config.json file and add `"apparmor": "no"` and then manually install the add-on from your sources. That should disable AppArmor for the Plejd container.

**Comment by claeshellgren** [comment]
> 
> 
> You could try to edit the config.json file and add `"apparmor": "no"` and then manually install the add-on from your sources. That should disable AppArmor for the Plejd container.
> 
> That way we can try to pin down the issue and see if its something I've missed or if the Home Assistant documentation is incomplete somehow.
> 
> Reference:
> https://developers.home-assistant.io/docs/en/hassio_addon_config.html

I had the same problem with 0.3.x, tried to disable AppArmor as you suggested, it worked...

**Comment by robertostlund** [comment]
> > You could try to edit the config.json file and add `"apparmor": "no"` and then manually install the add-on from your sources. That should disable AppArmor for the Plejd container.
> > That way we can try to pin down the issue and see if its something I've missed or if the Home Assistant documentation is incomplete somehow.
> > Reference:
> > https://developers.home-assistant.io/docs/en/hassio_addon_config.html
> 
> I had the same problem with 0.3.x, tried to disable AppArmor as you suggested, it worked...

I have the same issues with AppArmor. What did you do to fix it?

**Comment by atrampare** [comment]
I also had the apparmor error but after i edited the config.json file and added "apparmor": "no" and then manually install the add-on the error dissapeard.

But i got a new error instead.


**Log**
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: Plejd
 Adds support for the Swedish home automation devices from Plejd.
-----------------------------------------------------------
 Add-on version: 0.3.5
 You are running the latest version of this add-on.
parse error: Expected string key before ':' at line 1, column 4
[18:54:15] ERROR: Unknown HTTP error occured
 System:   (amd64 / qemux86-64)
 Home Assistant version: 0.105.3
 Supervisor version: 201
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[18:54:15] INFO: Starting the Plejd service...
[18:54:15] INFO: Verified permissions on startup script
[18:54:15] INFO: Executing startup script
[18:54:16] INFO: Wrote plejd.json
[18:54:16] INFO: Running add-on
starting Plejd add-on v. 0.3.5
plejd-api: login()
plejd-api: logging into vik21
plejd-api: got session token response
plejd-api: getCryptoKey()
plejd-api: got sites response
wireEvents()
init()
plejd-mqtt: connected to mqtt.
plejd-mqtt: discovered light named Spottar Hall Uppe with PID 45.
plejd-mqtt: discovered light named Spottar Hall Nere with PID 32.
onDeviceConnected()
plejd-ble: warning: wasn't able to connect to Plejd, will retry.
plejd-ble: were unable to connect, will retry connection in 10 seconds.

I have home assistant installed on a nuc with ubuntu server and docker.
Anyone know what might cause this error?

**Comment by icanos** [comment]
I've seen that error on occasion but after a restart of the addon it worked again. Haven't investigated that much yet :)

**Comment by icanos** [comment]
If this continues to be an issue, please reopen. Thanks! :)
