### ISSUE TITLE
plejd-ble: failed connecting to plejd, error: DBusError: Software caused connection abort

### ISSUE THREAD

**Issue by hm-flixtech** [icanos/hassio-plejd#54]
Hello!
Thanks for this addon!

I have problem connecting to plejd.
Running on Raspberry PI 3B+ with HASSIO.

After start:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Plejd
 Adds support for the Swedish home automation devices from Plejd.
-----------------------------------------------------------
 Add-on version: 0.3.3
 You are running the latest version of this add-on.
parse error: Expected string key before ':' at line 1, column 4
[10:10:35] ERROR: Unknown HTTP error occured
 System:   (armv7 / raspberrypi3)
 Home Assistant version: 0.104.3
 Supervisor version: 195
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[10:10:40] INFO: Starting the Plejd service...
[10:10:40] INFO: Verified permissions on startup script
[10:10:40] INFO: Executing startup script
[10:10:44] INFO: Wrote plejd.json
[10:10:44] INFO: Running add-on
starting Plejd add-on v. 0.3.3
plejd-api: login()
plejd-api: logging into xxxx
plejd-api: got session token response
plejd-api: getCryptoKey()
plejd-api: got sites response
wireEvents()
plejd-mqtt: connected to mqtt.
plejd-mqtt: discovered light named Ute Garage with PID 25.
plejd-mqtt: discovered light named Ute Loge & Garage with PID 26.
plejd-mqtt: discovered light named Ute Entré with PID 16.
plejd-mqtt: discovered light named Kök Tak with PID 32.
plejd-mqtt: discovered light named Köksö with PID 33.
plejd-mqtt: discovered light named Hall Fönster with PID 37.
plejd-mqtt: discovered light named Hall Tak with PID 36.
plejd-mqtt: discovered light named Matplats Tak with PID 39.
plejd-mqtt: discovered light named Matplats Bord with PID 40.
plejd-mqtt: discovered light named Sagasrum Fönster with PID 21.
plejd-mqtt: discovered light named Sagasrum Tak with PID 20.
plejd-mqtt: discovered light named Vardagsrum Fönster with PID 24.
plejd-mqtt: discovered light named Vardagsrum Tak with PID 23.
plejd-mqtt: discovered light named Ute Dörr sovrum with PID 28.
plejd-mqtt: discovered light named Sovrum Fönsternich with PID 29.
plejd-mqtt: discovered light named Sovrum Fönster with PID 30.
plejd-mqtt: discovered light named Sovrum Tak with PID 31.
plejd-mqtt: discovered light named Ute Uterum with PID 12.
plejd-mqtt: discovered light named Ute Källartrapp with PID 34.
plejd-ble: connecting to /org/bluez/hci0/dev_C7_DD_8A_36_20_E7
plejd-ble: failed connecting to plejd, error: DBusError: Software caused connection abort
plejd-ble: connecting to /org/bluez/hci0/dev_E8_1C_EF_C7_8F_07
plejd-ble: failed connecting to plejd, error: DBusError: Software caused connection abort
plejd-ble: connecting to /org/bluez/hci0/dev_F9_56_06_FF_82_D4
plejd-ble: failed connecting to plejd, error: DBusError: Software caused connection abort
plejd-ble: connecting to /org/bluez/hci0/dev_E5_B2_65_80_FF_3D
plejd-ble: failed connecting to plejd, error: DBusError: Software caused connection abort
plejd-ble: connecting to /org/bluez/hci0/dev_DB_DE_56_EB_EF_BF
plejd-ble: failed connecting to plejd, error: DBusError: Software caused connection abort
plejd-ble: connecting to /org/bluez/hci0/dev_F7_76_B1_C3_2A_03
plejd-ble: failed connecting to plejd, error: DBusError: Software caused connection abort
plejd-ble: connecting to /org/bluez/hci0/dev_D3_C7_AA_CF_DD_21
plejd-ble: failed connecting to plejd, error: DBusError: Software caused connection abort
plejd-ble: connecting to /org/bluez/hci0/dev_D3_09_9B_BC_4A_54
plejd-ble: failed connecting to plejd, error: TypeError: Cannot read property 'Connect' of undefined
plejd-ble: connecting to /org/bluez/hci0/dev_FA_D9_BC_F7_32_BA
plejd-ble: failed connecting to plejd, error: TypeError: Cannot read property 'Connect' of undefined
plejd-ble: connecting to /org/bluez/hci0/dev_FD_98_D4_53_77_06
plejd-ble: failed connecting to plejd, error: TypeError: Cannot read property 'Connect' of undefined
plejd-ble: connecting to /org/bluez/hci0/dev_C1_0F_E3_56_EF_BF
plejd-ble: failed connecting to plejd, error: TypeError: Cannot read property 'Connect' of undefined
onDeviceConnected()
plejd-ble: error: unable to connect to the Plejd mesh.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
plejd-ble: connecting to /org/bluez/hci0/dev_C7_DD_8A_36_20_E7
onDeviceConnected()
trying 10 characteristics
authenticate()
```

After restart:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Plejd
 Adds support for the Swedish home automation devices from Plejd.
-----------------------------------------------------------
 Add-on version: 0.3.3
 You are running the latest version of this add-on.
parse error: Expected string key before ':' at line 1, column 4
[11:12:58] ERROR: Unknown HTTP error occured
 System:   (armv7 / raspberrypi3)
 Home Assistant version: 0.104.3
 Supervisor version: 195
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[11:13:00] INFO: Starting the Plejd service...
[11:13:00] INFO: Verified permissions on startup script
[11:13:00] INFO: Executing startup script
[11:13:02] INFO: Wrote plejd.json
[11:13:02] INFO: Running add-on
starting Plejd add-on v. 0.3.3
plejd-api: login()
plejd-api: logging into xxxxx
plejd-api: got session token response
plejd-api: getCryptoKey()
plejd-api: got sites response
wireEvents()
plejd-mqtt: connected to mqtt.
plejd-mqtt: discovered light named Ute Garage with PID 25.
plejd-mqtt: discovered light named Ute Loge & Garage with PID 26.
plejd-mqtt: discovered light named Ute Entré with PID 16.
plejd-mqtt: discovered light named Kök Tak with PID 32.
plejd-mqtt: discovered light named Köksö with PID 33.
plejd-mqtt: discovered light named Hall Fönster with PID 37.
plejd-mqtt: discovered light named Hall Tak with PID 36.
plejd-mqtt: discovered light named Matplats Tak with PID 39.
plejd-mqtt: discovered light named Matplats Bord with PID 40.
plejd-mqtt: discovered light named Sagasrum Fönster with PID 21.
plejd-mqtt: discovered light named Sagasrum Tak with PID 20.
plejd-mqtt: discovered light named Vardagsrum Fönster with PID 24.
plejd-mqtt: discovered light named Vardagsrum Tak with PID 23.
plejd-mqtt: discovered light named Ute Dörr sovrum with PID 28.
plejd-mqtt: discovered light named Sovrum Fönsternich with PID 29.
plejd-mqtt: discovered light named Sovrum Fönster with PID 30.
plejd-mqtt: discovered light named Sovrum Tak with PID 31.
plejd-mqtt: discovered light named Ute Uterum with PID 12.
plejd-mqtt: discovered light named Ute Källartrapp with PID 34.
(node:292) UnhandledPromiseRejectionWarning: DBusError: Operation already in progress
    at _methodReturnHandlers.(anonymous function) (/plejd/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.MessageBus.conn.on (/plejd/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:198:13)
    at /plejd/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:55:9)
    at Socket.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:554:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:292) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:292) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by icanos** [comment]
I'll refactor the logging a bit to not give you errors, since DBus needs retries sometimes. If you let the add-on run for a minute or two, the connection should establish successfully despite the errors you're experiencing.

**Comment by hm-flixtech** [comment]
Unfortunately not. Tried the whole weekend.

`plejd-ble: were unable to connect, will retry connection in 10 seconds.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
onDeviceConnected()
plejd-ble: error: unable to enumerate characteristics.
plejd-ble: were unable to connect, will retry connection in 10 seconds.`

**Comment by icanos** [comment]
Did you restart the RPi between or just the add-on? I've heard that DBus doesn't seem play nicely with the 3B+. It might be that the timeouts aren't long enough for 3B+ to work properly.

I'll add some configuration to the settings and we'll have another try at it :-)

**Comment by hm-flixtech** [comment]
The first log in my first message and the log in my second message is after reboot of the PI, the second log in the first message is after restart of the plejd addon.

Thanks!

**Comment by hm-flixtech** [comment]
It is the node-red addon that is making the problem. If i stop node-red, plejd works. I don't use any BLE in my node red program.

**Comment by icanos** [comment]
Not completely sure why and how to resolve it. If anyone has any input, I would very much appreciate it :)

**Comment by hm-flixtech** [comment]
I think we can close this issue. I uninstalled node-red and installed it again, then everything worked prefect!
Thanks for your help!
Grate addon!!!
