### ISSUE TITLE
Plejd plugin installation fail

### ISSUE THREAD

**Issue by ri4man78** [icanos/hassio-plejd#60]
Clean installed HA 105.2. Plejd plugin failed to install. Prior 105.2 had no problems at all.
What's the problem?
Anyone having the same problem?
Thanks.

20-02-08 14:33:03 ERROR (SyncWorker_9) [hassio.docker.addon] Can't build 4cb18a39/aarch64-addon-plejd:0.3.4: The command '/bin/bash -o pipefail -c apk add --no-cache --virtual .build-dependencies   g++=8.3.0-r0   gcc=8.3.0-r0   libc-dev=0.7.1-r0   linux-headers=4.19.36-r0   make=4.2.1-r2   python=2.7.16-r2   bluez=5.50-r3   eudev-dev=3.2.8-r0     && apk add --no-cache   git   nodejs=10.16.3-r0   npm=10.16.3-r0   dbus-dev   glib-dev     && npm config set unsafe-perm true' returned a non-zero code: 2

**Comment by Kemo90** [comment]
Same here :/

**Comment by mattues** [comment]
and here

**Comment by icanos** [comment]
I will have a look at the build, I'll get back once I've checked it out.

**Comment by icanos** [comment]
This should be resolved with the latest version, please try that.

**Comment by kazmur** [comment]
> This should be resolved with the latest version, please try that.

Just tried on a Raspberry Pi 4 B. Works fine to install 0.3.5. Thanks!

**Comment by icanos** [comment]
Perfect, thanks for testing it out :-) closing as fixed
