### ISSUE TITLE
Reverse transition: revisit

### ISSUE THREAD

**Issue by f00dagi** [icanos/hassio-plejd#68]
Hi icanos

I was not able to reopen my previous ticket so I created a new one.

I have upgraded to 0.4.1 and was under the impression that the reverse transition bug was solved in this revision. After some testing I experience the same behavior as described below.

Thanks for taking some time to look into this bug once again, am I doing something wrong here?

The transition to make a light source brighter from lets say 10 to 254 over 20 seconds works fine...

entity_id: light.lounge_tak
brightness: 254
transition: 20
...but going in the other direction from 254 to 10 over 20 seconds results in a direct jump to 10.

entity_id: light.lounge_tak
brightness: 10
transition: 20
Also if the light source is already at brightness 100 and should with transition move to 254 it seems to start at lowest brightness before moving to 254 while the expected behavior would be starting at 100 and move to 254.

I have tested this with an IKEA trådfri light source and that works fine.

Thanks again for your efforts!

-Daniel

**Comment by f00dagi** [comment]
Hi Icanos

I am kind of stuck in my fine tuning of my home automation lights since I dont have transition fully supported. If you can find some time I would really appreciare if you could take a look at this bug.

Thanks!

**Comment by icanos** [comment]
I will take a look at this asap.

**Comment by f00dagi** [comment]
Hi Icanos

I bought you three more coffees to encourage you to take a look at this feature. I hope you can find some time. I am really eager to continue my development based on this functionality.

Thanks.

**Comment by f00dagi** [comment]
Hi again, I don't want to nag you about this feature but I would appreciate if you could let me know whether you will support this or not in the future. If you will not I will of course accept that since I know you are doing this as a hobby project. Then I simply need to find some other type of solution. If you are I am happy to wait for you implementation. Thanks.

**Comment by icanos** [comment]
Sorry for not getting back to you. I’ll look into it asap! Give me a few days :)

**Comment by f00dagi** [comment]
Great, thanks! I am looking forward to it and is more than willing to evaluate any updates that you will release.

**Comment by icanos** [comment]
Could you please try the new version and get back to me? Also attach the log if it doesn't work correctly.

Bear in mind that it takes a few minutes on initial startup for the plugin to know the state in which each Plejd device is. So if you're trying to quickly, it will default to a state of 250 (of maximum 255) when transitioning to off.

**Comment by f00dagi** [comment]
I still see 0.4.6 as the latest version in the HA interface. Does it usually take some time to see a new update?

Have you had time to look at this? This bug is the rea

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by f00dagi** [comment]
Wow! Beautiful! It works perfectly, thanks alot for your effort, this will keep me busy for some time.

**Comment by f00dagi** [comment]
Wow! Beautiful! It works perfectly, thanks alot for your effort, this will keep me busy for some time.

**Comment by f00dagi** [comment]
Hi Icanos

Sorry to tell you but the behavior is back to exactly the same (incorrect) state as described in the original bug report. I will not repeat the characteristics again since it is well described.

Hope you find some time to implement brightness: and transition: to align with other light sources (such as IKEA), I use it alot. Thanks for you efforts.

I am on Home Assistant: 0.115.2 and Plejd: 0.4.7.

**Comment by f00dagi** [comment]
Hi, you made updates to support this but with updates it seems the feature has dissapeared again.

Hope you can find some time to look into it. Thanks!

**Comment by icanos** [comment]
That's unfortunate. I'll try to find out what I accidentally removed and put it back :)

**Comment by f00dagi** [comment]
Great, I am happy to evaluate any updates you might release.

**Comment by f00dagi** [comment]
Friendly reminder, user christmas gift? :D

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SweVictor** [comment]
Can confirm transitions does not work as expected
* Repeatedly calling {turnOn, transition = 5, brightness = 255} will always transition from "0" (low) => 255 even if the light is set to the correct level before. HA seems to know the initial level correctly
* TurnOff works the same way (lights that are off turns on and then fades down)
* Fading down is quite choppy, especially visible for longer transition duration (not sure if this is fixable, just noting)
