### ISSUE TITLE
plejd-ble: warning: wasn't able to connect to Plejd, will retry.

### ISSUE THREAD

**Issue by atrampare** [icanos/hassio-plejd#69]
Hi,

I got a new install on a Nuc installed with ubuntu server and home assistant in a docker.

It seams to connect and i get all the lights to show up in the log but i get a error plejd-ble: warning: wasn't able to connect to Plejd, will retry.

Is ther any other that got the addon working on a nuc with ubuntu server?

Log
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: Plejd
 Adds support for the Swedish home automation devices from Plejd.
-----------------------------------------------------------
 Add-on version: 0.4.2
 You are running the latest version of this add-on.
parse error: Expected string key before ':' at line 1, column 4
[18:37:55] ERROR: Unknown HTTP error occured
 System:   (amd64 / qemux86-64)
 Home Assistant version: 0.105.3
 Supervisor version: 207
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[18:37:55] INFO: Starting the Plejd service...
[18:37:55] INFO: Verified permissions on startup script
[18:37:55] INFO: Executing startup script
[18:37:56] INFO: Wrote plejd.json
[18:37:56] INFO: Running add-on
starting Plejd add-on v. 0.4.2
plejd-api: login()
plejd-api: logging into vik21
plejd-api: got session token response
plejd-api: getCryptoKey()
plejd-api: got sites response
wireEvents()
init()
plejd-mqtt: connected to mqtt.
plejd-mqtt: discovered light (DIM-01) named Spottar Hall Uppe with PID 45.
plejd-mqtt: discovered light (DIM-01) named Spottar Hall Nere with PID 32.
onDeviceConnected()
plejd-ble: warning: wasn't able to connect to Plejd, will retry.
plejd-ble: were unable to connect, will retry connection in 10 seconds.

**Comment by icanos** [comment]
Did you get it to work? Sometimes it need a couple of retries to connect.

**Comment by atrampare** [comment]
Hi,
Been busy but i have restarted the addon several times but the error still there.

Today when i gave it a try i got a new error. It seams to complain about unable to retrieve the crypto key. I tried changing the plejd password but that didn't solve it. 
No other changes have been made since the previous error.

Log
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: Plejd
 Adds support for the Swedish home automation devices from Plejd.
-----------------------------------------------------------
 Add-on version: 0.4.2
 You are running the latest version of this add-on.
parse error: Expected string key before ':' at line 1, column 4
[22:13:37] ERROR: Unknown HTTP error occured
 System:   (amd64 / qemux86-64)
 Home Assistant version: 0.105.3
 Supervisor version: 209
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[22:13:38] INFO: Starting the Plejd service...
[22:13:38] INFO: Verified permissions on startup script
[22:13:38] INFO: Executing startup script
[22:13:39] INFO: Wrote plejd.json
[22:13:39] INFO: Running add-on
starting Plejd add-on v. 0.4.2
plejd-api: login()
plejd-api: logging into vik21
plejd-api: got session token response
plejd-api: getCryptoKey()
error: unable to retrieve the crypto key. error: Error: Request failed with status code 400
(node:290) UnhandledPromiseRejectionWarning: unable to retrieve the crypto key. error: Error: Request failed with status code 400
(node:290) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:290) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[22:13:40] INFO: Starting the Plejd service...
[22:13:40] INFO: Verified permissions on startup script
[22:13:40] INFO: Executing startup script
[22:13:40] INFO: Wrote plejd.json
[22:13:40] INFO: Running add-on

**Comment by icanos** [comment]
Please try again with the latest version, Plejd made some updates to the API which probably rolled out over time to people.

**Comment by atrampare** [comment]
Hi,

Did a reinstall och home assistant. Installed it directly without Ubuntu server.
Running the latest version but i got this in my log now.

Thanks for the help. 

Log
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Plejd
 Adds support for the Swedish home automation devices from Plejd.
-----------------------------------------------------------
 Add-on version: 0.4.3
 You are running the latest version of this add-on.
parse error: Expected string key before ':' at line 1, column 4
[21:21:06] ERROR: Unknown HTTP error occured
 System:   (amd64 / intel-nuc)
 Home Assistant version: 0.106.6
 Supervisor version: 209
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[21:21:06] INFO: Starting the Plejd service...
[21:21:06] INFO: Verified permissions on startup script
[21:21:06] INFO: Executing startup script
[21:21:07] INFO: Wrote plejd.json
[21:21:07] INFO: Running add-on
starting Plejd add-on v. 0.4.3
plejd-api: login()
plejd-api: logging into vik21
plejd-api: got session token response
plejd-api: getSites()
plejd-api: got site list response
plejd-api: getSites()
plejd-api: got site details response
wireEvents()
init()
plejd-mqtt: connected to mqtt.
plejd-mqtt: discovered light (DIM-01) named Spottar Hall Uppe with PID 45.
plejd-mqtt: discovered light (DIM-01) named Spottar Hall Nere with PID 32.
plejd-ble: disconnecting /org/bluez/hci0/dev_FE_3D_89_1A_D4_13
plejd-ble: connecting to /org/bluez/hci0/dev_FE_3D_89_1A_D4_13
onDeviceConnected()
trying 10 characteristics
authenticate()
startPing()
startWriteQueue()
uh oh, no Plejd device.
uh oh, no Plejd device.
uh oh, no Plejd device.
uh oh, no Plejd device.
uh oh, no Plejd device.

**Comment by atrampare** [comment]
Got it working after last update.

**Comment by atrampare** [comment]
Got it working after last update.
