### ISSUE TITLE
No devices added

### ISSUE THREAD

**Issue by fabianpk** [icanos/hassio-plejd#70]
Hello,
 I've been running home assistant core (as it's now known) for a few years, and switched to hass.io to try this addon out as I really want plejd to work with home assistant. I installed it OK, and I have no apparent error messages (one warning though), but the lights aren't published to home assistant. It did get published the first time, but I couldn't turn off or on the lights. After that I restarted hass.io and then they were listed as "unavailable" and the scenes disapeared. Then I tried deleting them (as they were unavailable), removing the addon and re-installing it, to try a clean slate. But now no plejd entities shows up under "Developer Tools/States" or under "Overview". My hass.io is a clean install except for mosquitto and the configuration.yaml webfile editor. 
Is the 'UnhandledPromiseRejectionWarning' relevant? What can I do about it?

My configuration.yaml:

> mqtt:
>
>  broker: mqtt://192.168.1.22
>  username: <mymqttusername>
>  password: <password>
>  discovery: true
>  discovery_prefix: homeassistant
>  birth_message: 
>    topic: 'hass/status'
>    payload: 'online'
>  will_message: 
>    topic: 'hass/status'
>    payload: 'offline'

  Below is my logfile from hassio-plejd:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: Plejd
 Adds support for the Swedish home automation devices from Plejd.
-----------------------------------------------------------
 Add-on version: 0.4.2
 You are running the latest version of this add-on.
parse error: Expected string key before ':' at line 1, column 4
[20:19:00] ERROR: Unknown HTTP error occured
 System:   (amd64 / qemux86-64)
 Home Assistant version: 0.106.5
 Supervisor version: 207
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[20:19:01] INFO: Starting the Plejd service...
[20:19:01] INFO: Verified permissions on startup script
[20:19:01] INFO: Executing startup script
[20:19:01] INFO: Wrote plejd.json
[20:19:01] INFO: Running add-on
starting Plejd add-on v. 0.4.2
plejd-api: login()
plejd-api: logging into Algot
plejd-api: got session token response
plejd-api: getCryptoKey()
plejd-api: got sites response
wireEvents()
init()
(node:291) UnhandledPromiseRejectionWarning: DBusError: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender="(null)" (inactive) interface="org.freedesktop.DBus" member="Hello" error name="(unset)" requested_reply="0" destination="org.freedesktop.DBus" (bus)
    at _methodReturnHandlers.(anonymous function) (/plejd/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.MessageBus.conn.on (/plejd/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:198:13)
    at /plejd/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:555:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:291) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:291) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
plejd-mqtt: connected to mqtt.
plejd-mqtt: discovered light (DIM-01) named TrappaLampUtgång with PID 12.
plejd-mqtt: discovered light (DIM-01) named Trappa with PID 11.
plejd-mqtt: discovered light (DIM-01) named TrappaVidSkåp with PID 14.
plejd-mqtt: discovered switch (Scene) named Tänd with PID 1.
plejd-mqtt: discovered switch (Scene) named Släck with PID 2.
plejd-mqtt: connected to mqtt.
plejd-mqtt: discovered light (DIM-01) named TrappaLampUtgång with PID 12.
plejd-mqtt: discovered light (DIM-01) named Trappa with PID 11.
plejd-mqtt: discovered light (DIM-01) named TrappaVidSkåp with PID 14.
plejd-mqtt: discovered switch (Scene) named Tänd with PID 1.
plejd-mqtt: discovered switch (Scene) named Släck with PID 2.

**Comment by icanos** [comment]
Yes, the error you're receiving (or warning) indicates that there's something missing with your AppArmor policies. Have you manually installed Hass.io on hardware other that RPi? In that case, you might need to turn off AppArmor in the config.json file.

**Comment by f0xenSWE** [comment]
I get the exact same issue, have already updated my config.json as follows: 

"host_dbus": true,
"apparmor": "no",

Restarted both addon and Hass.io but the problem persists. 
Im running Hass.io in docker.

**Comment by icanos** [comment]
You need to rebuild the addon after that is added

**Comment by f0xenSWE** [comment]
Thank you for the quick reply. 
Unfortunately the same issue persists. 

"apparmor": "no", is still in the config.json file, addon rebuilt but I still get the exact same error.

**Comment by fabianpk** [comment]
Thank you so much for your help. I have installed it on a linux machine with Ubuntu, yes. I modified the config.json file in:
/usr/share/hassio/addons/git/4cb18a39/plejd/config.json

and added the line (I noticed this was in the readme, sorry). I stopped the plejd addon, and issued the rebuild command. It seems to have been rebuilt, by looking in supervisor logs:

20-03-06 20:50:46 INFO (SyncWorker_9) [supervisor.docker.addon] Start build 4cb18a39/amd64-addon-plejd:0.4.2
20-03-06 20:51:42 INFO (SyncWorker_9) [supervisor.docker.addon] Build 4cb18a39/amd64-addon-plejd:0.4.2 done
20-03-06 20:51:42 INFO (MainThread) [supervisor.addons] Add-on '4cb18a39_plejd' successfully rebuilt

Then I restarted Homeassistant. It didn't work (it didn't create any new lights). So I deleted the docker image, reinstalled the whole thing, changed the config.json, rebuilt the addon, and started it for the first time with the apparmor "no" line. Now it creates the plejd lights, but I can't lit them, and it still gives me the same error message:

init()
(node:290) UnhandledPromiseRejectionWarning: DBusError: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender="(null)" (inactive) interface="org.freedesktop.DBus" member="Hello" error name="(unset)" requested_reply="0" destination="org.freedesktop.DBus" (bus)
    at _methodReturnHandlers.(anonymous function) (/plejd/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.MessageBus.conn.on (/plejd/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:198:13)
    at /plejd/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:555:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:290) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:290) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
plejd-mqtt: connected to mqtt.
plejd-mqtt: discovered light (DIM-01) named TrappaLampUtgång with PID 12.
plejd-mqtt: discovered light (DIM-01) named Trappa with PID 11.
plejd-mqtt: discovered light (DIM-01) named TrappaVidSkåp with PID 14.
plejd-mqtt: discovered switch (Scene) named Tänd with PID 1.
plejd-mqtt: discovered switch (Scene) named Släck with PID 2.
triggering scene with ID 1
triggering scene with ID 2

I also tried rebooting my machine, and did a dist-upgrade to ensure there was no other missing updates to the system.

**Comment by icanos** [comment]
It looks like AppArmor is still enabled and thus the ‘no’ thing in the config hasn’t taken effect. Not sure if somethings changed in newer HA versions or not.

**Comment by fabianpk** [comment]
Thanks again. Ok, I noticed that all other entries were listed as false/true and not “no”. So I changed to false, and I also found another file, /use/share/hassio/addons.json

When I changed that file in the same manner, it started working!

**Comment by icanos** [comment]
Perfect, closing this as resolved :-)
