### ISSUE TITLE
Cant install v 0.4.4

### ISSUE THREAD

**Issue by Kemo90** [icanos/hassio-plejd#77]
Hello, tried to update to v 0.4.4 but ut didnt work. Then i uninstalled it, at now when i try to install the latest version it says : failed to install addon, unknown error, see logs

And the logs says; 
20-03-24 17:48:54 ERROR (SyncWorker_15) [supervisor.docker.addon] Can't build 4cb18a39/armv7-addon-plejd:0.4.4: The command '/bin/bash -o pipefail -c apk add --no-cache --virtual .build-dependencies   g++=8.3.0-r0   gcc=8.3.0-r0   libc-dev=0.7.1-r0   linux-headers=4.19.36-r0   make=4.2.1-r2   python=2.7.16-r2   bluez=5.50-r3   eudev-dev=3.2.8-r0     && apk add --no-cache   git   nodejs   npm   dbus-dev   glib-dev     && npm config set unsafe-perm true' returned a non-zero code: 2

**Comment by icanos** [comment]
I'll update the Dockerfile and release a new version today

**Comment by icanos** [comment]
A new version is released, 0.4.5, please try that. I have successfully compiled that one on my rig.

**Comment by Kemo90** [comment]
Thanks, well done. Now it works
