### ISSUE TITLE
Light Attributes

### ISSUE THREAD

**Issue by spripe** [icanos/hassio-plejd#78]
Is it possible to add room name/Area into attribute?
            "attributes": {
                "friendly_name": "Taklampa",
                "supported_features": 40
            },

so it will be;
            "attributes": {
                "friendly_name": "Taklampa",
                "room_name": "Vardagsrum",
                "supported_features": 40
            },

**Comment by icanos** [comment]
The room name, is that the room name from Plejd?

**Comment by spripe** [comment]
Yes

**Comment by icanos** [comment]
Can't see that there's any attributes available for lights in the MQTT documentation in HA.
https://www.home-assistant.io/integrations/light.mqtt/

If you've seen some other implementation of this, feel free to post it and I'll look into it :)

**Comment by SweVictor** [comment]
Closing this as "it does not seem to be possible" for now. One option could be to add an option to add the room name to the friendly nameof the light, but at least for me personally I typically include the room name in the light name already to be able to target them with voice commands.
