### ISSUE TITLE
Addon needs to manually be restarted

### ISSUE THREAD

**Issue by spripe** [icanos/hassio-plejd#79]
I'm running version 0.106.6 of Home Assistant.
When I restart HASS, I need to manually restart plejd addon to see my light change status from Unavailable to correct status.

How can I debug this further?

**Comment by icanos** [comment]
Can't say that I've seen that before. I have successfully been able to restart HA without issues. Are you using Mosquitto and have configured HA to send online/offline messages?

**Comment by spripe** [comment]
Thank you, you're correct, it was on my side with the online/offline messages
