### ISSUE TITLE
REL-02

### ISSUE THREAD

**Issue by mattiasjonsson** [icanos/hassio-plejd#8]
Hi Marcus, you can add REL-02 to your list of working Plejd devices. It's still in beta, but should soon be available to the public. So far I have not had any trouble with it. Works great with your add-on :)

**Comment by icanos** [comment]
Oh, nice! Should that maybe be a switch instead of light?

**Comment by mattiasjonsson** [comment]
I guess that would be a nice feature :)

But since I now add my Plejd devices manually (via the config file) to MQTT I can choose what type of entity it should be in HA.
