### ISSUE TITLE
Losing connection

### ISSUE THREAD

**Issue by markusgun** [icanos/hassio-plejd#80]
Hi,
First of all, thank you for your work, I would not have invested in Plejd if there were not any addon for Home assistant.
I have some issue with the Plejd-addon. After boot/reboot of rpi3 with hassio everything with plejd works good. But after some hours, the connection is lost. It does not solve by just restarting the plejd addon or home assistant, I need to go to supervisor-system-reboot to get it working again..
If I restart just plejd addon I get this: 
onDeviceConnected()
plejd-ble: warning: wasn't able to connect to Plejd, will retry.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
(node:290) UnhandledPromiseRejectionWarning: DBusError: Operation already in progress
    at _methodReturnHandlers.(anonymous function) (/plejd/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.MessageBus.conn.on (/plejd/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:198:13)
    at /plejd/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:555:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:290) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:290) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
init()
plejd-ble: error: failed to start discovery. Make sure no other add-on is currently scanning.

My configuration looks like this:
site: Hem
username: **
password: **
mqttBroker: 'mqtt://localhost'
mqttUsername: **
mqttPassword: **
includeRoomsAsLights: false
connectionTimeout: 3
writeQueueWaitTime: 400

Any ideas? Maybe change connectionTimeout, is that in seconds? I can upgrade ti Rpi4 if that would help. 
Can it be that node-red is conflicting?
I am using the latest versions plejd 0.4.4, Home Assistant 0.107.6
BR
Markus

**Comment by jzee** [comment]
I have observed the exact same behavior on my system running on an rpi3b. Restarting the add-on doesn’t fix it, only a system reboot does. 

FYI @markusgun this behavior was observable for me even without node-red, when I added node-red later, this behavior wasn’t affected.

The point that drove me to believe that this can be resource (ie RAM) related is the weird zombie state the add-on is in when it fails, it seems the container just poofs, there are no more logs visible, still hass thinks the add-on was running (offers to REstart it).

For the time being, I worked around it by having an automation that restarts the whole system every night, that has been stable for me for weeks now. I plan to upgrade the HW to an rpi4 any day now. Will report on how it behaves then.

**Comment by markusgun** [comment]
> I have observed the exact same behavior on my system running on an rpi3b. Restarting the add-on doesn’t fix it, only a system reboot does.
> 
> FYI @markusgun this behavior was observable for me even without node-red, when I added node-red later, this behavior wasn’t affected.
> 
> The point that drove me to believe that this can be resource (ie RAM) related is the weird zombie state the add-on is in when it fails, it seems the container just poofs, there are no more logs visible, still hass thinks the add-on was running (offers to REstart it).
> 
> For the time being, I worked around it by having an automation that restarts the whole system every night, that has been stable for me for weeks now. I plan to upgrade the HW to an rpi4 any day now. Will report on how it behaves then.

Thank you @jzee ! Sounds like we have the same behavior yes. I have implemented your work around now and scheduled a reboot.

**Comment by icanos** [comment]
I know that when starting HA, I've seen issues with Node RED interfering when you have something configured that is utilizing BLE that scans at the same time as the Plejd addon tries to do that.

I, however, can't say that I've experienced any issues at all regarding "Operation already in progress." on my RPi 4.

**Comment by jzee** [comment]
I upgraded to an RPi4 last week and keep using the same configuration as before. The system has survived without a reboot since.

**Comment by dennisgranasen** [comment]
I'm getting the same. RPi3b

**Comment by icanos** [comment]
It seems that the dbus implementation in node has some issues with stability on a RPi3b. I'd recommend a RPi4, it works really well on that device.
