### ISSUE TITLE
plejd-ble: disconnecting / what do i do wrong:(

### ISSUE THREAD

**Issue by jmekroth** [icanos/hassio-plejd#82]
plejd-mqtt: connected to mqtt.
plejd-mqtt: discovered light (CTR-01) named Spottar  with PID 11.
plejd-mqtt: discovered light (DIM-01) named Spottar vardagsrum with PID 13.
plejd-ble: disconnecting /org/bluez/hci0/dev_E2_54_4B_D1_36_2C

**Comment by icanos** [comment]
Not sure, need more info than that to be able to help you.

What device are you running?
How have you configured everything?
Etc.
