### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by BertilJ** [icanos/hassio-plejd#83]
I had some issues after messing around with mqtt and last upgrade, also started to see a lot of errors in the add-on log so I decided to uninstall the add-on and reinstall it. But nope, it won't install and I'm getting this error message in the log:

> 20-05-04 20:15:55 INFO (MainThread) [supervisor.addons] Create Home Assistant add-on data folder /data/addons/data/4cb18a39_plejd
> 20-05-04 20:15:55 INFO (SyncWorker_17) [supervisor.docker.addon] Start build 4cb18a39/amd64-addon-plejd:0.4.5
> 20-05-04 20:15:59 ERROR (SyncWorker_17) [supervisor.docker.addon] Can't build 4cb18a39/amd64-addon-plejd:0.4.5: The command '/bin/bash -o pipefail -c apk add --no-cache --virtual .build-dependencies   g++=8.3.0-r0   gcc=8.3.0-r0   libc-dev=0.7.1-r0   linux-headers=4.19.36-r0   make=4.2.1-r2   python=2.7.16-r2   bluez   eudev-dev=3.2.8-r0     && apk add --no-cache   git   nodejs   npm   dbus-dev   glib-dev     && npm config set unsafe-perm true' returned a non-zero code: 2

I've been running this add-on for quite some time without any issues more than a few disconnects that have been repaired by restarting the add-on. So this is really a great add-on.

Another thing I noticed is that the info refers to version 0.5, I've done all updates but I've only reached 0.45 and that's also what I see when I try to install, 0.45

**Comment by staffansson** [comment]
Same thing happened to me yesterday. After some disconnection that couldn’t be fixed with app restart I tried to uninstall and reinstall the addon. But now I can’t install the addon and I’m getting the same error as BertilJ.

**Comment by icanos** [comment]
Fixed the build errors and pushed a new version :)

**Comment by BertilJ** [comment]
Update went well, no issues.

**Comment by richardsorensson** [comment]
This issue seems to have resurfaced over here;
https://github.com/icanos/hassio-plejd/issues/235
