### ISSUE TITLE
Plejd app cant find devices after hassio.plejd connected

### ISSUE THREAD

**Issue by FlyHigh-Swe** [icanos/hassio-plejd#87]
Hi

I am not sure this is an issue or something with my own setup, 

If I activate hassio-pöjed /running on RasberyPi4) I cant communicate with the plecj-.hardware using the plejd app. I need to restart the plejd hardware to be able to communicate with it.

I also have some issues with timeouts Home-assistant, it almost feels as the app and hassio-plejd  cant be used at the same time.

I only have one CRT1 and no gateway.

If noone else have a similar issue its probably somewhere in my setup.
Any tips or tricks that I might have missed?

/Erik S

**Comment by nysmag** [comment]
> it almost feels as the app and hassio-plejd cant be used at the same time.  

That's it, only one 'client' can be connected to the mesh.

**Comment by icanos** [comment]
If you only have one device, you can't be connected with both the app and the HA add-on. One device can only be connected to one client at a time.

As long as you have more than one device, you can connect to the mesh with both app and HA as long as you're connecting to different devices.
