### ISSUE TITLE
plejd/event/scene is zero.

### ISSUE THREAD

**Issue by spripe** [icanos/hassio-plejd#96]
Add-on version: 0.4.7
 There is an update available for this add-on!
 Latest add-on version: null
 Please consider upgrading as soon as possible.
parse error: Expected string key before ':' at line 1, column 4
[01:10:54] ERROR: Unknown HTTP error occured
 System:   (amd64 / qemux86-64)
 Home Assistant version: 0.113.0
 Supervisor version: 229
--------------------------------------------

I have an issue with that MQTT topic: plejd/event/scene is zero.
Earlier there were a Scene ID for each. but now they are zero.

The topic is sent correctly when trigger, but the id is always 0.
Looks like an early behavior when i suggested this feature some month ago :)

Meddelande 256 mottaget på plejd/event/scene vid 01:23 :
{
    "scene": 0
}
QoS: 0 - Retain: false

**Comment by spripe** [comment]
Please see Closed issue: "Scene ID always 0 #35"
You did then mention that it was a bug which was resolved in the new (0.2.5) version :)

**Comment by SweVictor** [comment]
I suppose we can close this then?
