### ISSUE TITLE
Breaking change in version 113.1

### ISSUE THREAD

**Issue by faanskit** [icanos/hassio-plejd#98]
After upgrading to 113.1, the Plejd plugin needs to be restarted following a reboot.
Likely the breaking change for MQTT is to blame.

From the [changelog](https://www.home-assistant.io/blog/2020/07/22/release-113/):
> Birth and will messages are now published by default.
> 
> MQTT birth message defaults to:{"topic": "homeassistant/status", "payload": "online"} MQTT will message defaults to: {"topic": "homeassistant/status", "payload": "offline"}
> 
> MQTT will published also on clean connect from broker.

I suspect changing mqtt.js to listen to homeassistant/status instead of hassio/status will do the trick.

/Marcus

**Comment by johanschelin** [comment]
Also have the same issue and problem and beleive this is the solution.

**Comment by kodarn** [comment]
A simple update of the **`startTopic`**-variable in mqtt.js seems logical.

https://github.com/icanos/hassio-plejd/blob/master/plejd/mqtt.js#L5

Broken: `const startTopic = 'hass/status';`
Fix: `const startTopic = 'homeassistant/status';`

**Comment by icanos** [comment]
Think we need to listen for both since I've included a custom birth message in the documentation.

**Comment by johanschelin** [comment]
Yes I belive that listening to both would solve this for me as well. At the moment I have an automation checking every 30min and restarting the addin if my devices ar unavailable. :)

**Comment by SweVictor** [comment]
This is being addressed in #114 . In the meantime I think it works if you follow the installation instructions and set up `mqtt` correctly in `configuration.json` with the right birth message.

Closing due to working as expected, if not, feel free to re-open.
