### ISSUE TITLE
unable to retrieve session token response: Error: Request failed with status code 404 (and 403)

### ISSUE THREAD

**Issue by jappish84** [icanos/hassio-plejd#99]
Hi, i'm a first time user of the hassio-plejd add-on and I'm having issues getting it to work. 

I'm running my hassio installation on rpi 4 4GB. I have installed and configured the Mosquitto mqtt addon and enabled discovery on the integration page. 

I have also added this to my configuration.yaml:

```
mqtt:
  broker: https://192.168.x.xxx:xxxx
  username: !secret mqtt_uname
  password: !secret mqtt_pw
  discovery: true
  discovery_prefix: homeassistant
  birth_message: 
    topic: 'hass/status'
    payload: 'online'
  will_message: 
    topic: 'hass/status'
    payload: 'offline'
```

my config page looks like this:

```
site: Redacted number
username: redacted@redacted.com
password: redacted
mqttBroker: 'https://192.168.xx.xxx:xxxx'
mqttUsername: redacted
mqttPassword: redacted
includeRoomsAsLights: false
connectionTimeout: 2
writeQueueWaitTime: 400
```

Sometime I get this error:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Plejd
 Adds support for the Swedish home automation devices from Plejd.
-----------------------------------------------------------
 Add-on version: 0.4.7
 There is an update available for this add-on!
 Latest add-on version: null
 Please consider upgrading as soon as possible.
parse error: Expected string key before ':' at line 1, column 4
[14:05:10] ERROR: Unknown HTTP error occured
 System:   (armv7 / raspberrypi4)
 Home Assistant version: 0.112.4
 Supervisor version: 229
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[14:05:11] INFO: Starting the Plejd service...
[14:05:11] INFO: Verified permissions on startup script
[14:05:12] INFO: Executing startup script
[14:05:12] INFO: Wrote plejd.json
[14:05:12] INFO: Running add-on
starting Plejd add-on v. 0.4.7
plejd-api: login()
plejd-api: logging into **redacted**
error: unable to retrieve session token response: Error: Request failed with status code 404
(node:293) UnhandledPromiseRejectionWarning: unable to retrieve session token response: Error: Request failed with status code 404
(node:293) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:293) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
```

and sometime I get this error with a status code 403 instead, will update this post when I get that again

edit: 

Here it is:

```
[14:34:01] INFO: Starting the Plejd service...
[14:34:01] INFO: Verified permissions on startup script
[14:34:01] INFO: Executing startup script
[14:34:02] INFO: Wrote plejd.json
[14:34:02] INFO: Running add-on
starting Plejd add-on v. 0.4.7
plejd-api: login()
plejd-api: logging into ***redacted***
error: unable to retrieve session token response: Error: Request failed with status code 403
(node:10605) UnhandledPromiseRejectionWarning: unable to retrieve session token response: Error: Request failed with status code 403
(node:10605) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:10605) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I should also mention I'm a bit unsure what to use on "site:" is it the top name visible in the app, or the account name visible after pressing the hamburger menu?

**Comment by TorulfDanielsson** [comment]
Regarding te token issues, what is the firmware build on your plejd primarily your dim-01 if you have those?

**Comment by jappish84** [comment]
The fw is v 2.2.1 on dim-01
Build number 20181128160002

**Comment by TorulfDanielsson** [comment]
Same as mine and they are working. The reason i asked was that I had the same problem and the reason was an old firmware (build from 2016....) in my dim-01. Once updated to the firmware you have it worked.

**Comment by TorulfDanielsson** [comment]
I would have tried to update the CTR-01, the new firmware is 3.0.4 and 2.1 seems to be the same generation that i had on my dim-01.

**Comment by jappish84** [comment]
Thanks @TorulfDanielsson I guess I could try that but how do I update the firmware? I can only find a Facebook post where a plejd support rep is referring to contact the support for fw update procedure, isn't the fw updatable by the end user?

**Comment by TorulfDanielsson** [comment]
If you activate the new timer function it will ask you to update the firmware. Position your phone as close as possible to the ctr during the update process.

**Comment by jappish84** [comment]
Thanks, I'll give it a go when I'm at the site

**Comment by jappish84** [comment]
Ok, so sorry this took a while, but now all devices have been updated.

I have: 

6x CTR-01 with FW 3.0.4 (one of these has a BAT-01 with FW 3.0.4, and 4 of these have the same name, not sure if that could cause issues?)
5x DIM-01 with FW 2.2.1
1x DIM-02 with FW 2.4.3
1x REL-02 with FW 1.0.7

For site name I'm using the first visible name in the app, the one in the top of the app, next to the hamburger menu. Is this correct, or should I use the name of the account, that's visible after I press the hamburger menu?

However, I'm getting this log output after the FW update:

´´´
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Plejd
 Adds support for the Swedish home automation devices from Plejd.
-----------------------------------------------------------
 Add-on version: 0.4.7
 There is an update available for this add-on!
 Latest add-on version: null
 Please consider upgrading as soon as possible.
 System: HassOS 4.11  (armv7 / raspberrypi4)
 Home Assistant version: 0.112.4
 Supervisor version: 240
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[14:24:51] INFO: Starting the Plejd service...
[14:24:51] INFO: Verified permissions on startup script
[14:24:51] INFO: Executing startup script
[14:24:52] INFO: Wrote plejd.json
[14:24:52] INFO: Running add-on
starting Plejd add-on v. 0.4.7
plejd-api: login()
plejd-api: logging into ##REDACTED##
error: unable to retrieve session token response: Error: Request failed with status code 404
(node:294) UnhandledPromiseRejectionWarning: unable to retrieve session token response: Error: Request failed with status code 404
(node:294) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:294) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[14:24:53] INFO: Starting the Plejd service...
[14:24:53] INFO: Verified permissions on startup script
[14:24:53] INFO: Executing startup script´´´

**Comment by jappish84** [comment]
Is there anything else I could try to get this to work? What could be causing this issue?

**Comment by jappish84** [comment]
OMG, I am such an imbecile. The root of the problem was simply a typo in the password. Works fine after correction.

Is it safe to update to latest hassio release? Or should I expect mqtt issues?

**Comment by TorulfDanielsson** [comment]
> OMG, I am such an imbecile. The root of the problem was simply a typo in the password. Works fine after correction.
> 
> Is it safe to update to latest hassio release? Or should I expect mqtt issues?

I am on HassOS 4.13 Supervisor 243 Home Assistant 0.115.0b9 , latest beta i presume and plejd works perfectly.

**Comment by jappish84** [comment]
Thanks. I have now updated to the latest stable version.

All plejd devices seem to have been discovered, although, they don't work as expected. All entities but one simply fall back to "off" after trying to turn it "on" . The plejd add-on writes that 8 bytes of data have been sent. I have no additional entries in the home assistant log regarding plejd.

Could this be a range issue or something else?

**Comment by Johhag87** [comment]
I think I have a similar problem.

I'm running hassio installation on Virtual Machine Synology NAS.

[19:23:13] INFO: Starting the Plejd service...
[19:23:13] INFO: Verified permissions on startup script
[19:23:13] INFO: Executing startup script
[19:23:13] INFO: Wrote plejd.json
[19:23:13] INFO: Running add-on
starting Plejd add-on v. 0.4.8
plejd-api: login()
plejd-api: logging into Redacted
error: unable to retrieve session token response: Error: Request failed with status code 403
(node:3161) UnhandledPromiseRejectionWarning: unable to retrieve session token response: Error: Request failed with status code 403
(node:3161) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:3161) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


 configuration.yaml:

mqtt:
  broker: 'https://192.168.xxx.xxx:xxxx'
  username: mqtt
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant
  birth_message: 
    topic: 'hass/status'
    payload: 'online'
  will_message: 
    topic: 'hass/status'
    payload: 'offline'


config plejd page:

site: Redacted
username: redacted@redacted.com
password: redacted
mqttBroker: 'https://192.168.xxx.xxx:xxxx'
mqttUsername: mqtt
mqttPassword: xxxxxxx
includeRoomsAsLights: false
connectionTimeout: 2
writeQueueWaitTime: 400



Can't find anything wrong myself and would really need help!

**Comment by icanos** [comment]
Yes, it could be, although the log should say something about a disconnect etc in that case.

**Comment by SweVictor** [comment]
0.5.0 is released now. Could you please update to that and turn on verbose logging and paste logs here if the problem persists? Thanks

**Comment by SweVictor** [comment]
Closing this due to lack of response. Probably resolved already, otherwise after code restructure PR is in.
